### ISSUE TITLE
Intermittent failure of `tracker::tests::test_timing`

### ISSUE THREAD

**Issue by carols10cents** [influxdata/influxdb_iox#1051]
Every once in a while I get a failure on this timing test, and @NGA-TRAN has seen this as well:

```
$ cargo test tracker::tests::test_timing -p server
running 1 test
test tracker::tests::test_timing ... FAILED

failures:

---- tracker::tests::test_timing stdout ----
thread 'tracker::tests::test_timing' panicked at 'Expected 200000000 got 210815057', server/src/tracker.rs:563:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tracker::tests::test_timing

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 120 filtered out
```

I thought it was a precision/truncation/rounding issue at first glance, but I think I was seeing the `expected` tolerance number that's a round number.

I *think* I've only seen the one with expected tolerance of 200000000 fail, running some more to check :)

**Comment by carols10cents** [comment]
Oop just got a different one:

```
---- tracker::tests::test_timing stdout ----
thread 'tracker::tests::test_timing' panicked at 'Expected 100000000 got 117596962', server/src/tracker.rs:563:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by tustvold** [comment]
I will bump the tolerances, I had made the clearly incorrect assumption that thread sleep was at least accurate to 10ms - but it would appear a greater threshold is needed for some systems - will try bumping up to 25ms.

**Comment by alamb** [comment]
Fails for me sometimes too (maybe it is a mac thing)

```

---- tracker::tests::test_timing stdout ----
thread 'tracker::tests::test_timing' panicked at 'Expected 200000000 got 210137847', server/src/tracker.rs:563:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
