### ISSUE TITLE
assertion failed:  self.time_closed.is_none()

### ISSUE THREAD

**Issue by mkmik** [influxdata/influxdb_iox#1636]
I noticed this in the IOx internal staging environment.

```
level=error msg="thread 'tokio-runtime-worker' panicked at 'assertion failed: self.time_closed.is_none()', server/src/db/catalog/chunk.rs:478:17" target="panic_logging" location="panic_logging/src/lib.rs:110" time=1623055009864614071
```

__Logs:__
```
level=info msg="moving chunk to read buffer" partition_key="2021-06-04 18:00:00" chunk_id=13 span=9 target="server::db::lifecycle" location="server/src/db/lifecycle.rs:316" time=1623055009863286703
level=warn msg="soft limited exceeded, but no chunks found that can be evicted. Check lifecycle rules" db_name=844910ece80be8bc_3c0bd4c89186ca89 soft_limit=42949672960 buffer_size=45103829491 span=9 target="server::db::lifecycle" location="server/src/db/lifecycle.rs:236" time=1623055009863656129
level=debug msg="background task loading chunk to read buffer" name=844910ece80be8bc_3c0bd4c89186ca89 partition_key="2021-06-04 18:00:00" table_name=query_influxdb_source_read_request_duration_seconds chunk_id=13 target="server::db" location="server/src/db.rs:812" time=1623055009863691551
level=error msg="thread 'tokio-runtime-worker' panicked at 'assertion failed: self.time_closed.is_none()', server/src/db/catalog/chunk.rs:478:17" target="panic_logging" location="panic_logging/src/lib.rs:110" time=1623055009863698818
thread 'tokio-runtime-worker' panicked at 'assertion failed: self.time_closed.is_none()', server/src/db/catalog/chunk.rs:478:17
level=info msg="moving chunk to read buffer" partition_key="2021-06-04 18:00:00" chunk_id=13 span=9 target="server::db::lifecycle" location="server/src/db/lifecycle.rs:316" time=1623055009864198785
level=warn msg="soft limited exceeded, but no chunks found that can be evicted. Check lifecycle rules" db_name=844910ece80be8bc_3c0bd4c89186ca89 soft_limit=42949672960 buffer_size=45103829491 span=9 target="server::db::lifecycle" location="server/src/db/lifecycle.rs:236" time=1623055009864570825
level=debug msg="background task loading chunk to read buffer" name=844910ece80be8bc_3c0bd4c89186ca89 partition_key="2021-06-04 18:00:00" table_name=query_influxdb_source_read_request_duration_seconds chunk_id=13 target="server::db" location="server/src/db.rs:812" time=1623055009864606606
level=error msg="thread 'tokio-runtime-worker' panicked at 'assertion failed: self.time_closed.is_none()', server/src/db/catalog/chunk.rs:478:17" target="panic_logging" location="panic_logging/src/lib.rs:110" time=1623055009864614071
```

**Comment by mkmik** [comment]
the `catalog_chunks_total` for that database seems quiet for a while (we have hit the configured retention period for our staging env)

![image](https://user-images.githubusercontent.com/52673/120989130-80c37800-c77f-11eb-90bd-d5d2a8502fb9.png)
