### ISSUE TITLE
Panic during ingestion - self.time_closed.is_none()

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb_iox#1812]
```
Jun 25 19:22:13.224  INFO read_buffer::chunk: row group added rows=210000 columns=3 rg_size=8498851 mub_rb_size=10317952 mub_rb_comp=17.63% raw_size_null=13978961 raw_size_no_null=13978961 raw_rb_comp=39.20% table_name="m0" compressing_took=2.257454541s
Jun 25 19:22:13.248  INFO db_worker{database=org_bucket}: server::db::lifecycle: writing to object store chunk=Chunk('org_bucket':'m0':'2021-06-25 18:00:00':97)
Jun 25 19:22:13.289  INFO parquet_file::catalog: transaction committed tkey=TransactionKey { revision_counter: 48, uuid: 9b3759c8-67c7-4b79-b164-c6f26bef14a2 }
Jun 25 19:22:13.289  INFO parquet_file::catalog: transaction started tkey=TransactionKey { revision_counter: 49, uuid: c82f6bc9-4634-45c7-9821-ad498e78385b }
Jun 25 19:22:13.725  INFO server_worker: tracker::task::history: job finished job=TaskTracker { id: TaskId(93), state: TrackerState { start_instant: Instant { t: 6951874106106 }, cancel_token: CancellationToken { is_cancelled: false }, cpu_nanos: 2297794041, wall_nanos: 4137521041, created_futures: 1, pending_futures: 0, pending_registrations: 0, notify: Notify { state: 8, waiters: Mutex(Mutex { data: LinkedList { head: None, tail: None } }) } }, metadata: CompactChunks { db_name: "org_bucket", partition_key: "2021-06-25 18:00:00", table_name: "m0", chunks: [93] } }
Jun 25 19:22:13.725  INFO server_worker: tracker::task::history: job finished job=TaskTracker { id: TaskId(96), state: TrackerState { start_instant: Instant { t: 6951945225258 }, cancel_token: CancellationToken { is_cancelled: false }, cpu_nanos: 1215292500, wall_nanos: 1215391708, created_futures: 1, pending_futures: 0, pending_registrations: 0, notify: Notify { state: 8, waiters: Mutex(Mutex { data: LinkedList { head: None, tail: None } }) } }, metadata: WriteChunk { db_name: "org_bucket", partition_key: "2021-06-25 18:00:00", table_name: "m0", chunk_id: 96 } }
Jun 25 19:22:14.182  INFO parquet_file::catalog: transaction committed tkey=TransactionKey { revision_counter: 49, uuid: c82f6bc9-4634-45c7-9821-ad498e78385b }
Jun 25 19:22:14.725  INFO server_worker: tracker::task::history: job finished job=TaskTracker { id: TaskId(97), state: TrackerState { start_instant: Instant { t: 6951973411490 }, cancel_token: CancellationToken { is_cancelled: false }, cpu_nanos: 893004333, wall_nanos: 933943666, created_futures: 1, pending_futures: 0, pending_registrations: 0, notify: Notify { state: 8, waiters: Mutex(Mutex { data: LinkedList { head: None, tail: None } }) } }, metadata: WriteChunk { db_name: "org_bucket", partition_key: "2021-06-25 18:00:00", table_name: "m0", chunk_id: 97 } }
Jun 25 19:22:25.826 ERROR panic_logging: thread 'tokio-runtime-worker' panicked at 'attempt to subtract with overflow', mutable_buffer/src/chunk/snapshot.rs:162:25
thread 'tokio-runtime-worker' panicked at 'attempt to subtract with overflow', mutable_buffer/src/chunk/snapshot.rs:162:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Jun 25 19:22:25.912 ERROR panic_logging: thread 'tokio-runtime-worker' panicked at 'assertion failed: self.time_closed.is_none()', server/src/db/catalog/chunk.rs:521:17
thread 'tokio-runtime-worker' panicked at 'assertion failed: self.time_closed.is_none()', server/src/db/catalog/chunk.rs:521:17
Jun 25 19:22:26.212 ERROR panic_logging: thread 'tokio-runtime-worker' panicked at 'assertion failed: self.time_closed.is_none()', server/src/db/catalog/chunk.rs:521:17
thread 'tokio-runtime-worker' panicked at 'assertion failed: self.time_closed.is_none()', server/src/db/catalog/chunk.rs:521:17
Jun 25 19:22:26.267 ERROR panic_logging: thread 'tokio-runtime-worker' panicked at 'assertion failed: self.time_closed.is_none()', server/src/db/catalog/chunk.rs:521:17
thread 'tokio-runtime-worker' panicked at 'assertion failed: self.time_closed.is_none()', server/src/db/catalog/chunk.rs:521:17
Jun 25 19:22:26.323 ERROR panic_logging: thread 'tokio-runtime-worker' panicked at 'assertion failed: self.time_closed.is_none()', server/src/db/catalog/chunk.rs:521:17
thread 'tokio-runtime-worker' panicked at 'assertion failed: self.time_closed.is_none()', server/src/db/catalog/chunk.rs:521:17
```

__Steps to reproduce:__

1. checkout IOx (running 9cfabfd here).
2. run IOx with `INFLUXDB_IOX_ID=42 LOG_FILTER=debug RUST_LOG=debug ./target/debug/influxdb_iox run`
3. create a test database `./target/debug/influxdb_iox database create org_bucket`
4. go fetch our internal repo for Cloud 2.
5. Install @e-dard's modified version of [inch](https://github.com/influxdata/inch) from within the Cloud 2 repo using `make inch`.
6. Run `inch` with these settings `bin/inch -bucket bucket -org org -host "http://localhost:8080" -c 10 -t 1000000,100000,100000,100000 -p 10` 

Observed the panics in the logs that I have pasted above.

__Expected behaviour:__

No panics!

__Actual behaviour:__

Panics many!

__Environment info:__

IOx was built in release mode on a mac with an M1 CPU.

**Comment by crepererum** [comment]
Looking at the code that modifies `time_closed`:

- the struct is always initialized to with `time_closed: None`
- the only way to modify it is in `Chunk::freeze` if the stage is Open
- there are no ordinary exists between the check and the stage modification
- `Chunk` is takes as `&mut self` during that section

So I can only conclude that we panic in-between. And indeed looking at the logs you've provided that seems to be the case:

```
Jun 25 19:22:25.826 ERROR panic_logging: thread 'tokio-runtime-worker' panicked at 'attempt to subtract with overflow', mutable_buffer/src/chunk/snapshot.rs:162:25
```

So the code (as probably MANY other places) is not panic-safe. That's also what I've stated in #1694 (CC @tustvold ). Also panic-safety is inherently hard to test.

**Comment by e-dard** [comment]
I can no longer reproduce this with a build that includes #1825
