### ISSUE TITLE
Panics are rendered in structured log output but also emitted directly

### ISSUE THREAD

**Issue by mkmik** [influxdata/influxdb_iox#1818]
This is an excerpt of an iox node that is panicking;

```
level=error msg="thread \'tokio-runtime-worker\' panicked at \'assertion failed: sequence.number > n.max\', mutable_buffer/src/persistence_windows.rs:234:17" target="panic_logging" location="panic_logging/src/lib.rs:110" t
ime=1624876860063152256
thread 'tokio-runtime-worker' panicked at 'assertion failed: sequence.number > n.max', mutable_buffer/src/persistence_windows.rs:234:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
level=error msg="thread \'tokio-runtime-worker\' panicked at \'assertion failed: sequence.number > n.max\', mutable_buffer/src/persistence_windows.rs:234:17" target="panic_logging" location="panic_logging/src/lib.rs:110" time=1624876860283807256
level=error msg="thread \'tokio-runtime-worker\' panicked at \'assertion failed: sequence.number > n.max\', mutable_buffer/src/persistence_windows.rs:234:17" target="panic_logging" location="panic_logging/src/lib.rs:110" time=1624876860323513758
thread 'tokio-runtime-worker' panicked at 'assertion failed: sequence.number > n.max', mutable_buffer/src/persistence_windows.rs:234:17
thread 'tokio-runtime-worker' panicked at 'assertion failed: sequence.number > n.max', mutable_buffer/src/persistence_windows.rs:234:17
```

TODO: check if this causes parsing problems at the log collection pipeline (e.g. fluentd). Structured logs are (by default) emitted at stdout, while panics are on stderr; `kubectl logs` doesn't let you tell the difference but perhaps the log collector can.

**Comment by crepererum** [comment]
Also see #1694 which is somewhat related.
