### ISSUE TITLE
Chunk Snapshot panic

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb_iox#1820]
Observed a panic locally running `inch`. See https://github.com/influxdata/influxdb_iox/issues/1812 for details on how to run that.

```Jun 28 12:07:44.446  INFO influxdb_iox::influxdb_ioxd: InfluxDB IOx server ready git_hash="ed98812c2afd298e62f91d3b7656be7b79858ca8"
Jun 28 12:07:44.470  INFO server_worker: server: started background worker
Jun 28 12:07:44.470  INFO server_worker: server::init: loaded databases, server is initalized
Jun 28 12:07:47.673  INFO server::db: Found NO existing catalog for DB org_bucket, creating new one
Jun 28 12:07:47.674  INFO parquet_file::catalog: transaction started tkey=TransactionKey { revision_counter: 0, uuid: 96b768dc-cc34-48d6-8017-d506a6313338 }
Jun 28 12:07:47.674  INFO parquet_file::catalog: transaction committed tkey=TransactionKey { revision_counter: 0, uuid: 96b768dc-cc34-48d6-8017-d506a6313338 }
Jun 28 12:07:47.675  INFO db_worker{database=org_bucket}: server::db: started background worker
Jun 28 12:08:28.427 ERROR panic_logging: thread 'tokio-runtime-worker' panicked at 'attempt to subtract with overflow', mutable_buffer/src/chunk/snapshot.rs:162:25
thread 'tokio-runtime-worker' panicked at 'attempt to subtract with overflow', mutable_buffer/src/chunk/snapshot.rs:162:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```

**Comment by e-dard** [comment]
Reproduced locally:

```
Jun 28 14:14:24.509  INFO db_worker{database=org_bucket}: server::db: started background worker
[mutable_buffer/src/chunk/snapshot.rs:162] array.get_array_memory_size() = 1066448
[mutable_buffer/src/chunk/snapshot.rs:162] array.get_buffer_memory_size() = 532864
[mutable_buffer/src/chunk/snapshot.rs:163] dictionary_size = 818256
[mutable_buffer/src/chunk/snapshot.rs:162] array.get_array_memory_size() = 248656
[mutable_buffer/src/chunk/snapshot.rs:162] array.get_buffer_memory_size() = 123968
[mutable_buffer/src/chunk/snapshot.rs:163] dictionary_size = 818256```

The issue here is that a column's size can be smaller than the overall shared dicationary size, leading to an overflow issue here:

https://github.com/influxdata/influxdb_iox/blob/9456ae5d392ff4641ea2d46955774ac20c4fcdcc/mutable_buffer/src/chunk/snapshot.rs#L162-L163
