### ISSUE TITLE
Possible flaky test db::tests::chunk_summaries

### ISSUE THREAD

**Issue by mkmik** [influxdata/influxdb_iox#2033]
```
ailures:

---- db::tests::chunk_summaries stdout ----
Partitions: ["1970-01-01T00", "1970-01-05T15"]Partitions2: ["1970-01-05T15", "1970-01-01T00"]thread 'db::tests::chunk_summaries' panicked at 'assertion failed: `(left == right)`
  left: `[ChunkSummary { partition_key: "1970-01-01T00", table_name: "cpu", id: 2, storage: ReadBufferAndObjectStore, lifecycle_action: None, memory_bytes: 3082, object_store_bytes: 1524, row_count: 2, time_of_first_write: None, time_of_last_write: None, time_closed: None }, ChunkSummary { partition_key: "1970-01-05T15", table_name: "cpu", id: 0, storage: ClosedMutableBuffer, lifecycle_action: None, memory_bytes: 2398, object_store_bytes: 0, row_count: 1, time_of_first_write: None, time_of_last_write: None, time_closed: None }, ChunkSummary { partition_key: "1970-01-05T15", table_name: "cpu", id: 1, storage: OpenMutableBuffer, lifecycle_action: None, memory_bytes: 87, object_store_bytes: 0, row_count: 1, time_of_first_write: None, time_of_last_write: None, time_closed: None }]`,
 right: `[ChunkSummary { partition_key: "1970-01-01T00", table_name: "cpu", id: 2, storage: ReadBufferAndObjectStore, lifecycle_action: None, memory_bytes: 3082, object_store_bytes: 1520, row_count: 2, time_of_first_write: None, time_of_last_write: None, time_closed: None }, ChunkSummary { partition_key: "1970-01-05T15", table_name: "cpu", id: 0, storage: ClosedMutableBuffer, lifecycle_action: None, memory_bytes: 2398, object_store_bytes: 0, row_count: 1, time_of_first_write: None, time_of_last_write: None, time_closed: None }, ChunkSummary { partition_key: "1970-01-05T15", table_name: "cpu", id: 1, storage: OpenMutableBuffer, lifecycle_action: None, memory_bytes: 87, object_store_bytes: 0, row_count: 1, time_of_first_write: None, time_of_last_write: None, time_closed: None }]`: 

expected:
[
    ChunkSummary {
        partition_key: "1970-01-01T00",
        table_name: "cpu",
        id: 2,
        storage: ReadBufferAndObjectStore,
        lifecycle_action: None,
        memory_bytes: 3082,
        object_store_bytes: 1524,
        row_count: 2,
        time_of_first_write: None,
        time_of_last_write: None,
        time_closed: None,
    },
    ChunkSummary {
        partition_key: "1970-01-05T15",
        table_name: "cpu",
        id: 0,
        storage: ClosedMutableBuffer,
        lifecycle_action: None,
        memory_bytes: 2398,
        object_store_bytes: 0,
        row_count: 1,
        time_of_first_write: None,
        time_of_last_write: None,
        time_closed: None,
    },
    ChunkSummary {
        partition_key: "1970-01-05T15",
        table_name: "cpu",
        id: 1,
        storage: OpenMutableBuffer,
        lifecycle_action: None,
        memory_bytes: 87,
        object_store_bytes: 0,
        row_count: 1,
        time_of_first_write: None,
        time_of_last_write: None,
        time_closed: None,
    },
]

actual:[
    ChunkSummary {
        partition_key: "1970-01-01T00",
        table_name: "cpu",
        id: 2,
        storage: ReadBufferAndObjectStore,
        lifecycle_action: None,
        memory_bytes: 3082,
        object_store_bytes: 1520,
        row_count: 2,
        time_of_first_write: None,
        time_of_last_write: None,
        time_closed: None,
    },
    ChunkSummary {
        partition_key: "1970-01-05T15",
        table_name: "cpu",
        id: 0,
        storage: ClosedMutableBuffer,
        lifecycle_action: None,
        memory_bytes: 2398,
        object_store_bytes: 0,
        row_count: 1,
        time_of_first_write: None,
        time_of_last_write: None,
        time_closed: None,
    },
    ChunkSummary {
        partition_key: "1970-01-05T15",
        table_name: "cpu",
        id: 1,
        storage: OpenMutableBuffer,
        lifecycle_action: None,
        memory_bytes: 87,
        object_store_bytes: 0,
        row_count: 1,
        time_of_first_write: None,
        time_of_last_write: None,
        time_closed: None,
    },
]

', server/src/db.rs:2530:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   2: core::panicking::assert_failed::inner
   3: core::panicking::assert_failed
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:143:5
   4: server::db::tests::chunk_summaries::{{closure}}
             at ./src/db.rs:2530:9
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/future/mod.rs:80:19
   6: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/future/future.rs:120:9
   7: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/basic_scheduler.rs:213:62
   8: tokio::coop::with_budget::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/coop.rs:106:9
   9: std::thread::local::LocalKey<T>::try_with
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/thread/local.rs:376:16
  10: std::thread::local::LocalKey<T>::with
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/thread/local.rs:352:9
  11: tokio::coop::with_budget
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/coop.rs:99:5
  12: tokio::coop::budget
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/coop.rs:76:5
  13: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/basic_scheduler.rs:213:39
  14: tokio::runtime::basic_scheduler::enter::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/basic_scheduler.rs:323:29
  15: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/macros/scoped_tls.rs:61:9
  16: tokio::runtime::basic_scheduler::enter
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/basic_scheduler.rs:323:5
  17: tokio::runtime::basic_scheduler::Inner<P>::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/basic_scheduler.rs:202:9
  18: tokio::runtime::basic_scheduler::InnerGuard<P>::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/basic_scheduler.rs:516:9
  19: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/basic_scheduler.rs:162:24
  20: tokio::runtime::Runtime::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/mod.rs:450:46
  21: server::db::tests::chunk_summaries
             at ./src/db.rs:2538:9
  22: server::db::tests::chunk_summaries::{{closure}}
             at ./src/db.rs:2455:11
  23: core::ops::function::FnOnce::call_once
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:227:5
  24: core::ops::function::FnOnce::call_once
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    db::tests::chunk_summaries
```

See https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/8205/workflows/d27311fa-032c-4e10-ba5c-d05d654d7648/jobs/41862

**Comment by alamb** [comment]
I believe this is fixed by https://github.com/influxdata/influxdb_iox/issues/2033
