### ISSUE TITLE
Kafka reader stopped because of a panic in the MUB

### ISSUE THREAD

**Issue by mkmik** [influxdata/influxdb_iox#2066]
kiox-query-4000 running at commit 07c8dea6b9d77c2aeb6637ae546f3d69b458a6c3

panicked with:

```
thread 'tokio-runtime-worker' panicked at 'failed to fit into offset type', /home/rust/project/arrow_util/src/string.rs:57:44
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/option.rs:1241:5
   3: core::option::Option<T>::expect
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/option.rs:349:21
   4: arrow_util::string::PackedStringArray<K>::append
             at ./home/rust/project/arrow_util/src/string.rs:57:22
   5: mutable_buffer::column::Column::append
             at ./home/rust/project/mutable_buffer/src/column.rs:209:21
   6: mutable_buffer::chunk::MBChunk::write_columns
             at ./home/rust/project/mutable_buffer/src/chunk.rs:338:13
   7: mutable_buffer::chunk::MBChunk::write_table_batch
             at ./home/rust/project/mutable_buffer/src/chunk.rs:141:9
   8: server::db::Db::store_sequenced_entry
             at ./home/rust/project/server/src/db.rs:853:45
   9: server::db::Db::stream_in_sequenced_entries::{{closure}}::{{closure}}::{{closure}}
             at ./home/rust/project/server/src/db.rs:695:33
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/future/mod.rs:80:19
  11: <futures_util::stream::stream::for_each::ForEach<St,Fut,F> as core::future::future::Future>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/stream/stream/for_each.rs:68:24
  12: server::db::Db::stream_in_sequenced_entries::{{closure}}
             at ./home/rust/project/server/src/db.rs:682:9
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/future/mod.rs:80:19
  14: <futures_util::future::maybe_done::MaybeDone<Fut> as core::future::future::Future>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/future/maybe_done.rs:95:38
  15: <futures_util::future::join_all::JoinAll<F> as core::future::future::Future>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/future/join_all.rs:97:16
  16: server::db::Db::background_worker::{{closure}}::{{closure}}::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/macros/select.rs:505:49
  17: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/future/poll_fn.rs:38:9
  18: server::db::Db::background_worker::{{closure}}::{{closure}}
             at ./home/rust/project/server/src/db.rs:665:21
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/future/mod.rs:80:19
  20: <tokio::future::maybe_done::MaybeDone<Fut> as core::future::future::Future>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/future/maybe_done.rs:68:48
  21: server::db::Db::background_worker::{{closure}}::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/macros/join.rs:86:20
  22: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/future/poll_fn.rs:38:9
  23: server::db::Db::background_worker::{{closure}}
             at ./home/rust/project/server/src/db.rs:618:9
  24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/future/mod.rs:80:19
  25: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.26/src/instrument.rs:151:9
  26: server::config::DatabaseHandle::advance_init::{{closure}}
             at ./home/rust/project/server/src/config.rs:670:21
  27: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/future/mod.rs:80:19
  28: tokio::runtime::task::core::CoreStage<T>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/core.rs:233:13
  29: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/harness.rs:438:23
  30: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:344:9
  31: std::panicking::try::do_call
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:379:40
  32: std::panicking::try
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:343:19
  33: std::panic::catch_unwind
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:431:14
  34: tokio::runtime::task::harness::poll_future
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/harness.rs:425:19
  35: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/harness.rs:89:9
  36: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/harness.rs:59:15
  37: tokio::runtime::task::raw::RawTask::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/raw.rs:70:18
  38: tokio::runtime::task::Notified<S>::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/mod.rs:171:9
  39: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/thread_pool/worker.rs:349:13
  40: tokio::coop::with_budget::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/coop.rs:106:9
  41: std::thread::local::LocalKey<T>::try_with
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/thread/local.rs:376:16
  42: std::thread::local::LocalKey<T>::with
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/thread/local.rs:352:9
  43: tokio::coop::with_budget
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/coop.rs:99:5
  44: tokio::coop::budget
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/coop.rs:76:5
  45: tokio::runtime::thread_pool::worker::Context::run_task
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/thread_pool/worker.rs:348:9
  46: tokio::runtime::thread_pool::worker::Context::run
  47: tokio::runtime::thread_pool::worker::run::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/thread_pool/worker.rs:303:17
  48: tokio::macros::scoped_tls::ScopedKey<T>::set
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/macros/scoped_tls.rs:61:9
  49: tokio::runtime::thread_pool::worker::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/thread_pool/worker.rs:300:5
  50: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/thread_pool/worker.rs:279:45
  51: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/blocking/task.rs:42:21
  52: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/core.rs:243:17
  53: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/loom/std/unsafe_cell.rs:14:9
  54: tokio::runtime::task::core::CoreStage<T>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/core.rs:233:13
  55: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/harness.rs:438:23
  56: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:344:9
  57: std::panicking::try::do_call
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:379:40
  58: std::panicking::try
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:343:19
  59: std::panic::catch_unwind
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:431:14
  60: tokio::runtime::task::harness::poll_future
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/harness.rs:425:19
  61: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/harness.rs:89:9
  62: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/harness.rs:59:15
  63: tokio::runtime::task::raw::RawTask::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/raw.rs:70:18
  64: tokio::runtime::task::Notified<S>::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/mod.rs:171:9
  65: tokio::runtime::blocking::pool::Inner::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/blocking/pool.rs:265:17
  66: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/blocking/pool.rs:245:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The panic occurred at: 2021-07-20T10:17:41Z

The cpu metric drops to 0 and correlates with the time of the panic:

![image](https://user-images.githubusercontent.com/52673/126324439-1819836f-615d-4535-9bcb-2c8c30ae7920.png)

It seems that this panic effectively stopped the kafka reader from progressing.

**Comment by mkmik** [comment]
```
OBSERVER> select table_name,memory_bytes,row_count from chunks where storage = 'OpenMutableBuffer' order by memory_bytes desc limit 10;
+----------------------------------------------+--------------+-----------+
| table_name                                   | memory_bytes | row_count |
+----------------------------------------------+--------------+-----------+
| query_log                                    | 2149747767   | 26301     |
| query_log                                    | 1286049746   | 21286     |
| storage_backup_request_duration_seconds      | 31555188     | 96892     |
| storage_persistence_request_duration_seconds | 31129444     | 94339     |
| query_log                                    | 24823496     | 83108     |
| auth_prometheus_request_duration_seconds     | 22953836     | 87804     |
| storage_compactions_duration_seconds         | 21986603     | 71961     |
| storage_tsi_index_series_created_duration_ns | 21751289     | 71190     |
| query_log                                    | 20093872     | 72692     |
| auth_prometheus_request_duration_seconds     | 14774544     | 56402     |
+----------------------------------------------+--------------+-----------+
```

**Comment by mkmik** [comment]
Tried to query but:

```
level=error msg="thread 'IOx Query Executor Thread' panicked at 'UNKNOWN', mutable_buffer/src/chunk/snapshot.rs:50:14" target="panic_logging" location="panic_logging/src/lib.rs:110" time=1626786900242488260
thread 'IOx Query Executor Thread' panicked at 'called `Result::unwrap()` on an `Err` value: ArrowError { source: InvalidArgumentError("all columns in a record batch must have the same length") }', mutable_buffer/src/chunk/snapshot.rs:50:14
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/result.rs:1355:5
   3: core::result::Result<T,E>::unwrap
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/result.rs:1037:23
   4: mutable_buffer::chunk::snapshot::ChunkSnapshot::new
             at ./home/rust/project/mutable_buffer/src/chunk/snapshot.rs:47:21
   5: mutable_buffer::chunk::MBChunk::snapshot
             at ./home/rust/project/mutable_buffer/src/chunk.rs:162:33
   6: server::db::chunk::DbChunk::snapshot
             at ./home/rust/project/server/src/db/chunk.rs:110:32
   7: core::ops::function::Fn::call
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:70:5
   8: server::db::catalog::Catalog::filtered_chunks::{{closure}}
             at ./home/rust/project/server/src/db/catalog.rs:294:17
   9: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:280:13
  10: core::option::Option<T>::map
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/option.rs:487:29
  11: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/iter/adapters/map.rs:101:9
  12: alloc::vec::Vec<T,A>::extend_desugared
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/vec/mod.rs:2499:35
  13: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/vec/spec_extend.rs:18:9
  14: <alloc::vec::Vec<T,A> as core::iter::traits::collect::Extend<T>>::extend
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/vec/mod.rs:2474:9
  15: server::db::catalog::Catalog::filtered_chunks
             at ./home/rust/project/server/src/db/catalog.rs:292:13
  16: server::db::access::ChunkAccess::candidate_chunks
             at ./home/rust/project/server/src/db/access.rs:141:22
  17: <server::db::access::DbSchemaProvider as datafusion::catalog::schema::SchemaProvider>::table
             at ./home/rust/project/server/src/db/access.rs:271:22
  18: <datafusion::execution::context::ExecutionContextState as datafusion::sql::planner::ContextProvider>::get_table_provider
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/3fb600d/datafusion/src/execution/context.rs:871:9
  19: datafusion::sql::planner::SqlToRel<S>::create_relation
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/3fb600d/datafusion/src/sql/planner.rs:435:25
  20: datafusion::sql::planner::SqlToRel<S>::plan_table_with_joins
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/3fb600d/datafusion/src/sql/planner.rs:309:20
  21: datafusion::sql::planner::SqlToRel<S>::plan_from_tables::{{closure}}
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/3fb600d/datafusion/src/sql/planner.rs:299:26
  22: core::iter::adapters::map::map_try_fold::{{closure}}
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/iter/adapters/map.rs:89:28
  23: core::iter::traits::iterator::Iterator::try_fold
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/iter/traits/iterator.rs:2006:21
  24: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/iter/adapters/map.rs:115:9
  25: <core::iter::adapters::ResultShunt<I,E> as core::iter::traits::iterator::Iterator>::try_fold
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/iter/adapters/mod.rs:173:9
  26: core::iter::traits::iterator::Iterator::find
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/iter/traits/iterator.rs:2358:9
  27: <core::iter::adapters::ResultShunt<I,E> as core::iter::traits::iterator::Iterator>::next
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/iter/adapters/mod.rs:155:9
  28: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/vec/spec_from_iter_nested.rs:23:32
  29: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/vec/spec_from_iter.rs:36:9
  30: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/vec/mod.rs:2404:9
  31: core::iter::traits::iterator::Iterator::collect
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/iter/traits/iterator.rs:1788:9
  32: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter::{{closure}}
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/result.rs:1625:53
  33: core::iter::adapters::process_results
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/iter/adapters/mod.rs:144:17
  34: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/result.rs:1625:9
  35: core::iter::traits::iterator::Iterator::collect
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/iter/traits/iterator.rs:1788:9
  36: datafusion::sql::planner::SqlToRel<S>::plan_from_tables
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/3fb600d/datafusion/src/sql/planner.rs:297:18
  37: datafusion::sql::planner::SqlToRel<S>::select_to_plan
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/3fb600d/datafusion/src/sql/planner.rs:510:21
  38: datafusion::sql::planner::SqlToRel<S>::set_expr_to_plan
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/3fb600d/datafusion/src/sql/planner.rs:159:35
  39: datafusion::sql::planner::SqlToRel<S>::query_to_plan_with_alias
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/3fb600d/datafusion/src/sql/planner.rs:145:20
  40: datafusion::sql::planner::SqlToRel<S>::query_to_plan
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/3fb600d/datafusion/src/sql/planner.rs:121:9
  41: datafusion::sql::planner::SqlToRel<S>::sql_statement_to_plan
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/3fb600d/datafusion/src/sql/planner.rs:105:40
  42: datafusion::sql::planner::SqlToRel<S>::statement_to_plan
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/3fb600d/datafusion/src/sql/planner.rs:93:42
  43: datafusion::execution::context::ExecutionContext::create_logical_plan
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/3fb600d/datafusion/src/execution/context.rs:225:9
  44: query::exec::context::IOxExecutionContext::prepare_sql
....
```

**Comment by e-dard** [comment]
FYI this is happening on `query-3000` since yesterday too. I have been investingating the cause of it (the cause is that there is too much data in a column to make a `StringArray`). But the reasoning behind it is some data that we push internally. I would like to understand more about that data and the use-case to figure out the best way to handle this. 

This is somewhat blocked on other issues at the moment such as:

 - https://github.com/influxdata/influxdb_iox/issues/2075
 - https://github.com/influxdata/influxdb_iox/issues/2071
