### ISSUE TITLE
Statistics count mismatch: IOx panicking on failed non-null value assertion

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb_iox#2124]
https://github.com/influxdata/influxdb_iox/pull/2103 aligned the tracking of all value counts within columns and also all non-null counts, across the various execution engines (MUB, RUB, Parquet).

This has now been deployed internally and I have seen the panic below.

It is panicking here:

https://github.com/influxdata/influxdb_iox/blob/6ae1ba57b91647ff57708f8b4a26a5ef480a5902/data_types/src/partition_metadata.rs#L155-L166

And given the specific column (`os`) is known to be reasonably sparse I suspect it has something to do with the NULL values in there.

```
level=error msg="thread 'tokio-runtime-worker' panicked at 'UNKNOWN', data_types/src/partition_metadata.rs:156:13" span=549755813910 target="panic_logging" location="panic_logging/src/lib.rs:110" time=1627333382210685572
thread 'tokio-runtime-worker' panicked at 'assertion failed: `(left == right)`
  left: `87389`,
 right: `100194`: Mismatch counts in table http_api_request_duration_seconds column os, expected 100194 got 87389', data_types/src/partition_metadata.rs:156:13
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   2: core::panicking::assert_failed::inner
   3: core::panicking::assert_failed
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:143:5
   4: data_types::partition_metadata::TableSummary::total_count
             at ./home/rust/project/data_types/src/partition_metadata.rs:156:13
   5: server::db::lifecycle::compact::compact_chunks::{{closure}}
             at ./home/rust/project/server/src/db/lifecycle/compact.rs:49:27
   6: core::iter::adapters::map::map_try_fold::{{closure}}
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/iter/adapters/map.rs:89:28
   7: core::iter::traits::iterator::Iterator::try_fold
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/iter/traits/iterator.rs:2006:21
   8: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/iter/adapters/map.rs:115:9
   9: <core::iter::adapters::ResultShunt<I,E> as core::iter::traits::iterator::Iterator>::try_fold
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/iter/adapters/mod.rs:173:9
  10: core::iter::traits::iterator::Iterator::find
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/iter/traits/iterator.rs:2358:9
  11: <core::iter::adapters::ResultShunt<I,E> as core::iter::traits::iterator::Iterator>::next
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/iter/adapters/mod.rs:155:9
  12: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/vec/spec_from_iter_nested.rs:23:32
  13: alloc::vec::source_iter_marker::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/vec/source_iter_marker.rs:41:20
  14: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/vec/mod.rs:2404:9
  15: core::iter::traits::iterator::Iterator::collect
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/iter/traits/iterator.rs:1788:9
  16: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter::{{closure}}
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/result.rs:1625:53
  17: core::iter::adapters::process_results
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/iter/adapters/mod.rs:144:17
  18: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/result.rs:1625:9
  19: core::iter::traits::iterator::Iterator::collect
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/iter/traits/iterator.rs:1788:9
  20: server::db::lifecycle::compact::compact_chunks
             at ./home/rust/project/server/src/db/lifecycle/compact.rs:42:24
  21: <server::db::lifecycle::LockableCatalogPartition as lifecycle::LockablePartition>::compact_chunks
             at ./home/rust/project/server/src/db/lifecycle.rs:200:30
  22: lifecycle::policy::LifecyclePolicy<M>::maybe_compact_chunks
             at ./home/rust/project/lifecycle/src/policy.rs:268:27
  23: lifecycle::policy::LifecyclePolicy<M>::check_for_work
             at ./home/rust/project/lifecycle/src/policy.rs:519:13
  24: server::db::Db::background_worker::{{closure}}::{{closure}}
             at ./home/rust/project/server/src/db.rs:896:29
  25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/future/mod.rs:80:19
  26: <tokio::future::maybe_done::MaybeDone<Fut> as core::future::future::Future>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/future/maybe_done.rs:68:48
  27: server::db::Db::background_worker::{{closure}}::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/macros/join.rs:86:20
  28: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/future/poll_fn.rs:38:9
  29: server::db::Db::background_worker::{{closure}}
             at ./home/rust/project/server/src/db.rs:887:9
  30: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/future/mod.rs:80:19
  31: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.26/src/instrument.rs:151:9
  32: server::config::DatabaseHandle::advance_init::{{closure}}
             at ./home/rust/project/server/src/config.rs:649:21
  33: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/future/mod.rs:80:19
  34: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/task/core.rs:147:17
  35: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/loom/std/unsafe_cell.rs:14:9
  36: tokio::runtime::task::core::CoreStage<T>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/task/core.rs:137:13
  37: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/task/harness.rs:437:23
  38: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:344:9
  39: std::panicking::try::do_call
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:379:40
  40: std::panicking::try
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:343:19
  41: std::panic::catch_unwind
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:431:14
  42: tokio::runtime::task::harness::poll_future
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/task/harness.rs:424:19
  43: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/task/harness.rs:89:9
  44: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/task/harness.rs:59:15
  45: tokio::runtime::task::raw::RawTask::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/task/raw.rs:70:18
  46: tokio::runtime::task::Notified<S>::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/task/mod.rs:166:9
  47: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/thread_pool/worker.rs:396:13
  48: tokio::coop::with_budget::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/coop.rs:106:9
  49: std::thread::local::LocalKey<T>::try_with
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/thread/local.rs:376:16
  50: std::thread::local::LocalKey<T>::with
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/thread/local.rs:352:9
  51: tokio::coop::with_budget
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/coop.rs:99:5
  52: tokio::coop::budget
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/coop.rs:76:5
  53: tokio::runtime::thread_pool::worker::Context::run_task
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/thread_pool/worker.rs:395:9
  54: tokio::runtime::thread_pool::worker::Context::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/thread_pool/worker.rs:365:24
  55: tokio::runtime::thread_pool::worker::run::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/thread_pool/worker.rs:350:17
  56: tokio::macros::scoped_tls::ScopedKey<T>::set
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/macros/scoped_tls.rs:61:9
  57: tokio::runtime::thread_pool::worker::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/thread_pool/worker.rs:347:5
  58: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/thread_pool/worker.rs:326:45
  59: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/blocking/task.rs:42:21
  60: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/task/core.rs:147:17
  61: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/loom/std/unsafe_cell.rs:14:9
  62: tokio::runtime::task::core::CoreStage<T>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/task/core.rs:137:13
  63: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/task/harness.rs:437:23
  64: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:344:9
  65: std::panicking::try::do_call
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:379:40
  66: std::panicking::try
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:343:19
  67: std::panic::catch_unwind
             at ./rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:431:14
  68: tokio::runtime::task::harness::poll_future
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/task/harness.rs:424:19
  69: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/task/harness.rs:89:9
  70: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/task/harness.rs:59:15
  71: tokio::runtime::task::raw::RawTask::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/task/raw.rs:70:18
  72: tokio::runtime::task::Notified<S>::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/task/mod.rs:166:9
  73: tokio::runtime::blocking::pool::Inner::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/blocking/pool.rs:265:17
  74: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/blocking/pool.rs:245:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by alamb** [comment]
This is a new assert. In order to unblock tools, I plan to make the assert into a warning while fixing the root cause.

**Comment by alamb** [comment]
This is definitely still happening

from greylog: https://logs.aws.influxdata.io/search?q=kubernetes_container_name%3Aiox+AND+kubernetes_labels_component%3Aiox%5C-query%5C-3000+AND+%22Mismatch+in+statistics+count%22&rangetype=relative&relative=300

```


timestamp | source
-- | --
2021-08-09 19:10:18 +00:00 | ip-10-140-11-50.ec2.internal
level=warn msg="Mismatch in statistics count, see #2124" table_name=http_api_request_duration_seconds column_name=os_version column_count=74526 previous_count=100006 target="data_types::partition_metadata" location="data_types/src/partition_metadata.rs:112" time=1628535860764882032
2021-08-09 19:10:18 +00:00 | ip-10-140-11-50.ec2.internal
level=warn msg="Mismatch in statistics count, see #2124" table_name=http_api_request_duration_seconds column_name=role column_count=100000 previous_count=100006 target="data_types::partition_metadata" location="data_types/src/partition_metadata.rs:112" time=1628535860764886267
2021-08-09 19:10:18 +00:00 | ip-10-140-11-50.ec2.internal
level=warn msg="Mismatch in statistics count, see #2124" table_name=http_api_requests_total column_name=os_version column_count=74713 previous_count=100141 target="data_types::partition_metadata" location="data_types/src/partition_metadata.rs:112" time=1628535860765085844
2021-08-09 19:10:18 +00:00 | ip-10-140-11-50.ec2.internal
level=warn msg="Mismatch in statistics count, see #2124" table_name=http_api_requests_total column_name=role column_count=100135 previous_count=100141 target="data_types::partition_metadata" location="data_types/src/partition_metadata.rs:112" time=1628535860765090160
2021-08-09 19:10:18 +00:00 | ip-10-140-11-50.ec2.internal
level=warn msg="Mismatch in statistics count, see #2124" table_name=http_api_request_duration_seconds column_name=os column_count=74526 previous_count=100006 target="data_types::partition_metadata" location="data_types/src/partition_metadata.rs:112" time=1628535860764877203


```

**Comment by alamb** [comment]
I have found at least one bug in the calculation of statistics in the MUB (when inserting batches that do not have all columns sometimes the statistics are not updated correctly).
