### ISSUE TITLE
panic: unsupported type of stats in read buffer 

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#2158]
Internally in our cluster we have seen the following panic

```
level=error msg="thread 'tokio-runtime-worker' panicked at 'UNKNOWN', read_buffer/src/table.rs:744:26" target="panic_logging" location="panic_logging/src/lib.rs:110" time=1627527025281603101
```

Which corresponds to the following code in the read buffer. 
```
                    _ => panic!(
                        "unsupported type of stats in read buffer: {:?}",
                        column_meta.range
                    ),
```

Since this 

__Steps to reproduce:__
Not sure

__Expected behaviour:__
No panic

__Actual behaviour:__
panic

__Environment info:__
internal tools cluster

**Comment by alamb** [comment]
I believe the issue is thatthe code that creates TableSummaries does not work for columns with only null values in it. I can reproduce a panic in the same line with a test like this (adding column entirely of null values):

```diff
diff --git a/read_buffer/src/chunk.rs b/read_buffer/src/chunk.rs
index c5c2274c..45a00c5f 100644
--- a/read_buffer/src/chunk.rs
+++ b/read_buffer/src/chunk.rs
@@ -832,6 +832,7 @@ mod test {
     fn table_summaries() {
         let schema = SchemaBuilder::new()
             .non_null_tag("env")
+            .tag("host")
             .non_null_field("temp", Float64)
             .non_null_field("counter", UInt64)
             .non_null_field("icounter", Int64)
@@ -847,6 +848,11 @@ mod test {
                     .into_iter()
                     .collect::<DictionaryArray<Int32Type>>(),
             ),
+            Arc::new(
+                (vec![None, None, None] as Vec<Option<&str>>)
+                    .into_iter()
+                    .collect::<DictionaryArray<Int32Type>>(),
+            ),
             Arc::new(Float64Array::from(vec![10.0, 30000.0, 4500.0])),
             Arc::new(UInt64Array::from(vec![1000, 3000, 5000])),
             Arc::new(Int64Array::from(vec![1000, -1000, 4000])),
```

Produces

```
---- chunk::test::table_summaries stdout ----
thread 'chunk::test::table_summaries' panicked at 'unsupported type of stats in read buffer: (Null, Null)', read_buffer/src/table.rs:744:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
