### ISSUE TITLE
Panic in `CatalogChunk::new_rub_chunk`:  'inconsistent min/max expected String got NULL', read_buffer/src/table.rs:709:25

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#2217]
This is the same reproducer as described by @e-dard  on https://github.com/influxdata/influxdb_iox/issues/2112 but seems to be a differnet underlying cause, so opening a new ticket: 

The following Flux is causing IOx to error in our internal deployment:

```
from(bucket: "apps")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "http_query_response_bytes")
  |> aggregateWindow(every: v.windowPeriod, fn: count, createEmpty: false)
```

This results in the `read_window_aggregate` physical operation being issues, which then needs a `Grouped SeriesSet` plan to execute in order to get the data in the correct series-key based format.

The query never works and Flux displays `An internal error has occurred`.
I can see the following in the IOx logs:

```
level=error msg="thread 'tokio-runtime-worker' panicked at 'UNKNOWN', read_buffer/src/table.rs:709:25" target="panic_logging" location="
panic_logging/src/lib.rs:110" time=1628596458858162477
thread 'tokio-runtime-worker' panicked at 'inconsistent min/max expected String got NULL', read_buffer/src/table.rs:709:25
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
   1: std::panicking::begin_panic_fmt
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:457:5
   2: read_buffer::table::MetaData::to_summary::{{closure}}
   3: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:280:13
   4: core::option::Option<T>::map
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/option.rs:489:29
   5: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/adapters/map.rs:101:9
   6: alloc::vec::Vec<T,A>::extend_desugared
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/vec/mod.rs:2546:35
   7: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/vec/spec_extend.rs:18:9
   8: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/vec/spec_from_iter_nested.rs:37:9
   9: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/vec/spec_from_iter.rs:33:9
  10: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/vec/mod.rs:2449:9
  11: core::iter::traits::iterator::Iterator::collect
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/traits/iterator.rs:1748:9
  12: read_buffer::table::MetaData::to_summary
             at ./home/rust/project/read_buffer/src/table.rs:690:23
  13: read_buffer::table::Table::table_summary
             at ./home/rust/project/read_buffer/src/table.rs:193:9
  14: read_buffer::chunk::Chunk::table_summary
             at ./home/rust/project/read_buffer/src/chunk.rs:198:9
  15: server::db::catalog::chunk::CatalogChunk::new_rub_chunk
             at ./home/rust/project/server/src/db/catalog/chunk.rs:306:41
  16: server::db::catalog::partition::Partition::create_rub_chunk
             at ./home/rust/project/server/src/db/catalog/partition.rs:170:58
  17: server::db::lifecycle::compact::compact_chunks::{{closure}}
             at ./home/rust/project/server/src/db/lifecycle/compact.rs:103:13
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/future/mod.rs:80:19
  19: <F as futures_core::future::TryFuture>::try_poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.16/src/future.rs:82:9
  20: <tracker::task::future::TrackedFuture<F> as core::future::future::Future>::poll
             at ./home/rust/project/tracker/src/task/future.rs:73:20
```
The logs I captured are here:
[query-3000-log.txt](https://github.com/influxdata/influxdb_iox/files/6946378/query-3000-log.txt)

**Comment by alamb** [comment]
Starting to check this one out

**Comment by alamb** [comment]
I am not sure this really has anything to do with the query -- it may just be happening and I happened to see it.

One thing that is styming  me is that I can not seem to figure out what the actual panic message was -- I get the stack trace but not what the panic message is. 

I am continuing to investigate / poke at kubernetes, etc to see if I can uncover what is going on

**Comment by alamb** [comment]
Filed https://github.com/influxdata/influxdb_iox/issues/2240 to track the lack of panic messages in the log

**Comment by alamb** [comment]
This appears to be code I changed in https://github.com/influxdata/influxdb_iox/pull/2159 but clearly didn't get all the cases

**Comment by alamb** [comment]
https://github.com/influxdata/influxdb_iox/blob/main/read_buffer/src/table.rs#L708

The code in question has basically discovered that the statistics for a RowGroup somehow have a non-null String for the min, and a null for a max. 

The proper behavior in this case should be for the same string value to be both min and max. Looking into how this could happen

**Comment by alamb** [comment]
I have a reproducer now. Fixing.

**Comment by tustvold** [comment]
I believe this was closed by https://github.com/influxdata/influxdb_iox/pull/2246
