### ISSUE TITLE
Inconsistent statistics (try 3) in IOx

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#2289]
Next phase of https://github.com/influxdata/influxdb_iox/issues/2124

I added what has turned out to be a very good bug finding aid (as well as a great way to brick IOx in dev) that asserts that the row count statistics are consistent for all columns. We had temporarily turned in into a warning, and I thought I had fixed https://github.com/influxdata/influxdb_iox/issues/2124 so re-enabled the assert.

Turns out that it was not fixed and asserted again. @NGA-TRAN  has turned off the assert again in https://github.com/influxdata/influxdb_iox/pull/2250 and this ticket tracks the work to fix it

In the long running saga

__Expected behaviour:__
Counts for all columns in a chunk should be consistent

__Actual behaviour:__
Sometimes the counts are mismatched

__Logs:__

```
thread 'IOx Query Executor Thread' panicked at 'assertion failed: `(left == right)`
  left: `3161247`,
 right: `3170727`: Mismatch counts in table http_query_response_bytes column org_id, expected 3170727 got 3161247', data_types/src/partition_metadata.rs:109:13
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:117:5
   4: data_types::partition_metadata::TableSummary::total_count
             at ./home/rust/project/data_types/src/partition_metadata.rs:109:13
   5: <server::db::access::ChunkAccess as query::pruning::PruningObserver>::was_pruned
             at ./home/rust/project/server/src/db/access.rs:164:24
   6: query::pruning::must_keep
             at ./home/rust/project/query/src/pruning.rs:98:17
   7: query::pruning::prune_chunks::{{closure}}
             at ./home/rust/project/query/src/pruning.rs:56:21
   8: core::iter::adapters::filter::filter_try_fold::{{closure}}
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/adapters/filter.rs:44:25
   9: core::iter::traits::iterator::Iterator::try_fold
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/traits/iterator.rs:1972:21
  10: <core::iter::adapters::filter::Filter<I,P> as core::iter::traits::iterator::Iterator>::try_fold
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/adapters/filter.rs:93:9
  11: <I as alloc::vec::source_iter_marker::SpecInPlaceCollect<T,I>>::collect_in_place
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/vec/source_iter_marker.rs:117:13
  12: alloc::vec::source_iter_marker::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/vec/source_iter_marker.rs:55:19
  13: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/vec/mod.rs:2449:9
  14: core::iter::traits::iterator::Iterator::collect
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/traits/iterator.rs:1748:9
  15: query::pruning::prune_chunks
             at ./home/rust/project/query/src/pruning.rs:54:36
  16: <server::db::access::ChunkAccess as query::provider::ChunkPruner<server::db::chunk::DbChunk>>::prune_chunks
             at ./home/rust/project/server/src/db/access.rs:155:9
  17: server::db::access::ChunkAccess::candidate_chunks
             at ./home/rust/project/server/src/db/access.rs:145:9
  18: <server::db::access::QueryCatalogAccess as query::QueryDatabase>::chunks
             at ./home/rust/project/server/src/db/access.rs:189:9
  19: <server::db::Db as query::QueryDatabase>::chunks
             at ./home/rust/project/server/src/db.rs:1352:9
  20: query::frontend::influxrpc::InfluxRpcPlanner::read_window_aggregate
             at ./home/rust/project/query/src/frontend/influxrpc.rs:631:22
  21: influxdb_iox::influxdb_ioxd::planner::Planner::read_window_aggregate::{{closure}}::{{closure}}
             at ./home/rust/project/src/influxdb_ioxd/planner.rs:244:21
  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/future/mod.rs:80:19
  23: query::exec::task::DedicatedExecutor::spawn::{{closure}}
             at ./home/rust/project/query/src/exec/task.rs:124:31
  24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/future/mod.rs:80:19
  25: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/future/future.rs:119:9
  26: query::exec::task::DedicatedExecutor::new::{{closure}}::{{closure}}::{{closure}}
             at ./home/rust/project/query/src/exec/task.rs:89:29
  27: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
```

**Comment by alamb** [comment]
I looked at the IOx logs this morning and did not find any warning messages:

https://logs.aws.influxdata.io/search?q=kubernetes_container_name%3Aiox+AND+%22mismatch%22&rangetype=relative&relative=432000

![Screen Shot 2021-11-13 at 7 04 37 AM](https://user-images.githubusercontent.com/490673/141643112-9abb821e-b2c9-422d-a550-82a0481bc7a6.png)

Thus I think we can close this one
