### ISSUE TITLE
panic on "select count(*) from system.columns"

### ISSUE THREAD

**Issue by mkmik** [influxdata/influxdb_iox#2381]
(on query-3000 on our internal staging env)

```
; ./target/debug/influxdb_iox database query 844910ece80be8bc_3c0bd4c89186ca89 'select count(*) from system.columns;'
Error querying: status: InvalidArgument, message: "Error while planning query: Internal executor error while planning query: Error joining execution task: channel closed", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Mon, 23 Aug 2021 15:02:14 GMT"} }
```

**Comment by mkmik** [comment]
```
hread 'IOx Query Executor Thread' panicked at 'must contain at least one element', /home/rust/project/data_types/src/partition_metadata.rs:73:33
level=error msg="thread 'IOx Query Executor Thread' panicked at 'UNKNOWN', /home/rust/project/data_types/src/partition_metadata.rs:73:33" target="panic_logging" location="panic_logging/src/lib.rs:110" time=1629731020865554395
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/option.rs:1243:5
   3: core::option::Option<T>::expect
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/option.rs:351:21
   4: <data_types::partition_metadata::TableSummary as core::iter::traits::collect::FromIterator<data_types::partition_metadata::TableSummary>>::from_iter
             at ./home/rust/project/data_types/src/partition_metadata.rs:73:21
   5: data_types::partition_metadata::PartitionSummary::from_table_summaries
             at ./home/rust/project/data_types/src/partition_metadata.rs:58:20
   6: server::db::catalog::partition::Partition::summary
             at ./home/rust/project/server/src/db/catalog/partition.rs:282:9
   7: server::db::catalog::table::Table::partition_summaries::{{closure}}
             at ./home/rust/project/server/src/db/catalog/table.rs:99:42
   8: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:280:13
   9: core::option::Option<T>::map
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/option.rs:489:29
  10: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/adapters/map.rs:101:9
  11: <core::iter::adapters::flatten::FlattenCompat<I,U> as core::iter::traits::iterator::Iterator>::next
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/adapters/flatten.rs:262:23
  12: <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/adapters/flatten.rs:51:9
  13: alloc::vec::Vec<T,A>::extend_desugared
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/vec/mod.rs:2546:35
  14: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/vec/spec_extend.rs:18:9
  15: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/vec/spec_from_iter_nested.rs:37:9
  16: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/vec/spec_from_iter.rs:33:9
  17: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/vec/mod.rs:2449:9
  18: core::iter::traits::iterator::Iterator::collect
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/traits/iterator.rs:1748:9
  19: server::db::catalog::Catalog::partition_summaries
             at ./home/rust/project/server/src/db/catalog.rs:222:9
  20: <server::db::system_tables::columns::ColumnsTable as server::db::system_tables::IoxSystemTable>::batch
             at ./home/rust/project/server/src/db/system_tables/columns.rs:36:49
  21: <server::db::system_tables::SystemTableProvider<T> as datafusion::datasource::datasource::TableProvider>::scan
             at ./home/rust/project/server/src/db/system_tables.rs:147:20
  22: datafusion::physical_plan::planner::DefaultPhysicalPlanner::create_initial_plan
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/fa3f099/datafusion/src/physical_plan/planner.rs:310:17
  23: datafusion::physical_plan::planner::DefaultPhysicalPlanner::create_initial_plan
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/fa3f099/datafusion/src/physical_plan/planner.rs:429:34
  24: datafusion::physical_plan::planner::DefaultPhysicalPlanner::create_initial_plan
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/fa3f099/datafusion/src/physical_plan/planner.rs:516:34
  25: <datafusion::physical_plan::planner::DefaultPhysicalPlanner as datafusion::physical_plan::planner::PhysicalPlanner>::create_physical_plan
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/fa3f099/datafusion/src/physical_plan/planner.rs:248:28
  26: <query::exec::context::IOxQueryPlanner as datafusion::execution::context::QueryPlanner>::create_physical_plan
             at ./home/rust/project/query/src/exec/context.rs:55:9
  27: datafusion::execution::context::ExecutionContext::create_physical_plan
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/fa3f099/datafusion/src/execution/context.rs:485:9
  28: query::exec::context::IOxExecutionContext::prepare_plan
             at ./home/rust/project/query/src/exec/context.rs:213:29
  29: query::exec::context::IOxExecutionContext::prepare_sql
             at ./home/rust/project/query/src/exec/context.rs:203:9
  30: query::frontend::sql::SqlQueryPlanner::query
             at ./home/rust/project/query/src/frontend/sql.rs:91:9
  31: influxdb_iox::influxdb_ioxd::planner::Planner::sql::{{closure}}::{{closure}}
             at ./home/rust/project/src/influxdb_ioxd/planner.rs:66:21
  32: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/future/mod.rs:80:19
  33: query::exec::task::DedicatedExecutor::spawn::{{closure}}
             at ./home/rust/project/query/src/exec/task.rs:124:31
  34: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/future/mod.rs:80:19
  35: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/future/future.rs:119:9
  36: query::exec::task::DedicatedExecutor::new::{{closure}}::{{closure}}::{{closure}}
             at ./home/rust/project/query/src/exec/task.rs:89:29
  37: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/future/mod.rs:80:19
  38: <F as futures_core::future::TryFuture>::try_poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.16/src/future.rs:82:9
  39: <tracker::task::future::TrackedFuture<F> as core::future::future::Future>::poll
             at ./home/rust/project/tracker/src/task/future.rs:73:20
  40: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.0/src/runtime/task/core.rs:161:17
  41: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.0/src/loom/std/unsafe_cell.rs:14:9
  42: tokio::runtime::task::core::CoreStage<T>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.0/src/runtime/task/core.rs:151:13
  43: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.0/src/runtime/task/harness.rs:461:19
  44: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:347:9
  45: std::panicking::try::do_call
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401:40
  46: std::panicking::try
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365:19
  47: std::panic::catch_unwind
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434:14
  48: tokio::runtime::task::harness::poll_future
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.0/src/runtime/task/harness.rs:449:18
  49: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.0/src/runtime/task/harness.rs:98:27
  50: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.0/src/runtime/task/harness.rs:53:15
  51: tokio::runtime::task::raw::RawTask::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.0/src/runtime/task/raw.rs:70:18
  52: tokio::runtime::task::LocalNotified<S>::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.0/src/runtime/task/mod.rs:343:9
  53: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.0/src/runtime/thread_pool/worker.rs:398:13
  54: tokio::coop::with_budget::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.0/src/coop.rs:106:9
  55: std::thread::local::LocalKey<T>::try_with
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/local.rs:400:16
  56: std::thread::local::LocalKey<T>::with
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/local.rs:376:9
  57: tokio::coop::with_budget
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.0/src/coop.rs:99:5
  58: tokio::coop::budget
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.0/src/coop.rs:76:5
  59: tokio::runtime::thread_pool::worker::Context::run_task
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.0/src/runtime/thread_pool/worker.rs:397:9
  60: tokio::runtime::thread_pool::worker::Context::run
  61: tokio::runtime::thread_pool::worker::run::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.0/src/runtime/thread_pool/worker.rs:350:17
  62: tokio::macros::scoped_tls::ScopedKey<T>::set
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.0/src/macros/scoped_tls.rs:61:9
  63: tokio::runtime::thread_pool::worker::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.0/src/runtime/thread_pool/worker.rs:347:5
  64: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.0/src/runtime/thread_pool/worker.rs:326:45
  65: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.0/src/runtime/blocking/task.rs:42:21
  66: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.0/src/runtime/task/core.rs:161:17
  67: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.0/src/loom/std/unsafe_cell.rs:14:9
  68: tokio::runtime::task::core::CoreStage<T>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.0/src/runtime/task/core.rs:151:13
  69: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.0/src/runtime/task/harness.rs:461:19
  70: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:347:9
  71: std::panicking::try::do_call
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401:40
  72: std::panicking::try
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365:19
  73: std::panic::catch_unwind
             at ./rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434:14
  74: tokio::runtime::task::harness::poll_future
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.0/src/runtime/task/harness.rs:449:18
  75: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.0/src/runtime/task/harness.rs:98:27
  76: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.0/src/runtime/task/harness.rs:53:15
  77: tokio::runtime::task::raw::RawTask::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.0/src/runtime/task/raw.rs:70:18
  78: tokio::runtime::task::UnownedTask<S>::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.0/src/runtime/task/mod.rs:373:9
  79: tokio::runtime::blocking::pool::Inner::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.0/src/runtime/blocking/pool.rs:265:17
  80: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.0/src/runtime/blocking/pool.rs:245:17
```

**Comment by alamb** [comment]
Will fix

**Comment by alamb** [comment]
Looks to me like the partition has no chunks (which I know can happen after a `drop_partition` call). Working on a reproducer

**Comment by alamb** [comment]
Here is a test that fails with the same error

```diff
diff --git a/server/src/db.rs b/server/src/db.rs
index 68ded4cf..bfb9df9d 100644
--- a/server/src/db.rs
+++ b/server/src/db.rs
@@ -4312,6 +4312,51 @@ mod tests {
         assert_eq!(db.partition_chunk_summaries(partition_key), vec![]);
     }
 
+    #[tokio::test]
+    async fn query_after_drop_partition_on_persisted_db() {
+        let test_db = TestDb::builder()
+            .lifecycle_rules(LifecycleRules {
+                late_arrive_window_seconds: NonZeroU32::try_from(1).unwrap(),
+                mub_row_threshold: NonZeroUsize::try_from(1).unwrap(),
+                persist: true,
+                ..Default::default()
+            })
+            .build()
+            .await;
+        let db = Arc::new(test_db.db);
+
+        write_lp(db.as_ref(), "cpu bar=1 10").await;
+        write_lp(db.as_ref(), "cpu bar=2 20").await;
+
+        let partition_key = "1970-01-01T00";
+        db.persist_partition(
+            "cpu",
+            partition_key,
+            Instant::now() + Duration::from_secs(1),
+        )
+        .await
+        .unwrap();
+
+        // query data before drop
+        let expected = vec![
+            "+-----------------+",
+            "| COUNT(UInt8(1)) |",
+            "+-----------------+",
+            "| 2               |",
+            "+-----------------+",
+        ];
+        let batches = run_query(Arc::clone(&db), "select count(*) from system.columns").await;
+        assert_batches_sorted_eq!(&expected, &batches);
+
+        // Drop the partition (avoid data)
+        db.drop_partition("cpu", partition_key).await.unwrap();
+
+        // query data after drop -- should have no rows
+        let expected = vec![""];
+        let batches = run_query(Arc::clone(&db), "select count(*) from system.columns").await;
+        assert_batches_sorted_eq!(&expected, &batches);
+    }
+
     async fn create_parquet_chunk(db: &Arc<Db>) -> (String, String, u32) {
         write_lp(db, "cpu bar=1 10").await;
         let partition_key = "1970-01-01T00";
```
