### ISSUE TITLE
`assertion failed: i < self.len() in PrimitiveArray<T>::value` during merge inside DataFusion

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#3530]
__Steps to reproduce:__

Update datafusion to the latest (e.g. https://github.com/influxdata/influxdb_iox/pull/3517)

__Expected behaviour:__
test pass without panic

__Actual behaviour:__
panic inside datafusion:

```
---- influxrpc::field_columns::test_field_columns_empty_database stdout ----
thread 'influxrpc::field_columns::test_field_columns_empty_database' panicked at 'assertion failed: i < self.len()', /home/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-7.0.0/src/array/array_primitive.rs:120:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::panicking::panic
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:48:5
   3: arrow::array::array_primitive::PrimitiveArray<T>::value
             at /home/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-7.0.0/src/array/array_primitive.rs:120:9
   4: arrow::array::ord::compare_dict_string::{{closure}}
             at /home/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-7.0.0/src/array/ord.rs:96:24
   5: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/alloc/src/boxed.rs:1708:9
   6: datafusion::physical_plan::sorts::SortKeyCursor::compare
             at /home/alamb/.cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/992624a/datafusion/src/physical_plan/sorts/mod.rs:155:39
   7: <datafusion::physical_plan::sorts::SortKeyCursor as core::cmp::PartialOrd>::partial_cmp
             at /home/alamb/.cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/992624a/datafusion/src/physical_plan/sorts/mod.rs:210:9
   8: core::cmp::PartialOrd::le
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/cmp.rs:1058:19
   9: core::cmp::impls::<impl core::cmp::PartialOrd<&B> for &A>::le
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/cmp.rs:1432:13
  10: alloc::collections::binary_heap::BinaryHeap<T>::sift_up
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/alloc/src/collections/binary_heap.rs:561:16
  11: alloc::collections::binary_heap::BinaryHeap<T>::push
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/alloc/src/collections/binary_heap.rs:495:18
  12: datafusion::physical_plan::sorts::sort_preserving_merge::SortPreservingMergeStream::maybe_poll_stream
             at /home/alamb/.cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/992624a/datafusion/src/physical_plan/sorts/sort_preserving_merge.rs:440:17
  13: datafusion::physical_plan::sorts::sort_preserving_merge::SortPreservingMergeStream::poll_next_inner
             at /home/alamb/.cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/992624a/datafusion/src/physical_plan/sorts/sort_preserving_merge.rs:563:35
  14: <datafusion::physical_plan::sorts::sort_preserving_merge::SortPreservingMergeStream as futures_core::stream::Stream>::poll_next
             at /home/alamb/.cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/992624a/datafusion/src/physical_plan/sorts/sort_preserving_merge.rs:545:20
  15: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.19/src/stream.rs:120:9
  16: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /home/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.19/src/stream/stream/mod.rs:1510:9
  17: <query::exec::query_tracing::TracedStream as futures_core::stream::Stream>::poll_next
             at /data/influxdb_iox/query/src/exec/query_tracing.rs:53:9
  18: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.19/src/stream.rs:120:9
  19: <S as futures_core::stream::TryStream>::try_poll_next
             at /home/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.19/src/stream.rs:196:9
  20: <futures_util::stream::try_stream::try_filter::TryFilter<St,Fut,F> as futures_core::stream::Stream>::poll_next
             at /home/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.19/src/stream/try_stream/try_filter.rs:83:47
  21: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /home/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.19/src/stream/stream/mod.rs:1510:9
  22: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /home/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.19/src/stream/stream/next.rs:32:9
  23: db::lifecycle::collect_rub::{{closure}}
             at /data/influxdb_iox/db/src/lifecycle.rs:369:33
  24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/future/mod.rs:80:19
  25: db::lifecycle::compact::compact_chunks::{{closure}}
             at /data/influxdb_iox/db/src/lifecycle/compact.rs:107:30
  26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/future/mod.rs:80:19
  27: <F as futures_core::future::TryFuture>::try_poll
             at /home/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.19/src/future.rs:82:9
  28: <tracker::task::future::TrackedFuture<F> as core::future::future::Future>::poll
             at /data/influxdb_iox/tracker/src/task/future.rs:73:20
  29: db::Db::compact_chunks::{{closure}}
             at /data/influxdb_iox/db/src/lib.rs:677:9
  30: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/future/mod.rs:80:19
  31: db::Db::compact_partition::{{closure}}
             at /data/influxdb_iox/db/src/lib.rs:638:9
  32: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/future/mod.rs:80:19
  33: <query_tests::scenarios::NoData as query_tests::scenarios::DbSetup>::make::{{closure}}
             at ./src/scenarios.rs:126:24
  34: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/future/mod.rs:80:19
  35: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/future/future.rs:119:9
  36: query_tests::influxrpc::field_columns::run_field_columns_test_case::{{closure}}
             at ./src/influxrpc/field_columns.rs:25:21
  37: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/future/mod.rs:80:19
  38: query_tests::influxrpc::field_columns::test_field_columns_empty_database::{{closure}}
             at ./src/influxrpc/field_columns.rs:54:5
  39: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/future/mod.rs:80:19
  40: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/future/future.rs:119:9
  41: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}::{{closure}}
             at /home/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:240:62
  42: tokio::coop::with_budget::{{closure}}
             at /home/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/coop.rs:102:9
  43: std::thread::local::LocalKey<T>::try_with
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/thread/local.rs:399:16
  44: std::thread::local::LocalKey<T>::with
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/thread/local.rs:375:9
  45: tokio::coop::with_budget
             at /home/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/coop.rs:95:5
  46: tokio::coop::budget
             at /home/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/coop.rs:72:5
  47: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}
             at /home/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:240:39
  48: tokio::runtime::basic_scheduler::enter::{{closure}}
             at /home/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:349:29
  49: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/macros/scoped_tls.rs:61:9
  50: tokio::runtime::basic_scheduler::enter
             at /home/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:349:5
  51: tokio::runtime::basic_scheduler::Inner<P>::block_on
             at /home/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:230:9
  52: tokio::runtime::basic_scheduler::InnerGuard<P>::block_on
             at /home/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:501:9
  53: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /home/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:186:24
  54: tokio::runtime::Runtime::block_on
             at /home/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/mod.rs:461:46
  55: query_tests::influxrpc::field_columns::test_field_columns_empty_database
             at ./src/influxrpc/field_columns.rs:54:5
  56: query_tests::influxrpc::field_columns::test_field_columns_empty_database::{{closure}}
             at ./src/influxrpc/field_columns.rs:51:7
  57: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
  58: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by alamb** [comment]
I strongly suspect this is related to some code refactoring in https://github.com/apache/arrow-datafusion/pull/1596 that was unifying our sort implementations. Seeing if I can get a smaller reproducer

**Comment by alamb** [comment]
Upstream bug filed: https://github.com/apache/arrow-datafusion/issues/1676

**Comment by alamb** [comment]
No extra value is gained by this ticket, closing and will track with upstream
