### ISSUE TITLE
Panic Simplifying Invalid Predicate

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#3635]
Calling IOx with an invalid predicate, for example one that compares incompatible types, causes a panic.

```
2022-02-03T18:34:45.499339Z ERROR panic_logging: Thread panic panic_info=panicked at 'Expression simplificiation round 1 failed: Plan("'Utf8 = Int64' can't be evaluated because there isn't a common type to coerce the types to")', predicate/src/rpc_predicate.rs:185:22
thread 'IOx Query Executor Thread' panicked at 'Expression simplificiation round 1 failed: Plan("'Utf8 = Int64' can't be evaluated because there isn't a common type to coerce the types to")', predicate/src/rpc_predicate.rs:185:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This should instead return an error to the user

**Comment by alamb** [comment]
@tustvold  do you happen to remember how you found this panic? I am struggling to find a reproducer

**Comment by tustvold** [comment]
I believe one of the InfluxQL test cases ran into it

**Comment by alamb** [comment]
Thanks @tustvold  I'll try rerunning those

Note I created https://github.com/influxdata/influxdb_iox/pull/3763 to show my (failing) progress so far to create a reproducer

**Comment by alamb** [comment]
This will reproduce the issue: 

```
go test -v ./influxql/v1tests -run TestServer_Query_ShowTagValues
```

```
2022-02-16T14:25:53.854939Z DEBUG query::frontend::influxrpc: planning tag_values rpc_predicate=InfluxRpcPredicate { table_names: Some({"_"}), inner: Predicate { field_columns: None, partition_key: None, range: None, exprs: [CASE WHEN #value IS NULL THEN Utf8("") ELSE #value END = Int64(5000)], value_expr: [] } } tag_name="host"
2022-02-16T14:25:53.855226Z ERROR panic_logging: Thread panic panic_info=panicked at 'Expression simplificiation round 1 failed: Plan("'Utf8 = Int64' can't be evaluated because there is
n't a common type to coerce the types to")', predicate/src/rpc_predicate.rs:185:22
thread 'IOx Query Executor Thread' panicked at 'Expression simplificiation round 1 failed: Plan("'Utf8 = Int64' can't be evaluated because there isn't a common type to coerce the types
to")', predicate/src/rpc_predicate.rs:185:22
```

input data looks like:
```
	writes := []string{
		fmt.Sprintf(`cpu,host=server01 value=100 %d`, mustParseTime(time.RFC3339Nano, "2009-11-10T23:00:00Z").UnixNano()),
		fmt.Sprintf(`cpu,host=server01,region=uswest value=100 %d`, mustParseTime(time.RFC3339Nano, "2009-11-10T23:00:00Z").UnixNano()),
		fmt.Sprintf(`cpu,host=server01,region=useast value=100 %d`, mustParseTime(time.RFC3339Nano, "2009-11-10T23:00:00Z").UnixNano()),
		fmt.Sprintf(`cpu,host=server02,region=useast value=100 %d`, mustParseTime(time.RFC3339Nano, "2009-11-10T23:00:00Z").UnixNano()),
		fmt.Sprintf(`gpu,host=server02,region=useast value=100 %d`, mustParseTime(time.RFC3339Nano, "2009-11-10T23:00:00Z").UnixNano()),
		fmt.Sprintf(`gpu,host=server03,region=caeast value=100 %d`, mustParseTime(time.RFC3339Nano, "2009-11-10T23:00:00Z").UnixNano()),
		fmt.Sprintf(`disk,host=server03,region=caeast value=100 %d`, mustParseTime(time.RFC3339Nano, "2009-11-10T23:00:00Z").UnixNano()),
		fmt.Sprintf(`_,__name__=metric1 value=100 %d`, mustParseTime(time.RFC3339Nano, "2009-11-10T23:00:00Z").UnixNano()),

		fmt.Sprintf(`_,__name__=metric2 value=100 %d`, mustParseTime(time.RFC3339Nano, "2009-11-10T23:00:00Z").UnixNano()),
	}
```
