### ISSUE TITLE
Subsequently inserted string field values are lost

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#3935]
__Steps to reproduce:__

1. Download the `input.lp` from: [input.zip](https://github.com/influxdata/influxdb_iox/files/8186350/input.zip)

Then load the data and query it

```
influxdb_iox database create test_db
influxdb_iox database write test_db /tmp/input.lp
influxdb_iox database query test_db 'select * from m'
```

__Expected behaviour:__
The loaded data should be

```
+-----+----+----+----+-------+----------------------+
| f0  | f1 | f2 | f3 | f4    | time                 |
+-----+----+----+----+-------+----------------------+
| cat | 10 | 10 | 10 | true  | 2021-12-16T00:00:00Z |
| dog | 11 | 11 | 11 | false | 2021-12-16T00:01:00Z |
| cat | 12 | 12 | 12 | true  | 2021-12-16T00:02:00Z |
| emu | 13 | 13 | 13 | false | 2021-12-16T00:03:00Z |
| bird| 14 | 14 | 14 | true  | 2021-12-16T00:04:00Z |
+-----+----+----+----+-------+----------------------+
```

__Actual behaviour:__

lost all values other than `cat`:

```shell
(arrow_dev) alamb@MacBook-Pro-2:~/Software/idpe$ cat /tmp/input.lp
m f0="cat" 1639612800000000000
m f0="dog" 1639612860000000000
m f0="emu" 1639612920000000000
m f0="rat" 1639612980000000000
m f0="bird" 1639613040000000000
m f1=10i 1639612800000000000
m f1=11i 1639612860000000000
m f1=12i 1639612920000000000
m f1=13i 1639612980000000000
m f1=14i 1639613040000000000
m f2=10u 1639612800000000000
m f2=11u 1639612860000000000
m f2=12u 1639612920000000000
m f2=13u 1639612980000000000
m f2=14u 1639613040000000000
m f3=10 1639612800000000000
m f3=11 1639612860000000000
m f3=12 1639612920000000000
m f3=13 1639612980000000000
m f3=14 1639613040000000000
m f4=true 1639612800000000000
m f4=false 1639612860000000000
m f4=true 1639612920000000000
m f4=false 1639612980000000000
m f4=true 1639613040000000000
(arrow_dev) alamb@MacBook-Pro-2:~/Software/idpe$ ../influxdb_iox/target/debug/influxdb_iox database create test_db
Created database test_db
5fd0c65e-4541-4148-94bc-731672b3aa47
(arrow_dev) alamb@MacBook-Pro-2:~/Software/idpe$ ../influxdb_iox/target/debug/influxdb_iox database write test_db /tmp/input.lp
25 Lines OK
(arrow_dev) alamb@MacBook-Pro-2:~/Software/idpe$ ../influxdb_iox/target/debug/influxdb_iox database query test_db 'select * from m'
+-----+----+----+----+-------+----------------------+
| f0  | f1 | f2 | f3 | f4    | time                 |
+-----+----+----+----+-------+----------------------+
| cat | 10 | 10 | 10 | true  | 2021-12-16T00:00:00Z |
|     | 11 | 11 | 11 | false | 2021-12-16T00:01:00Z |
|     | 12 | 12 | 12 | true  | 2021-12-16T00:02:00Z |
|     | 13 | 13 | 13 | false | 2021-12-16T00:03:00Z |
|     | 14 | 14 | 14 | true  | 2021-12-16T00:04:00Z |
+-----+----+----+----+-------+----------------------+
(arrow_dev) alamb@MacBook-Pro-2:~/Software/idpe$
```

**Comment by alamb** [comment]
🤔 the data appears to be in the input string array (not sure if they are marked null or not)

```
2022-03-04T13:58:57.237023Z TRACE datafusion::physical_plan::planner: Detailed optimized physical plan:
ProjectionExec...
 columns: [StringArray
[
  "cat",
  "dog",
  "emu",
  "rat",
  "bird",
  "",
  "",
  "",
  "",
  "",
  ...5 elements...,

```

**Comment by alamb** [comment]
The plan in this case is as follows:

```text
ProjectionExec: expr=[f0@0 as f0, f1@1 as f1, f2@2 as f2, f3@3 as f3, f4@4 as f4, time@5 as time]
  UnionExec
    DeduplicateExec: [time@5 ASC]
      SortExec: [time@5 ASC]
        IOxReadFilterNode: table_name=m, chunks=1 predicate=Predicate
    IOxReadFilterNode: table_name=m, chunks=0 predicate=Predicate
```

I will file a ticket about the `IOxReaedFilterNode` with no chunks -- but I don't think that is related to the bug.



The input to the deduplicator does not look quite rigth:
```
AAL deduplicator input batch:
RecordBatch { ....
, columns: [StringArray
[
  "",
  "",
  "",
  "",
  "cat",
  "dog",
  "",
  "",
  "",
  "",
  ...5 elements...,
  "",
  "",
  "",
  "rat",
  "",
  "",
  "",
  "",
  "bird",
  "",
], PrimitiveArray<Int64>
```

The input to the SortExec seems ok:

```
AAL adapter input batch:
RecordBatch { .... }, columns: [StringArray
[
  "cat",
  "dog",
  "emu",
  "rat",
  "bird",
```

So next up will be to add some debugging to see if this is SortPreservingMerge / SortExec being screwy

**Comment by alamb** [comment]
I don't think this is a problem in DataFusion. I think it is something wrong with the deduplicator in IOx:

Given this input (two lp lines that have the same timestamp):: 

```shell
(arrow_dev) alamb@MacBook-Pro-2:~/Software/idpe$ cat /tmp/input2.lp 
m f0="cat" 1639612800000000000
m f1=10i 1639612800000000000
```

The `"cat"` is lost (🐱 lol)

```
(arrow_dev) alamb@MacBook-Pro-2:~/Software/idpe$ ../influxdb_iox/target/debug/influxdb_iox database write test_db /tmp/input2.lp
2 Lines OK
(arrow_dev) alamb@MacBook-Pro-2:~/Software/idpe$ ../influxdb_iox/target/debug/influxdb_iox database query test_db 'select * from m'
+----+----+----------------------+
| f0 | f1 | time                 |
+----+----+----------------------+
|    | 10 | 2021-12-16T00:00:00Z |
+----+----+----------------------+

```


However, when I test with non string columns:

```shell
(arrow_dev) alamb@MacBook-Pro-2:~/Software/idpe$ cat /tmp/input2.lp 
m f1=10i 1639612800000000000
m f2=10u 1639612800000000000
```

The correct results are produced (both fields are collapsed correctly):


```
(arrow_dev) alamb@MacBook-Pro-2:~/Software/idpe$ ../influxdb_iox/target/debug/influxdb_iox database write test_db /tmp/input2.lp
2 Lines OK
(arrow_dev) alamb@MacBook-Pro-2:~/Software/idpe$ ../influxdb_iox/target/debug/influxdb_iox database query test_db 'select * from m'
+----+----+----------------------+
| f1 | f2 | time                 |
+----+----+----------------------+
| 10 | 10 | 2021-12-16T00:00:00Z |
+----+----+----------------------+
```

**Comment by alamb** [comment]
Aha a break in the case! 🔎 

The input to the deduplicator is like this: 
```
Column 0: Utf8, 2 rows
 Row 0: cat, (null=false)
 Row 1: , (null=false)             <--- this row should be marked as NULL!
Column 1: Int64, 2 rows
 Row 0: , (null=true)
 Row 1: 10, (null=false)
Column 2: Timestamp(Nanosecond, None), 2 rows
 Row 0: 2021-12-16 00:00:00, (null=false)
 Row 1: 2021-12-16 00:00:00, (null=false)
```

**Comment by alamb** [comment]
Success!

This test fails (in `mutable_batch`):

```rust

    #[test]
    fn test_nulls() {
        let lp = r#"m f0="cat" 1639612800000000000
m f1=10i 1639612800000000000
        "#;

        let batches = lines_to_batches(lp, 5).unwrap();
        assert_eq!(batches.len(), 1);

        let batch = batches["m"].to_arrow(Selection::All).unwrap();
        assert_batches_eq!(
            &[
                "+-----+----+----------------------+",
                "| f0  | f1 | time                 |",
                "+-----+----+----------------------+",
                "| cat |    | 2021-12-16T00:00:00Z |",
                "|     | 10 | 2021-12-16T00:00:00Z |",
                "+-----+----+----------------------+",
            ],
            &[batch.clone()]
        );

        // Verify the nullness of the string column ("" not the same as null)
        let f0 = &batch.columns()[0];
        assert!(f0.is_valid(0));
        assert!(!f0.is_valid(1));

    }
}
```

```
---- tests::test_nulls stdout ----
thread 'tests::test_nulls' panicked at 'assertion failed: !f0.is_valid(1)', mutable_batch_lp/src/lib.rs:257:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::panicking::panic
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:48:5
   3: mutable_batch_lp::tests::test_nulls
             at ./src/lib.rs:257:9
   4: mutable_batch_lp::tests::test_nulls::{{closure}}
             at ./src/lib.rs:233:5
   5: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
