### ISSUE TITLE
Investigate shutdown behaviour of all-in-one mode after PR reverts

### ISSUE THREAD

**Issue by lukebond** [influxdata/influxdb_iox#4089]
I have created PRs to revert #4043 and #4044 which touched on propagating shutdown info. Perhaps those changes alone weren't enough to fix what @domodwyer was fixing, so I'm creating this issue to track it so he can pick it up when he gets back later this week.

**Comment by domodwyer** [comment]
I've not been able to reproduce this! 🤦 

I've used the handy e2e @alamb added in #4114 which I assume should catch this problem, and I also confirmed manually by running the following before/after picking both 22eab934c and 5c16f28a1 onto `origin/main`:

```console
$ cargo run -- run all-in-one --write-buffer-partition-range-start 0 --write-buffer-partition-range-end 0 --pause-ingest-size-bytes 1000000000 --persist-memory-threshold-bytes 1000000000000 --write-buffer file
```

What I did:

```console
$ git b test origin/main
Switched to a new branch 'test'
Outstanding TODOs for the current branch.................................Passed
$ cargo test all_in_one
   Compiling termtree v0.2.4
   Compiling wait-timeout v0.2.0
   Compiling test_helpers v0.1.0 (/Users/dom/Documents/rust/influxdb_iox/test_helpers)
   Compiling iox_tests v0.1.0 (/Users/dom/Documents/rust/influxdb_iox/iox_tests)
   Compiling influxdb_ioxd v0.1.0 (/Users/dom/Documents/rust/influxdb_iox/influxdb_ioxd)
   Compiling predicates-tree v1.0.5
   Compiling assert_cmd v2.0.4
   Compiling test_helpers_end_to_end_ng v0.1.0 (/Users/dom/Documents/rust/influxdb_iox/test_helpers_end_to_end_ng)
   Compiling influxdb_iox v0.1.0 (/Users/dom/Documents/rust/influxdb_iox/influxdb_iox)
    Finished test [unoptimized + debuginfo] target(s) in 27.31s
     Running unittests (target/debug/deps/influxdb_iox-23694d2be2884e65)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 12 filtered out; finished in 0.00s

     Running tests/end_to_end.rs (target/debug/deps/end_to_end-7fe773fd020af299)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 153 filtered out; finished in 0.00s

     Running tests/end_to_end_ng.rs (target/debug/deps/end_to_end_ng-23a7f81df3f9d301)

running 1 test
test end_to_end_ng_cases::all_in_one::smoke ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s

$ git pk 22eab934c
[test2 b583933da] fix: propagate shutdown into QuerierHandlerImpl
 Date: Tue Mar 15 17:10:41 2022 +0000
 1 file changed, 2 insertions(+), 5 deletions(-)
$ git pk 5c16f28a1
Auto-merging influxdb_ioxd/src/server_type/compactor.rs
[test2 10a096290] fix: propagate shutdown into CompactorHandler
 Date: Tue Mar 15 17:19:23 2022 +0000
 1 file changed, 2 insertions(+), 5 deletions(-)
$ cargo test all_in_one
   Compiling influxdb_ioxd v0.1.0 (/Users/dom/Documents/rust/influxdb_iox/influxdb_ioxd)
   Compiling influxdb_iox v0.1.0 (/Users/dom/Documents/rust/influxdb_iox/influxdb_iox)
    Finished test [unoptimized + debuginfo] target(s) in 27.37s
     Running unittests (target/debug/deps/influxdb_iox-23694d2be2884e65)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 12 filtered out; finished in 0.00s

     Running tests/end_to_end.rs (target/debug/deps/end_to_end-7fe773fd020af299)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 153 filtered out; finished in 0.00s

     Running tests/end_to_end_ng.rs (target/debug/deps/end_to_end_ng-23a7f81df3f9d301)

running 1 test
test end_to_end_ng_cases::all_in_one::smoke ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s
```

Are you aware of us merging anything since the original commits that might have fixed the underlying problem in the querier/compactor? What is your all-in-one command you're using - perhaps it's triggered by specific invocations somehow 🤷

**Comment by domodwyer** [comment]
I also can't reproduce it on the merge commit for #4044 either!

```console
$ git co 943cc3731
Note: switching to '943cc3731'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 943cc3731 Merge pull request #4044 from influxdata/dom/compactor-shutdown
Outstanding TODOs for the current branch.................................Passed
$ git last
commit 943cc3731c0b9bb41753fd9878a842f093534726 (HEAD)
Merge: b48f8ca6f 026b415ee
Author: kodiakhq[bot] <49736102+kodiakhq[bot]@users.noreply.github.com>
Date:   Tue Mar 15 17:40:00 2022 +0000

    Merge pull request #4044 from influxdata/dom/compactor-shutdown

    fix: propagate shutdown into CompactorHandler

$ cr -- run all-in-one --write-buffer-partition-range-start 0 --write-buffer-partition-range-end 0 --pause-ingest-size-bytes 1000000000 --persist-memory-threshold-bytes 1000000000000 --write-buffer file
    Finished dev [unoptimized + debuginfo] target(s) in 0.28s
     Running `target/debug/influxdb_iox run all-in-one --write-buffer-partition-range-start 0 --write-buffer-partition-range-end 0 --pause-ingest-size-bytes 1000000000 --persist-memory-threshold-bytes 1000000000000 --write-buffer file`

```

So perhaps it is something specific to the command line used? Or perhaps OS? I'm at a loss really.

**Comment by alamb** [comment]
Or maybe we fixed something else 🤔 

How about we make a new PR that restores the old code and @lukebond  and I can test it out locally?

**Comment by domodwyer** [comment]
We're just chatting about it now - @lukebond is running the same picks above to see what happens 👍

**Comment by lukebond** [comment]
okay so following @domodwyer's steps i'm able to repro my earlier issue, although the commands he pasted didn't work for me.

first, ran Dom's command:

```
$ cargo run -- run all-in-one --write-buffer-partition-range-start 0 --write-buffer-partition-range-end 0 --pause-ingest-size-bytes 1000000000 --persist-memory-threshold-bytes 1000000000000 --write-buffer file
error: The following required arguments were not provided:
    --write-buffer-addr <CONNECTION_STRING>
```

So I added it (and the DSN which I didn't have as an envvar):

```
$ cargo run -- run all-in-one --write-buffer-partition-range-start 0 --write-buffer-partition-range-end 0 --pause-ingest-size-bytes 1000000000 --persist-memory-threshold-bytes 1000000000000 --write-buffer file --write-buffer-addr /tmp --catalog-dsn postgresql://postgres:password@localhost:5432/iox_shared
thread 'main' panicked at 'assertion failed: pause_ingest_size > persist_memory_threshold', ingester/src/lifecycle.rs:150:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

So I just ran the last command from my bash history that I used last time:
```
$ LOG_FILTER=debug cargo run -- run   all-in-one   --write-buffer=file  --write-buffer-addr /tmp  --catalog-dsn postgresql://postgres:password@localhost:5432/iox_shared  --write-buffer-partition-range-start 0  --write-buffer-partition-range-end 0  --pause-ingest-size-bytes 10000  --persist-memory-threshold-bytes 1000
[snip]
2022-03-24T14:46:02.421207Z  INFO influxdb_ioxd: Binding gRPC services grpc_bind_address=SocketAddr(127.0.0.1:8081)
2022-03-24T14:46:02.421233Z  INFO influxdb_ioxd: Binding gRPC services grpc_bind_address=SocketAddr(127.0.0.1:8083)
2022-03-24T14:46:02.421314Z  INFO influxdb_ioxd: bound gRPC listener local_addr=127.0.0.1:8083
2022-03-24T14:46:02.421314Z  INFO influxdb_ioxd: bound gRPC listener local_addr=127.0.0.1:8081
2022-03-24T14:46:02.421348Z  INFO influxdb_ioxd: No http server specified
2022-03-24T14:46:02.421307Z  INFO influxdb_ioxd: Binding gRPC services grpc_bind_address=SocketAddr(127.0.0.1:8082)
2022-03-24T14:46:02.421389Z  INFO influxdb_ioxd: Completed bind of gRPC, binding http http_bind_address=SocketAddr(127.0.0.1:8080)
2022-03-24T14:46:02.421310Z  INFO influxdb_ioxd: Binding gRPC services grpc_bind_address=SocketAddr(127.0.0.1:8084)
2022-03-24T14:46:02.421415Z  INFO influxdb_ioxd: gRPC server listening
2022-03-24T14:46:02.421434Z  INFO influxdb_ioxd: bound gRPC listener local_addr=127.0.0.1:8082
2022-03-24T14:46:02.421442Z  INFO influxdb_ioxd: HTTP server listening
2022-03-24T14:46:02.421455Z  INFO influxdb_ioxd: No http server specified
2022-03-24T14:46:02.421460Z  INFO influxdb_ioxd: InfluxDB IOx server ready
2022-03-24T14:46:02.421455Z  INFO influxdb_ioxd: bound gRPC listener local_addr=127.0.0.1:8084
2022-03-24T14:46:02.421455Z  INFO influxdb_ioxd: bound HTTP listener bind_addr=127.0.0.1:8080
2022-03-24T14:46:02.421493Z  INFO influxdb_ioxd: No http server specified
2022-03-24T14:46:02.421496Z  INFO influxdb_ioxd: gRPC server listening
2022-03-24T14:46:02.421508Z  INFO influxdb_ioxd: HTTP server listening
2022-03-24T14:46:02.421505Z  INFO influxdb_ioxd: gRPC server listening
2022-03-24T14:46:02.421514Z  INFO influxdb_ioxd: gRPC server listening
2022-03-24T14:46:02.421520Z  INFO influxdb_ioxd: InfluxDB IOx server ready
2022-03-24T14:46:02.421522Z  INFO influxdb_ioxd: HTTP server listening
2022-03-24T14:46:02.421527Z  INFO influxdb_ioxd: HTTP server listening
2022-03-24T14:46:02.421542Z  INFO influxdb_ioxd: InfluxDB IOx server ready
2022-03-24T14:46:02.421541Z  INFO influxdb_ioxd: InfluxDB IOx server ready
2022-03-24T14:46:02.421534Z  INFO sqlx::query: /* SQLx ping */; rows: 0, elapsed: 210.008µs
2022-03-24T14:46:02.421599Z ERROR influxdb_ioxd: server worker shutdown prematurely
2022-03-24T14:46:02.421594Z  INFO sqlx::query: /* SQLx ping */; rows: 0, elapsed: 184.948µs
2022-03-24T14:46:02.421642Z  INFO influxdb_ioxd: HTTP server shutdown
2022-03-24T14:46:02.421666Z  INFO influxdb_ioxd: frontend shutdown completed
2022-03-24T14:46:02.421679Z  INFO influxdb_ioxd: backend shutdown completed
2022-03-24T14:46:02.421751Z  INFO influxdb_ioxd: done serving, draining futures grpc_bind_address=SocketAddr(127.0.0.1:8084) http_bind_address=None
2022-03-24T14:46:02.421781Z DEBUG hyper::server::shutdown: signal received, starting graceful shutdown
2022-03-24T14:46:02.421887Z  INFO influxdb_ioxd: HTTP server shutdown
2022-03-24T14:46:02.421901Z  INFO influxdb_ioxd: frontend shutdown completed
2022-03-24T14:46:02.421923Z  INFO influxdb_ioxd: backend shutdown completed
2022-03-24T14:46:02.422022Z  INFO influxdb_ioxd: done serving, draining futures grpc_bind_address=SocketAddr(127.0.0.1:8081) http_bind_address=Some(SocketAddr(127.0.0.1:8080))
2022-03-24T14:46:02.424214Z  INFO sqlx::query: SELECT column_name.* FROM table_name …; rows: 1, elapsed: 1.116ms

SELECT
  column_name.*
FROM
  table_name
  INNER JOIN column_name on column_name.table_id = table_name.id
WHERE
  table_name.namespace_id = $1;

2022-03-24T14:46:02.424565Z  INFO sqlx::query: /* SQLx ping */; rows: 0, elapsed: 108.619µs
2022-03-24T14:46:02.424575Z  INFO sqlx::query: /* SQLx ping */; rows: 0, elapsed: 175.799µs
2022-03-24T14:46:02.425761Z  INFO sqlx::query: SELECT * FROM table_name …; rows: 1, elapsed: 488.590µs

SELECT
  *
FROM
  table_name
WHERE
  namespace_id = $1;

2022-03-24T14:46:02.426433Z  INFO sqlx::query: /* SQLx ping */; rows: 0, elapsed: 273.190µs
2022-03-24T14:46:02.448066Z DEBUG hyper::server::shutdown: signal received, starting graceful shutdown
2022-03-24T14:46:02.448066Z DEBUG hyper::server::shutdown: signal received, starting graceful shutdown
2022-03-24T14:46:02.450287Z  INFO influxdb_ioxd: gRPC server shutdown
2022-03-24T14:46:02.450306Z  INFO influxdb_ioxd: frontend shutdown completed
2022-03-24T14:46:02.450305Z  INFO influxdb_ioxd: gRPC server shutdown
2022-03-24T14:46:02.450325Z  INFO influxdb_ioxd: frontend shutdown completed
2022-03-24T14:46:02.450384Z  INFO querier::database: Database sync shutdown
2022-03-24T14:46:02.450454Z  INFO ingester::lifecycle: Lifecycle manager shutdown
2022-03-24T14:46:02.450483Z  INFO ingester::handler: Stream handler shutdown kafka_topic="iox-shared" kafka_partition=0
2022-03-24T14:46:02.450528Z  INFO influxdb_ioxd: backend shutdown completed
2022-03-24T14:46:02.450654Z  INFO influxdb_ioxd: backend shutdown completed
2022-03-24T14:46:02.450747Z  INFO influxdb_ioxd: done serving, draining futures grpc_bind_address=SocketAddr(127.0.0.1:8083) http_bind_address=None
Server command failed: Error in all in one subcommand: Run: Early server shutdown
```

**Comment by domodwyer** [comment]
I managed to reproduce it from your CLI args:

```console
$ LOG_FILTER=debug cargo run -- run   all-in-one   --write-buffer=file  --write-buffer-addr /tmp  --write-buffer-partition-range-start 0  --write-buffer-partition-range-end 0  --pause-ingest-size-bytes 10000  --persist-memory-threshold-bytes 1000
    Finished dev [unoptimized + debuginfo] target(s) in 0.29s
     Running `target/debug/influxdb_iox run all-in-one --write-buffer=file --write-buffer-addr /tmp --write-buffer-partition-range-start 0 --write-buffer-partition-range-end 0 --pause-ingest-size-bytes 10000 --persist-memory-threshold-bytes 1000`
2022-03-24T15:11:34.505534Z  INFO influxdb_iox::commands::run::all_in_one: Automatically configuring creation of a single topic default_config=1

<snip>

2022-03-24T15:11:34.573268Z  INFO influxdb_iox::commands::run::all_in_one: starting all in one server
2022-03-24T15:11:34.573599Z  INFO influxdb_ioxd: InfluxDB IOx server starting git_hash="UNKNOWN" num_cpus=10 build_malloc_conf=
2022-03-24T15:11:34.573674Z  INFO sqlx::query: /* SQLx ping */; rows: 0, elapsed: 130.583µs
2022-03-24T15:11:34.573980Z  INFO influxdb_ioxd: Binding gRPC services grpc_bind_address=SocketAddr(127.0.0.1:8083)
2022-03-24T15:11:34.573986Z  INFO influxdb_ioxd: Binding gRPC services grpc_bind_address=SocketAddr(127.0.0.1:8084)
2022-03-24T15:11:34.573985Z  INFO influxdb_ioxd: Binding gRPC services grpc_bind_address=SocketAddr(127.0.0.1:8081)
2022-03-24T15:11:34.574020Z  INFO influxdb_ioxd: Binding gRPC services grpc_bind_address=SocketAddr(127.0.0.1:8082)
2022-03-24T15:11:34.574171Z  INFO influxdb_ioxd: bound gRPC listener local_addr=127.0.0.1:8083
2022-03-24T15:11:34.574161Z  INFO influxdb_ioxd: bound gRPC listener local_addr=127.0.0.1:8081
2022-03-24T15:11:34.574160Z  INFO influxdb_ioxd: bound gRPC listener local_addr=127.0.0.1:8084
2022-03-24T15:11:34.574168Z  INFO influxdb_ioxd: bound gRPC listener local_addr=127.0.0.1:8082
2022-03-24T15:11:34.574221Z  INFO influxdb_ioxd: No http server specified
2022-03-24T15:11:34.574224Z  INFO influxdb_ioxd: Completed bind of gRPC, binding http http_bind_address=SocketAddr(127.0.0.1:8080)
2022-03-24T15:11:34.574233Z  INFO influxdb_ioxd: No http server specified
2022-03-24T15:11:34.574216Z  INFO influxdb_ioxd: No http server specified
2022-03-24T15:11:34.574287Z  INFO influxdb_ioxd: gRPC server listening
2022-03-24T15:11:34.574287Z  INFO influxdb_ioxd: gRPC server listening
2022-03-24T15:11:34.574299Z  INFO influxdb_ioxd: HTTP server listening
2022-03-24T15:11:34.574301Z  INFO influxdb_ioxd: HTTP server listening
2022-03-24T15:11:34.574308Z  INFO influxdb_ioxd: InfluxDB IOx server ready
2022-03-24T15:11:34.574310Z  INFO influxdb_ioxd: InfluxDB IOx server ready
2022-03-24T15:11:34.574311Z  INFO influxdb_ioxd: gRPC server listening
2022-03-24T15:11:34.574323Z  INFO influxdb_ioxd: HTTP server listening
2022-03-24T15:11:34.574331Z  INFO influxdb_ioxd: InfluxDB IOx server ready
2022-03-24T15:11:34.574353Z  INFO influxdb_ioxd: bound HTTP listener bind_addr=127.0.0.1:8080
2022-03-24T15:11:34.574374Z  INFO influxdb_ioxd: gRPC server listening
2022-03-24T15:11:34.574382Z  INFO influxdb_ioxd: HTTP server listening
2022-03-24T15:11:34.574399Z  INFO influxdb_ioxd: InfluxDB IOx server ready
2022-03-24T15:11:34.575323Z  INFO sqlx::query: SELECT * FROM namespace; …; rows: 0, elapsed: 1.216ms

SELECT
  *
FROM
  namespace;

2022-03-24T15:11:34.575535Z  INFO querier::database: Syncing namespaces add=0 delete=0 actual=0 desired=0
2022-03-24T15:11:34.575778Z  INFO sqlx::query: /* SQLx ping */; rows: 0, elapsed: 96.000µs
2022-03-24T15:11:34.603673Z ERROR influxdb_ioxd: server worker shutdown prematurely
2022-03-24T15:11:34.603736Z DEBUG hyper::server::shutdown: signal received, starting graceful shutdown
2022-03-24T15:11:34.603757Z  INFO influxdb_ioxd: HTTP server shutdown
2022-03-24T15:11:34.603769Z  INFO influxdb_ioxd: frontend shutdown completed
2022-03-24T15:11:34.603799Z  INFO influxdb_ioxd: HTTP server shutdown
2022-03-24T15:11:34.603822Z  INFO influxdb_ioxd: frontend shutdown completed
2022-03-24T15:11:34.603826Z  INFO ingester::lifecycle: Lifecycle manager shutdown
2022-03-24T15:11:34.603844Z  INFO querier::database: Database sync shutdown
2022-03-24T15:11:34.603819Z  INFO ingester::handler: Stream handler shutdown kafka_topic="iox-shared" kafka_partition=0
2022-03-24T15:11:34.604244Z  INFO influxdb_ioxd: backend shutdown completed
2022-03-24T15:11:34.604753Z  INFO influxdb_ioxd: backend shutdown completed
2022-03-24T15:11:34.606058Z  INFO influxdb_ioxd: gRPC server shutdown
2022-03-24T15:11:34.606074Z  INFO influxdb_ioxd: frontend shutdown completed
2022-03-24T15:11:34.606082Z  INFO influxdb_ioxd: backend shutdown completed
2022-03-24T15:11:34.606138Z  INFO influxdb_ioxd: done serving, draining futures grpc_bind_address=SocketAddr(127.0.0.1:8084) http_bind_address=None
2022-03-24T15:11:34.606157Z  INFO trace_exporters::export: batched exporter shutting down
2022-03-24T15:11:34.606194Z  INFO trace_exporters::export: async exporter shut down
2022-03-24T15:11:34.606224Z DEBUG hyper::server::shutdown: signal received, starting graceful shutdown
2022-03-24T15:11:34.606243Z  INFO influxdb_ioxd: done serving, draining futures grpc_bind_address=SocketAddr(127.0.0.1:8083) http_bind_address=None
2022-03-24T15:11:34.606258Z  INFO trace_exporters::export: batched exporter shutting down
2022-03-24T15:11:34.606273Z  INFO influxdb_ioxd: HTTP server shutdown
2022-03-24T15:11:34.606283Z  INFO influxdb_ioxd: frontend shutdown completed
2022-03-24T15:11:34.606294Z  INFO influxdb_ioxd: backend shutdown completed
2022-03-24T15:11:34.606647Z  INFO influxdb_ioxd: done serving, draining futures grpc_bind_address=SocketAddr(127.0.0.1:8082) http_bind_address=None
2022-03-24T15:11:34.606667Z  INFO trace_exporters::export: batched exporter shutting down
2022-03-24T15:11:34.607836Z  INFO influxdb_ioxd: done serving, draining futures grpc_bind_address=SocketAddr(127.0.0.1:8081) http_bind_address=Some(SocketAddr(127.0.0.1:8080))
2022-03-24T15:11:34.607856Z  INFO trace_exporters::export: batched exporter shutting down
Server command failed: Error in all in one subcommand: Run: Early server shutdown
```

When I add `--write-buffer-addr /tmp` to my CLI args:

```console
$ cr \
-- run all-in-one \
--write-buffer=file \
--write-buffer-addr /tmp \
--write-buffer-partition-range-start 0 \
--write-buffer-partition-range-end 0 \
--pause-ingest-size-bytes 1000000000 \
--persist-memory-threshold-bytes 1000000000000 
```

I get the assert:

```console
thread 'main' panicked at 'assertion failed: pause_ingest_size > persist_memory_threshold', ingester/src/lifecycle.rs:150:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::panicking::panic
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:48:5
   3: ingester::lifecycle::LifecycleConfig::new
             at ./ingester/src/lifecycle.rs:150:9
   4: influxdb_ioxd::server_type::ingester::create_ingester_server_type::{{closure}}
             at ./influxdb_ioxd/src/server_type/ingester.rs:174:28
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/mod.rs:84:19
   6: influxdb_iox::commands::run::all_in_one::command::{{closure}}
             at ./influxdb_iox/src/commands/run/all_in_one.rs:353:6
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/mod.rs:84:19
   8: influxdb_iox::commands::run::command::{{closure}}
             at ./influxdb_iox/src/commands/run/mod.rs:116:71
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/mod.rs:84:19
  10: influxdb_iox::main::{{closure}}
             at ./influxdb_iox/src/main.rs:284:64
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/mod.rs:84:19
  12: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/park/thread.rs:263:54
  13: tokio::coop::with_budget::{{closure}}
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:102:9
  14: std::thread::local::LocalKey<T>::try_with
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/thread/local.rs:412:16
  15: std::thread::local::LocalKey<T>::with
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/thread/local.rs:388:9
  16: tokio::coop::with_budget
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:95:5
  17: tokio::coop::budget
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:72:5
  18: tokio::park::thread::CachedParkThread::block_on
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/park/thread.rs:263:31
  19: tokio::runtime::enter::Enter::block_on
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/enter.rs:151:13
  20: tokio::runtime::thread_pool::ThreadPool::block_on
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/mod.rs:73:9
  21: tokio::runtime::Runtime::block_on
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/mod.rs:477:43
  22: influxdb_iox::main
             at ./influxdb_iox/src/main.rs:203:5
  23: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2022-03-24T15:29:24.136582Z  WARN executor: DedicatedExecutor dropped without calling shutdown()
2022-03-24T15:29:24.137004Z  WARN executor: DedicatedExecutor dropped without calling shutdown()
2022-03-24T15:29:24.137602Z ERROR trace_exporters::export: sender-side of async exporter dropped without waiting for shut down
```

and when I swap the numbers around:

```console
$ cr \
-- run all-in-one \
--write-buffer=file \
--write-buffer-addr /tmp \
--write-buffer-partition-range-start 0 \
--write-buffer-partition-range-end 0 \
--pause-ingest-size-bytes 1000000000000 \
--persist-memory-threshold-bytes 1000000000
```

I also get the early shutdown:

```console

<...snip...>

2022-03-24T15:32:01.582875Z  INFO influxdb_ioxd: Binding gRPC services grpc_bind_address=SocketAddr(127.0.0.1:8082)
2022-03-24T15:32:01.582871Z  INFO influxdb_ioxd: Binding gRPC services grpc_bind_address=SocketAddr(127.0.0.1:8084)
2022-03-24T15:32:01.582874Z  INFO influxdb_ioxd: Binding gRPC services grpc_bind_address=SocketAddr(127.0.0.1:8081)
2022-03-24T15:32:01.582870Z  INFO influxdb_ioxd: Binding gRPC services grpc_bind_address=SocketAddr(127.0.0.1:8083)
2022-03-24T15:32:01.583070Z  INFO influxdb_ioxd: bound gRPC listener local_addr=127.0.0.1:8083
2022-03-24T15:32:01.583068Z  INFO influxdb_ioxd: bound gRPC listener local_addr=127.0.0.1:8082
2022-03-24T15:32:01.583070Z  INFO influxdb_ioxd: bound gRPC listener local_addr=127.0.0.1:8081
2022-03-24T15:32:01.583069Z  INFO influxdb_ioxd: bound gRPC listener local_addr=127.0.0.1:8084
2022-03-24T15:32:01.583126Z  INFO influxdb_ioxd: No http server specified
2022-03-24T15:32:01.583130Z  INFO influxdb_ioxd: No http server specified
2022-03-24T15:32:01.583130Z  INFO influxdb_ioxd: Completed bind of gRPC, binding http http_bind_address=SocketAddr(127.0.0.1:8080)
2022-03-24T15:32:01.583126Z  INFO influxdb_ioxd: No http server specified
2022-03-24T15:32:01.583200Z  INFO influxdb_ioxd: gRPC server listening
2022-03-24T15:32:01.583211Z  INFO influxdb_ioxd: gRPC server listening
2022-03-24T15:32:01.583214Z  INFO influxdb_ioxd: gRPC server listening
2022-03-24T15:32:01.583221Z  INFO influxdb_ioxd: HTTP server listening
2022-03-24T15:32:01.583226Z  INFO influxdb_ioxd: HTTP server listening
2022-03-24T15:32:01.583214Z  INFO influxdb_ioxd: HTTP server listening
2022-03-24T15:32:01.583230Z  INFO influxdb_ioxd: InfluxDB IOx server ready
2022-03-24T15:32:01.583261Z  INFO influxdb_ioxd: bound HTTP listener bind_addr=127.0.0.1:8080
2022-03-24T15:32:01.583267Z  INFO influxdb_ioxd: InfluxDB IOx server ready
2022-03-24T15:32:01.583236Z  INFO influxdb_ioxd: InfluxDB IOx server ready
2022-03-24T15:32:01.583277Z  INFO influxdb_ioxd: gRPC server listening
2022-03-24T15:32:01.583309Z  INFO influxdb_ioxd: HTTP server listening
2022-03-24T15:32:01.583320Z  INFO influxdb_ioxd: InfluxDB IOx server ready
2022-03-24T15:32:01.583460Z ERROR influxdb_ioxd: server worker shutdown prematurely
2022-03-24T15:32:01.584324Z  INFO sqlx::query: SELECT * FROM namespace; …; rows: 0, elapsed: 1.195ms

SELECT
  *
FROM
  namespace;

2022-03-24T15:32:01.584534Z  INFO influxdb_ioxd: HTTP server shutdown
2022-03-24T15:32:01.584548Z  INFO influxdb_ioxd: frontend shutdown completed
2022-03-24T15:32:01.584561Z  INFO influxdb_ioxd: backend shutdown completed
2022-03-24T15:32:01.584618Z  INFO querier::database: Syncing namespaces add=0 delete=0 actual=0 desired=0
2022-03-24T15:32:01.584651Z  INFO influxdb_ioxd: done serving, draining futures grpc_bind_address=SocketAddr(127.0.0.1:8081) http_bind_address=Some(SocketAddr(127.0.0.1:8080))
2022-03-24T15:32:01.584671Z  INFO trace_exporters::export: batched exporter shutting down
2022-03-24T15:32:01.584732Z  INFO trace_exporters::export: async exporter shut down
2022-03-24T15:32:01.584881Z  INFO sqlx::query: /* SQLx ping */; rows: 0, elapsed: 95.250µs
2022-03-24T15:32:01.613383Z  INFO influxdb_ioxd: gRPC server shutdown
2022-03-24T15:32:01.613383Z  INFO influxdb_ioxd: gRPC server shutdown
2022-03-24T15:32:01.613412Z  INFO influxdb_ioxd: frontend shutdown completed
2022-03-24T15:32:01.613418Z  INFO influxdb_ioxd: frontend shutdown completed
2022-03-24T15:32:01.613422Z  INFO influxdb_ioxd: backend shutdown completed
2022-03-24T15:32:01.613392Z  INFO influxdb_ioxd: gRPC server shutdown
2022-03-24T15:32:01.613466Z  INFO influxdb_ioxd: frontend shutdown completed
2022-03-24T15:32:01.613490Z  INFO influxdb_ioxd: done serving, draining futures grpc_bind_address=SocketAddr(127.0.0.1:8084) http_bind_address=None
2022-03-24T15:32:01.613508Z  INFO trace_exporters::export: batched exporter shutting down
2022-03-24T15:32:01.613515Z  INFO ingester::lifecycle: Lifecycle manager shutdown
2022-03-24T15:32:01.613870Z  INFO querier::database: Database sync shutdown
2022-03-24T15:32:01.613926Z  INFO influxdb_ioxd: backend shutdown completed
2022-03-24T15:32:01.613988Z  INFO influxdb_ioxd: done serving, draining futures grpc_bind_address=SocketAddr(127.0.0.1:8082) http_bind_address=None
2022-03-24T15:32:01.614006Z  INFO trace_exporters::export: batched exporter shutting down
2022-03-24T15:32:01.614133Z  INFO ingester::handler: Stream handler shutdown kafka_topic="iox-shared" kafka_partition=0
2022-03-24T15:32:01.614284Z  INFO influxdb_ioxd: backend shutdown completed
2022-03-24T15:32:01.614777Z  INFO influxdb_ioxd: done serving, draining futures grpc_bind_address=SocketAddr(127.0.0.1:8083) http_bind_address=None
2022-03-24T15:32:01.614794Z  INFO trace_exporters::export: batched exporter shutting down
Server command failed: Error in all in one subcommand: Run: Early server shutdown
```

So it looks like adding `--write-buffer-addr /tmp` triggers the issue.
