### ISSUE TITLE
Querier connected to multiple ingesters errors when one does not have information for the table

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#4298]
__Steps to reproduce:__
Configure an IOx querier to talk to several ingesters, only one of which has data for that ingester

__Expected behaviour:__
I expect the query to complete

__Actual behaviour:__

I get a query error
```sql
797a0180da80497c_ce59a0ee2de3ed17> select * from statuses;
Error running remote query: status: InvalidArgument, message: "Error while planning query: Execution error: Join Error: channel closed", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Wed, 13 Apr 2022 11:50:09 GMT"} }
```

And a panic i the log
```
level=error msg="Thread panic" panic_info="panicked at 'error performing query: GrpcError(Status { code: Internal, message: \"Error while performing query: No Table Data found for the given namespace name 797a0180da80497c_ce59a0ee2de3ed17, table name statuses\", metadata: MetadataMap { headers: {\"content-type\": \"application/grpc\", \"server\": \"envoy\", \"x-envoy-upstream-service-time\": \"1\", \"date\": \"Wed, 13 Apr 2022 11:50:22 GMT\"} }, source: None })', querier/src/ingester/mod.rs:152:18" target="panic_logging" location="panic_logging/src/lib.rs:94" time=1649850622284618910
thread 'IOx Query Executor Thread' panicked at 'error performing query: GrpcError(Status { code: Internal, message: "Error while performing query: No Table Data found for the given namespace name 797a0180da80497c_ce59a0ee2de3ed17, table name statuses", metadata: MetadataMap { headers: {"content-type": "application/grpc", "server": "envoy", "x-envoy-upstream-service-time": "1", "date": "Wed, 13 Apr 2022 11:50:22 GMT"} }, source: None })', querier/src/ingester/mod.rs:152:18
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
   3: core::result::Result<T,E>::expect
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1022:23
   4: <querier::ingester::IngesterConnectionImpl as querier::ingester::IngesterConnection>::partitions::{{closure}}
             at ./influxdb_iox/querier/src/ingester/mod.rs:149:37
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
   6: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/future.rs:123:9
   7: querier::table::QuerierTable::ingester_partitions::{{closure}}
             at ./influxdb_iox/querier/src/table/mod.rs:244:14
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
   9: querier::table::QuerierTable::chunks::{{closure}}
             at ./influxdb_iox/querier/src/table/mod.rs:124:70
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  11: querier::table::query_access::<impl datafusion::datasource::datasource::TableProvider for querier::table::QuerierTable>::scan::{{closure}}
             at ./influxdb_iox/querier/src/table/query_access.rs:52:32
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  13: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/future.rs:123:9
  14: datafusion::physical_plan::planner::DefaultPhysicalPlanner::create_initial_plan::{{closure}}
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/fa9e016/datafusion/core/src/physical_plan/planner.rs:346:64
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  16: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/future.rs:123:9
  17: datafusion::physical_plan::planner::DefaultPhysicalPlanner::create_initial_plan::{{closure}}
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/fa9e016/datafusion/core/src/physical_plan/planner.rs:577:84
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  19: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/future.rs:123:9
  20: <datafusion::physical_plan::planner::DefaultPhysicalPlanner as datafusion::physical_plan::planner::PhysicalPlanner>::create_physical_plan::{{closure}}
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/fa9e016/datafusion/core/src/physical_plan/planner.rs:284:70
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  22: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/future.rs:123:9
  23: <query::exec::context::IOxQueryPlanner as datafusion::execution::context::QueryPlanner>::create_physical_plan::{{closure}}
             at ./influxdb_iox/query/src/exec/context.rs:83:63
  24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  25: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/future.rs:123:9
  26: datafusion::execution::context::SessionState::create_physical_plan::{{closure}}
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/fa9e016/datafusion/core/src/execution/context.rs:1356:57
  27: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  28: datafusion::execution::context::SessionContext::create_physical_plan::{{closure}}
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/fa9e016/datafusion/core/src/execution/context.rs:823:56
  29: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  30: query::exec::context::IOxSessionContext::prepare_plan::{{closure}}
             at ./influxdb_iox/query/src/exec/context.rs:295:66
  31: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  32: query::exec::context::IOxSessionContext::prepare_sql::{{closure}}
             at ./influxdb_iox/query/src/exec/context.rs:282:40
  33: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  34: query::frontend::sql::SqlQueryPlanner::query::{{closure}}
             at ./influxdb_iox/query/src/frontend/sql.rs:22:31
  35: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  36: service_common::planner::Planner::sql::{{closure}}::{{closure}}
             at ./influxdb_iox/service_common/src/planner.rs:43:58
  37: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  38: executor::DedicatedExecutor::spawn::{{closure}}
             at ./influxdb_iox/executor/src/lib.rs:233:35
  39: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  40: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/future.rs:123:9
  41: executor::Task::run::{{closure}}::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/macros/select.rs:505:49
  42: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/future/poll_fn.rs:38:9
  43: executor::Task::run::{{closure}}
             at ./influxdb_iox/executor/src/lib.rs:43:9
  44: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  45: executor::DedicatedExecutor::new::{{closure}}::{{closure}}::{{closure}}
             at ./influxdb_iox/executor/src/lib.rs:195:35
  46: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  47: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.33/src/instrument.rs:272:9
  48: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/core.rs:161:17
  49: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/loom/std/unsafe_cell.rs:14:9
  50: tokio::runtime::task::core::CoreStage<T>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/core.rs:151:13
  51: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:467:19
  52: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panic/unwind_safe.rs:271:9
  53: std::panicking::try::do_call
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  54: std::panicking::try
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  55: std::panic::catch_unwind
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  56: tokio::runtime::task::harness::poll_future
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:455:18
  57: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:103:27
  58: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:57:15
  59: tokio::runtime::task::raw::RawTask::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/raw.rs:80:18
  60: tokio::runtime::task::LocalNotified<S>::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/mod.rs:347:9
  61: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:448:21
  62: tokio::coop::with_budget::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:102:9
  63: std::thread::local::LocalKey<T>::try_with
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/local.rs:413:16
  64: std::thread::local::LocalKey<T>::with
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/local.rs:389:9
  65: tokio::coop::with_budget
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:95:5
  66: tokio::coop::budget
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:72:5
  67: tokio::runtime::thread_pool::worker::Context::run_task
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:424:9
  68: tokio::runtime::thread_pool::worker::Context::run
  69: tokio::runtime::thread_pool::worker::run::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:376:17
  70: tokio::macros::scoped_tls::ScopedKey<T>::set
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/macros/scoped_tls.rs:61:9
  71: tokio::runtime::thread_pool::worker::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:373:5
  72: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:352:45
  73: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/task.rs:42:21
  74: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.33/src/instrument.rs:272:9
  75: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/core.rs:161:17
  76: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/loom/std/unsafe_cell.rs:14:9
  77: tokio::runtime::task::core::CoreStage<T>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/core.rs:151:13
  78: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:467:19
  79: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panic/unwind_safe.rs:271:9
  80: std::panicking::try::do_call
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  81: std::panicking::try
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  82: std::panic::catch_unwind
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  83: tokio::runtime::task::harness::poll_future
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:455:18
  84: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:103:27
  85: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:57:15
  86: tokio::runtime::task::raw::RawTask::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/raw.rs:80:18
  87: tokio::runtime::task::UnownedTask<S>::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/mod.rs:384:9
  88: tokio::runtime::blocking::pool::Task::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/pool.rs:91:9
  89: tokio::runtime::blocking::pool::Inner::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/pool.rs:308:17
  90: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/pool.rs:288:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
level=warn err="Planning { source: Execution(\"Join Error: channel closed\") }" msg="Error handling Flight gRPC request" target="service_grpc_flight" location="service_grpc_flight/src/lib.rs:100" time=1649850622288099612
(arrow_dev) alamb@MacBook-Pro-2:~/Software/k8s-idpe$ kubectl  --context dex@prod01-eu-central-1-aws -n iox logs iox-shared-querier-fbd565d85-b4rk9 | less

  83: tokio::runtime::task::harness::poll_future
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:455:18
  84: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:103:27
  85: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:57:15
  86: tokio::runtime::task::raw::RawTask::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/raw.rs:80:18
  87: tokio::runtime::task::UnownedTask<S>::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/mod.rs:384:9
  88: tokio::runtime::blocking::pool::Task::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/pool.rs:91:9
  89: tokio::runtime::blocking::pool::Inner::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/pool.rs:308:17
  90: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/pool.rs:288:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
__Environment info:__

* Please provide the command you used to build the project, including any `RUSTFLAGS`.
* System info: Run `uname -srm` or similar and copy the output here (we want to know your OS, architecture etc).
* If you're running IOx in a containerised environment then details about that would be helpful.
* Other relevant environment details: disk info, hardware setup etc.

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in logs or stack traces here.
Sometimes you can get useful information by running the program with the `RUST_BACKTRACE=full` environment variable.
Finally, the IOx server has a `-vv` for verbose logging.

**Comment by crepererum** [comment]
This is likely the "table not found" edge case we've talked about. This is currently exposed as an internal gRPC error. I'm working on a fix for that.

**Comment by alamb** [comment]
I will work on an end to end test
