### ISSUE TITLE
Flaky test    end_to_end_ng_cases::querier::multi_ingester::basic_multi_ingesters

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#4395]
Test fails https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/18376/workflows/25b4b161-0bbb-4d65-9a36-c900548caea0/jobs/153044

But succeeded on a rerun: https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/18376/workflows/3e951e32-e802-41c2-bdce-cb769874c718/jobs/153090

Failure was
```
failures:

---- end_to_end_ng_cases::querier::multi_ingester::basic_multi_ingesters stdout ----
thread 'end_to_end_ng_cases::querier::multi_ingester::basic_multi_ingesters' panicked at 'assertion failed: `(left == right)`
  left: `["+------+------+--------------------------------+-----+", "| tag1 | tag2 | time                           | val |", "+------+------+--------------------------------+-----+", "| A    | B    | 1970-01-01T00:00:00.000123456Z | 5   |", "+------+------+--------------------------------+-----+"]`,
 right: `["++", "++"]`: 

expected:

[
    "+------+------+--------------------------------+-----+",
    "| tag1 | tag2 | time                           | val |",
    "+------+------+--------------------------------+-----+",
    "| A    | B    | 1970-01-01T00:00:00.000123456Z | 5   |",
    "+------+------+--------------------------------+-----+",
]
actual:

[
    "++",
    "++",
]

', /home/rust/project/test_helpers_end_to_end_ng/src/steps.rs:177:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:182:5
   4: test_helpers_end_to_end_ng::steps::StepTest::run::{{closure}}
             at /home/rust/project/test_helpers_end_to_end_ng/src/steps.rs:177:21
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
   6: end_to_end_ng::end_to_end_ng_cases::querier::multi_ingester::basic_multi_ingesters::{{closure}}
             at ./tests/end_to_end_ng_cases/querier/multi_ingester.rs:122:50
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
   8: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/future.rs:123:9
   9: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:498:48
  10: tokio::coop::with_budget::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:102:9
  11: std::thread::local::LocalKey<T>::try_with
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/local.rs:413:16
  12: std::thread::local::LocalKey<T>::with
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/local.rs:389:9
  13: tokio::coop::with_budget
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:95:5
  14: tokio::coop::budget
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:72:5
  15: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:498:25
  16: tokio::runtime::basic_scheduler::Context::enter
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:356:19
  17: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:497:36
  18: tokio::runtime::basic_scheduler::CoreGuard::enter::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:555:57
  19: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/macros/scoped_tls.rs:61:9
  20: tokio::runtime::basic_scheduler::CoreGuard::enter
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:555:27
  21: tokio::runtime::basic_scheduler::CoreGuard::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:488:9
  22: tokio::runtime::basic_scheduler::BasicScheduler::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:168:24
  23: tokio::runtime::Runtime::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/mod.rs:475:46
  24: end_to_end_ng::end_to_end_ng_cases::querier::multi_ingester::basic_multi_ingesters
             at ./tests/end_to_end_ng_cases/querier/multi_ingester.rs:122:5
  25: end_to_end_ng::end_to_end_ng_cases::querier::multi_ingester::basic_multi_ingesters::{{closure}}
             at ./tests/end_to_end_ng_cases/querier/multi_ingester.rs:17:7
  26: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
  27: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2022-04-22T11:30:48.256576Z  INFO iox_catalog::postgres: connected to config store application_name=router2
2022-04-22T11:30:48.260636Z  INFO ioxd_router2: connected to write buffer topic topic="iox-shared" shards=2
2022-04-22T11:30:48.267277Z  INFO influxdb_iox::commands::run::router2: starting router2
2022-04-22T11:30:48.272312Z  INFO influxdb_iox::commands::run::main: InfluxDB IOx server starting git_hash="7f7809f291bf85490c2181d7241c4c0372a2b84a" num_cpus=32 build_malloc_conf=
2022-04-22T11:30:48.272768Z  INFO influxdb_iox::commands::run::main: Binding gRPC services grpc_bind_address=SocketAddr(127.0.0.1:8172)
2022-04-22T11:30:48.272952Z  INFO ioxd_common: bound gRPC listener local_addr=127.0.0.1:8172
2022-04-22T11:30:48.273003Z  INFO influxdb_iox::commands::run::main: Completed bind of gRPC, binding http http_bind_address=SocketAddr(127.0.0.1:8171)
2022-04-22T11:30:48.273077Z  INFO ioxd_common: bound HTTP listener bind_addr=127.0.0.1:8171
2022-04-22T11:30:48.273183Z  INFO ioxd_common: gRPC server listening
2022-04-22T11:30:48.273217Z  INFO ioxd_common: HTTP server listening
2022-04-22T11:30:49.897607Z  INFO ioxd_common: Received SIGTERM
2022-04-22T11:30:49.897743Z  INFO ioxd_common: Shutdown requested
2022-04-22T11:30:49.898204Z  INFO ioxd_common: HTTP server shutdown
2022-04-22T11:30:49.898268Z  INFO ioxd_common: frontend shutdown completed
2022-04-22T11:30:49.898303Z  INFO ioxd_common: backend shutdown completed
2022-04-22T11:30:49.898382Z  INFO influxdb_iox::commands::run::main: done serving, draining futures grpc_bind_address=SocketAddr(127.0.0.1:8172) http_bind_address=Some(SocketAddr(127.0.0.1:8171))
2022-04-22T11:30:48.442896Z  INFO iox_catalog::postgres: connected to config store application_name=ingester
2022-04-22T11:30:48.453409Z  INFO ingester::handler: ingester handler and lifecycle started with config LifecycleConfig { pause_ingest_size: 20, persist_memory_threshold: 10, partition_size_threshold: 314572800, partition_age_threshold: 1800s, partition_cold_threshold: 300s }
2022-04-22T11:30:48.454255Z  INFO influxdb_iox::commands::run::ingester: starting ingester
2022-04-22T11:30:48.463712Z  INFO influxdb_iox::commands::run::main: InfluxDB IOx server starting git_hash="7f7809f291bf85490c2181d7241c4c0372a2b84a" num_cpus=32 build_malloc_conf=
2022-04-22T11:30:48.464283Z  INFO influxdb_iox::commands::run::main: Binding gRPC services grpc_bind_address=SocketAddr(127.0.0.1:8109)
2022-04-22T11:30:48.464496Z  INFO ioxd_common: bound gRPC listener local_addr=127.0.0.1:8109
2022-04-22T11:30:48.464567Z  INFO influxdb_iox::commands::run::main: Completed bind of gRPC, binding http http_bind_address=SocketAddr(127.0.0.1:8200)
2022-04-22T11:30:48.464642Z  INFO ioxd_common: bound HTTP listener bind_addr=127.0.0.1:8200
2022-04-22T11:30:48.464746Z  INFO ioxd_common: gRPC server listening
2022-04-22T11:30:48.464781Z  INFO ioxd_common: HTTP server listening
2022-04-22T11:30:49.585186Z  WARN ingester::stream_handler::handler: pausing ingest until persistence has run kafka_topic=iox-shared kafka_partition=0
2022-04-22T11:30:49.812231Z  INFO ingester::server::grpc: err=TableNotFound { namespace_name: "5444824352627062_1263880199436024", table_name: "table_5" } msg="Error handling Flight gRPC request"
2022-04-22T11:30:49.922258Z  INFO ioxd_common: Received SIGTERM
2022-04-22T11:30:49.922359Z  INFO ioxd_common: Shutdown requested
2022-04-22T11:30:49.922499Z  INFO ioxd_common: HTTP server shutdown
2022-04-22T11:30:49.922531Z  INFO ioxd_common: frontend shutdown completed
2022-04-22T11:30:49.922672Z  INFO ingester::lifecycle: Lifecycle manager shutdown
2022-04-22T11:30:48.839233Z  INFO iox_catalog::postgres: connected to config store application_name=querier
2022-04-22T11:30:48.839863Z  INFO influxdb_iox::commands::run::querier: using specified number of threads per thread pool num_threads=32
2022-04-22T11:30:48.839919Z  INFO influxdb_iox::commands::run::querier: using ingester addresses ingester_addresses=["http://127.0.0.1:8109", "http://127.0.0.1:8110"]
2022-04-22T11:30:48.840723Z  INFO influxdb_iox::commands::run::querier: starting querier
2022-04-22T11:30:48.846563Z  INFO influxdb_iox::commands::run::main: InfluxDB IOx server starting git_hash="7f7809f291bf85490c2181d7241c4c0372a2b84a" num_cpus=32 build_malloc_conf=
2022-04-22T11:30:48.847070Z  INFO influxdb_iox::commands::run::main: Binding gRPC services grpc_bind_address=SocketAddr(127.0.0.1:8237)
2022-04-22T11:30:48.847311Z  INFO ioxd_common: bound gRPC listener local_addr=127.0.0.1:8237
2022-04-22T11:30:48.847352Z  INFO influxdb_iox::commands::run::main: Completed bind of gRPC, binding http http_bind_address=SocketAddr(127.0.0.1:8236)
2022-04-22T11:30:48.847418Z  INFO ioxd_common: bound HTTP listener bind_addr=127.0.0.1:8236
2022-04-22T11:30:48.847494Z  INFO ioxd_common: gRPC server listening
2022-04-22T11:30:48.847516Z  INFO ioxd_common: HTTP server listening
2022-04-22T11:30:50.926522Z  INFO ioxd_common: Received SIGTERM
2022-04-22T11:30:50.926651Z  INFO ioxd_common: Shutdown requested
2022-04-22T11:30:50.926864Z  INFO ioxd_common: HTTP server shutdown
2022-04-22T11:30:50.926900Z  INFO ioxd_common: frontend shutdown completed
2022-04-22T11:30:50.927007Z  INFO ioxd_common: backend shutdown completed
2022-04-22T11:30:50.927075Z  INFO influxdb_iox::commands::run::main: done serving, draining futures grpc_bind_address=SocketAddr(127.0.0.1:8237) http_bind_address=Some(SocketAddr(127.0.0.1:8236))
2022-04-22T11:30:48.681763Z  INFO iox_catalog::postgres: connected to config store application_name=ingester
2022-04-22T11:30:48.693308Z  INFO ingester::handler: ingester handler and lifecycle started with config LifecycleConfig { pause_ingest_size: 20, persist_memory_threshold: 10, partition_size_threshold: 314572800, partition_age_threshold: 1800s, partition_cold_threshold: 300s }
2022-04-22T11:30:48.694187Z  INFO influxdb_iox::commands::run::ingester: starting ingester
2022-04-22T11:30:48.699821Z  INFO influxdb_iox::commands::run::main: InfluxDB IOx server starting git_hash="7f7809f291bf85490c2181d7241c4c0372a2b84a" num_cpus=32 build_malloc_conf=
2022-04-22T11:30:48.700313Z  INFO influxdb_iox::commands::run::main: Binding gRPC services grpc_bind_address=SocketAddr(127.0.0.1:8110)
2022-04-22T11:30:48.700496Z  INFO ioxd_common: bound gRPC listener local_addr=127.0.0.1:8110
2022-04-22T11:30:48.700552Z  INFO influxdb_iox::commands::run::main: Completed bind of gRPC, binding http http_bind_address=SocketAddr(127.0.0.1:8235)
2022-04-22T11:30:48.700613Z  INFO ioxd_common: bound HTTP listener bind_addr=127.0.0.1:8235
2022-04-22T11:30:48.700701Z  INFO ioxd_common: gRPC server listening
2022-04-22T11:30:48.700725Z  INFO ioxd_common: HTTP server listening
2022-04-22T11:30:49.811523Z  INFO ingester::server::grpc: err=TableNotFound { namespace_name: "5444824352627062_1263880199436024", table_name: "table_5" } msg="Error handling Flight gRPC request"
2022-04-22T11:30:49.877719Z  WARN ingester::stream_handler::handler: pausing ingest until persistence has run kafka_topic=iox-shared kafka_partition=1
2022-04-22T11:30:50.787397Z  INFO ingester::stream_handler::handler: resuming ingest kafka_topic=iox-shared kafka_partition=1 pause_duration=909ms
2022-04-22T11:30:50.944399Z  INFO ioxd_common: Received SIGTERM
2022-04-22T11:30:50.944522Z  INFO ioxd_common: Shutdown requested
2022-04-22T11:30:50.944621Z  INFO ioxd_common: HTTP server shutdown
2022-04-22T11:30:50.944643Z  INFO ioxd_common: frontend shutdown completed
2022-04-22T11:30:50.944768Z  INFO ingester::stream_handler::handler: stream handler shutdown kafka_topic=iox-shared kafka_partition=1
2022-04-22T11:30:50.944778Z  INFO ingester::lifecycle: Lifecycle manager shutdown
2022-04-22T11:30:50.945273Z  INFO ioxd_common: backend shutdown completed
2022-04-22T11:30:50.945446Z  INFO influxdb_iox::commands::run::main: done serving, draining futures grpc_bind_address=SocketAddr(127.0.0.1:8110) http_bind_address=Some(SocketAddr(127.0.0.1:8235))


failures:
    end_to_end_ng_cases::querier::multi_ingester::basic_multi_ingesters

test result: FAILED. 26 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 7.76s
```

**Comment by alamb** [comment]
@NGA-TRAN  reports a similar issue on `end_to_end_cases::persistence::test_full_lifecycle`
https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/18478/workflows/b2214d79-fc7f-4cca-970d-ce0a71a0ea41/jobs/154169

**Comment by alamb** [comment]
another instance: https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/18531/workflows/e27fbf4c-b505-47d6-bc53-3423ba9cc896/jobs/154752

**Comment by alamb** [comment]
I have also seen this symptom:

```
2022-04-28T15:10:26.073681Z ERROR ingester::stream_handler::handler: failed to apply dml operation error=Error accessing catalog: unhandled sqlx error: error returned from database: sorry, too many clients already kafka_topic=iox-shared kafka_partition=1 potential_data_loss=true
```

For which I think https://github.com/influxdata/influxdb_iox/pull/4387 will help

**Comment by alamb** [comment]
Here is another example of https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/18678/workflows/da6bf55c-9922-4ccf-9965-f8e7d339991b/jobs/156428

```
---- end_to_end_ng_cases::querier::multi_ingester::basic_multi_ingesters stdout ----
thread 'end_to_end_ng_cases::querier::multi_ingester::basic_multi_ingesters' panicked at 'assertion failed: `(left == right)`
  left: `["+------+------+--------------------------------+-----+", "| tag1 | tag2 | time                           | val |", "+------+------+--------------------------------+-----+", "| A    | B    | 1970-01-01T00:00:00.000123456Z | 5   |", "+------+------+--------------------------------+-----+"]`,
 right: `["++", "++"]`: 

expected:

[
    "+------+------+--------------------------------+-----+",
    "| tag1 | tag2 | time                           | val |",
    "+------+------+--------------------------------+-----+",
    "| A    | B    | 1970-01-01T00:00:00.000123456Z | 5   |",
    "+------+------+--------------------------------+-----+",
]
actual:

[
    "++",
    "++",
]
```

**Comment by alamb** [comment]
Here is an example failure with the logging: https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/18730/workflows/91e0c0cf-31c2-4298-aab2-d5efc6c67f58/jobs/157016

```
failures:

---- end_to_end_ng_cases::querier::multi_ingester::basic_multi_ingesters stdout ----
retrying, not yet readable: GetWriteInfoResponse { kafka_partition_infos: [KafkaPartitionInfo { kafka_partition_id: 1, status: Unknown }, KafkaPartitionInfo { kafka_partition_id: 0, status: Unknown }] }
retrying, not yet readable: GetWriteInfoResponse { kafka_partition_infos: [KafkaPartitionInfo { kafka_partition_id: 0, status: Unknown }, KafkaPartitionInfo { kafka_partition_id: 1, status: Unknown }] }
All data is readable: GetWriteInfoResponse { kafka_partition_infos: [KafkaPartitionInfo { kafka_partition_id: 0, status: Readable }, KafkaPartitionInfo { kafka_partition_id: 1, status: Readable }] }
thread 'end_to_end_ng_cases::querier::multi_ingester::basic_multi_ingesters' panicked at 'assertion failed: `(left == right)`
  left: `["+------+------+--------------------------------+-----+", "| tag1 | tag2 | time                           | val |", "+------+------+--------------------------------+-----+", "| A    | B    | 1970-01-01T00:00:00.000123456Z | 5   |", "+------+------+--------------------------------+-----+"]`,
 right: `["++", "++"]`: 

expected:

[
    "+------+------+--------------------------------+-----+",
    "| tag1 | tag2 | time                           | val |",
    "+------+------+--------------------------------+-----+",
    "| A    | B    | 1970-01-01T00:00:00.000123456Z | 5   |",
    "+------+------+--------------------------------+-----+",
]
actual:

[
    "++",
    "++",
]
```
Very intriguing...

**Comment by alamb** [comment]
some other examples

 https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/18848/workflows/42a77bf6-0a61-45e9-9014-a6a417620f49/jobs/158299

https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/18850/workflows/f67a6454-4a6d-43d9-b471-14b1e422e1d9/jobs/158325

**Comment by alamb** [comment]
Another one: https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/19157/workflows/d011530b-1840-4e92-bce6-deb51e1e5bc0/jobs/161481

**Comment by alamb** [comment]
@carols10cents  has a good lead -- more details https://github.com/influxdata/influxdb_iox/pull/4609#issuecomment-1128146435

**Comment by carols10cents** [comment]
got another one, i'll see if i have some time to stare at the logs today https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/19423/workflows/c685c41b-25aa-42e6-8c5a-3ffba3602155/jobs/164158

**Comment by alamb** [comment]
Also FWI I am messing with that code in the context of https://github.com/influxdata/influxdb_iox/issues/4634

So perhaps I will stumble on the issue while working on that

**Comment by carols10cents** [comment]
We got another one though: https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/19466/workflows/8768b930-dc0c-476f-9966-1d4545833bc3/jobs/164592

This is really weird. I'm seeing some logging messages of the ingesters persisting tables, but I don't see either ingester persisting `table_5` specifically. But same as [here](https://github.com/influxdata/influxdb_iox/pull/4609#issuecomment-1128723433), both ingesters are saying they don't know about that table and the catalog doesn't have any parquet files for it either...

**Comment by alamb** [comment]
Another example: https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/19561/workflows/21127431-e8bd-436d-8dc5-1a7c7228ba68/jobs/165544

**Comment by alamb** [comment]
More proposed debugging: https://github.com/influxdata/influxdb_iox/pull/4684

**Comment by alamb** [comment]
I ran the test in a loop for 1000 iterations and it failed after 560 -- see [fail_with_logs.txt](https://github.com/influxdata/influxdb_iox/files/8782086/fail_with_logs.txt)

Digging into that now

**Comment by alamb** [comment]
https://github.com/influxdata/influxdb_iox/pull/4711 I think fixes the symptom @carols10cents mentions in https://github.com/influxdata/influxdb_iox/issues/4395#issuecomment-1132167702 but it doesn't explain the error that some of the data is not readable

**Comment by alamb** [comment]
I still am having issues getting this test to fail locally with debug logging on, which presumably changes the timing. Perhaps this is why we don't see it on master after @carols10cents  turned on debug logs on CI in https://github.com/influxdata/influxdb_iox/pull/4609 -- "heisenbug".

However, when I have debug logging off it does still fail so I still think this is a real issue

**Comment by alamb** [comment]
Here is the next failure (logs in [next_fail.txt](https://github.com/influxdata/influxdb_iox/files/8790969/next_fail.txt)). It fails immediately at step 2 (the first validation that `table_5` has data.




```shell
2022-05-27T17:38:18.315508Z  INFO test_helpers_end_to_end::steps: ====Begin running query: select * from table_5
thread 'end_to_end_cases::querier::multi_ingester::basic_multi_ingesters' panicked at 'assertion failed: `(left == right)`
  left: `["+------+------+--------------------------------+-----+", "| tag1 | tag2 | time                           | val |", "+------+------+--------------------------------+-----+", "| A    | B    | 1970-01-01T00:00:00.000123456Z | 5   |", "+------+------+--------------------------------+-----+"]`,
 right: `["++", "++"]`:

expected:

[
    "+------+------+--------------------------------+-----+",
    "| tag1 | tag2 | time                           | val |",
    "+------+------+--------------------------------+-----+",
    "| A    | B    | 1970-01-01T00:00:00.000123456Z | 5   |",
    "+------+------+--------------------------------+-----+",
]
actual:

[
    "++",
    "++",
]
```

Upon review of the logs, it appears that the ingesters retun no data to the querier

```text
2022-05-27T17:38:17.368702Z  INFO ioxd_common: gRPC server listening server_type=Querier
2022-05-27T17:38:17.391617Z  INFO ioxd_common: HTTP server listening server_type=Querier
2022-05-27T17:38:18.439832Z  INFO querier::table: Fetching all chunks predicate=Predicate { field_columns: None, partition_key: None, range: None, exprs: [], value_expr: [] } namespace=0525826078618535_1050534350652374 table_name=table_5
2022-05-27T17:38:18.465686Z  INFO querier::table: Ingester partitions fetched namespace=0525826078618535_1050534350652374 table_name=table_5 parquet_cache_outdated=false tombstone_cache_outdated=false max_parquet_sequence_number=None max_tombstone_sequence_number=None
2022-05-27T17:38:18.465782Z  INFO querier::table: Ingester partitions fetched namespace=0525826078618535_1050534350652374 table_name=table_5 num_ingester_partitions=0
2022-05-27T17:38:18.465905Z  INFO querier::table::state_reconciler: Reconciling  namespace=0525826078618535_1050534350652374 table_name=table_5 tombstones=[] num_parquet_files=0
2022-05-27T17:38:18.466052Z  INFO querier::table::state_reconciler: Parquet files after filtering parquet_ids=[] namespace=0525826078618535_1050534350652374 table_name=table_5
2022-05-27T17:38:18.466126Z  INFO querier::table::state_reconciler: Created parquet chunks num_chunks=0
2022-05-27T17:38:18.466186Z  INFO querier::table::state_reconciler: Final chunk count after reconcilation num_chunks=0
```

Despite claiming that the data from the write token is readable:

```
All data is readable: GetWriteInfoResponse { kafka_partition_infos: [KafkaPartitionInfo { kafka_partition_id: 1, status: Readable }, KafkaPartitionInfo { kafka_partition_id: 0, status: Readable }] }
```

I will keep digging

**Comment by alamb** [comment]
A break in the case 🕵️ 

I can reproduce this error by injecting a sleep into the ingester like this:

```diff
diff --git a/ingester/src/data.rs b/ingester/src/data.rs
index 1cf636090..24b2b2b01 100644
--- a/ingester/src/data.rs
+++ b/ingester/src/data.rs
@@ -31,7 +31,7 @@ use snafu::{OptionExt, ResultExt, Snafu};
 use std::{
     collections::{btree_map::Entry, BTreeMap},
     convert::TryFrom,
-    sync::Arc,
+    sync::Arc, time::Duration,
 };
 use uuid::Uuid;
 use write_summary::SequencerProgress;
@@ -571,6 +571,9 @@ impl NamespaceData {
                         None => self.insert_table(sequencer_id, &t, catalog).await?,
                     };
 
+                    // TEMP: Inject a pause here to simulate slow writes
+                    tokio::time::sleep(Duration::from_millis(100)).await;
+
                     let mut table_data = table_data.write().await;
                     let should_pause = table_data
                         .buffer_table_write(
```

Then it fails every time.

Preliminary analysis shows me that this is due to how the "progress" is reported by the Ingester (I wrote that code) -- basically it assumes a write is atomic, but the write is actually split across multiple tables each with its own independent lock. 

The final "readable" calculation is taken by finding the `max` ingested sequence across all tables -- so once the values for a single table from a write are written, it will effectively report the entire write as readable.

So the sequence of events looks like:
1. Write (starts) to be processed in `buffer_operation` for sequence `X` 
2. At least one table is updated
3. The querier asks for max sequence readable, and is told `X` (max across tables)
4. The querier asks for data for one of the tables that does not yet have the data from `X` and returns no results

**Comment by alamb** [comment]
https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/19838/workflows/29427bc2-8162-4adf-846a-9c9ec4d5c119/jobs/168353
