### ISSUE TITLE
Querier panics "Sorted/persisted chunk without partition id"

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#4631]
```text
level=error msg="Thread panic" panic_info="panicked at 'Sorted/persisted chunk without partition id', query/src/provider.rs:625:32" target="panic_logging" location="panic_logging/src/lib.rs:107" time=1652857442531832389
thread 'IOx Query Executor Thread' panicked at 'Sorted/persisted chunk without partition id', query/src/provider.rs:625:32
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::panicking::panic_display
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:73:5
   3: core::panicking::panic_str
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/option.rs:1852:5
   5: core::option::Option<T>::expect
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/option.rs:715:21
   6: query::provider::Deduplicater::sort_key_of_overlapped_chunks
             at ./influxdb_iox/query/src/provider.rs:625:13
   7: query::provider::Deduplicater::chunks_dedup_sort_key
             at ./influxdb_iox/query/src/provider.rs:581:21
   8: query::provider::Deduplicater::build_scan_plan
             at ./influxdb_iox/query/src/provider.rs:471:45
   9: <query::provider::ChunkTableProvider as datafusion::datasource::datasource::TableProvider>::scan::{{closure}}
             at ./influxdb_iox/query/src/provider.rs:285:20
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  11: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/future.rs:123:9
  12: datafusion::physical_plan::planner::DefaultPhysicalPlanner::create_initial_plan::{{closure}}
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/5c89c3b/datafusion/core/src/physical_plan/planner.rs:390:64
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  14: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/future.rs:123:9
  15: datafusion::physical_plan::planner::DefaultPhysicalPlanner::create_initial_plan::{{closure}}
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/5c89c3b/datafusion/core/src/physical_plan/planner.rs:675:88
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  17: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/future.rs:123:9
  18: datafusion::physical_plan::planner::DefaultPhysicalPlanner::create_initial_plan::{{closure}}
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/5c89c3b/datafusion/core/src/physical_plan/planner.rs:726:88
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  20: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/future.rs:123:9
  21: datafusion::physical_plan::planner::DefaultPhysicalPlanner::create_initial_plan::{{closure}}
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/5c89c3b/datafusion/core/src/physical_plan/planner.rs:621:84
  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  23: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/future.rs:123:9
  24: <datafusion::physical_plan::planner::DefaultPhysicalPlanner as datafusion::physical_plan::planner::PhysicalPlanner>::create_physical_plan::{{closure}}
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/5c89c3b/datafusion/core/src/physical_plan/planner.rs:327:70
  25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  26: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/future.rs:123:9
  27: <query::exec::context::IOxQueryPlanner as datafusion::execution::context::QueryPlanner>::create_physical_plan::{{closure}}
             at ./influxdb_iox/query/src/exec/context.rs:83:63
  28: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  29: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/future.rs:123:9
  30: datafusion::execution::context::SessionState::create_physical_plan::{{closure}}
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/5c89c3b/datafusion/core/src/execution/context.rs:1418:58
  31: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  32: datafusion::execution::context::SessionContext::create_physical_plan::{{closure}}
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/5c89c3b/datafusion/core/src/execution/context.rs:879:56
  33: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  34: query::exec::context::IOxSessionContext::prepare_plan::{{closure}}
             at ./influxdb_iox/query/src/exec/context.rs:295:66
  35: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  36: query::exec::context::IOxSessionContext::to_series_and_groups::{{closure}}::{{closure}}::{{closure}}
             at ./influxdb_iox/query/src/exec/context.rs:403:64
  37: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  38: executor::DedicatedExecutor::spawn::{{closure}}
             at ./influxdb_iox/executor/src/lib.rs:232:35
  39: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  40: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/future.rs:123:9
  41: executor::Task::run::{{closure}}::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/macros/select.rs:507:49
  42: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/future/poll_fn.rs:38:9
  43: executor::Task::run::{{closure}}
             at ./influxdb_iox/executor/src/lib.rs:43:9
  44: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  45: executor::DedicatedExecutor::new::{{closure}}::{{closure}}::{{closure}}
             at ./influxdb_iox/executor/src/lib.rs:194:35
  46: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  47: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.34/src/instrument.rs:272:9
  48: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/core.rs:165:17
  49: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/loom/std/unsafe_cell.rs:14:9
  50: tokio::runtime::task::core::CoreStage<T>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/core.rs:155:13
  51: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:470:19
  52: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panic/unwind_safe.rs:271:9
  53: std::panicking::try::do_call
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  54: std::panicking::try
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  55: std::panic::catch_unwind
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  56: tokio::runtime::task::harness::poll_future
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:458:18
  57: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:104:27
  58: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:57:15
  59: tokio::runtime::task::raw::RawTask::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/raw.rs:84:18
  60: tokio::runtime::task::LocalNotified<S>::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/mod.rs:376:9
  61: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:431:13
  62: tokio::coop::with_budget::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:102:9
  63: std::thread::local::LocalKey<T>::try_with
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/local.rs:413:16
  64: std::thread::local::LocalKey<T>::with
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/local.rs:389:9
  65: tokio::coop::with_budget
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:95:5
  66: tokio::coop::budget
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:72:5
  67: tokio::runtime::thread_pool::worker::Context::run_task
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:430:9
  68: tokio::runtime::thread_pool::worker::Context::run
  69: tokio::runtime::thread_pool::worker::run::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:382:17
  70: tokio::macros::scoped_tls::ScopedKey<T>::set
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/macros/scoped_tls.rs:61:9
  71: tokio::runtime::thread_pool::worker::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:379:5
  72: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:358:45
  73: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/blocking/task.rs:42:21
  74: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.34/src/instrument.rs:272:9
  75: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/core.rs:165:17
  76: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/loom/std/unsafe_cell.rs:14:9
  77: tokio::runtime::task::core::CoreStage<T>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/core.rs:155:13
  78: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:470:19
  79: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panic/unwind_safe.rs:271:9
  80: std::panicking::try::do_call
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  81: std::panicking::try
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  82: std::panic::catch_unwind
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  83: tokio::runtime::task::harness::poll_future
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:458:18
  84: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:104:27
  85: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:57:15
  86: tokio::runtime::task::raw::RawTask::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/raw.rs:84:18
  87: tokio::runtime::task::UnownedTask<S>::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/mod.rs:413:9
  88: tokio::runtime::blocking::pool::Task::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/blocking/pool.rs:91:9
  89: tokio::runtime::blocking::pool::Inner::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/blocking/pool.rs:325:17
  90: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/blocking/pool.rs:300:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by alamb** [comment]
This is code introduced in https://github.com/influxdata/influxdb_iox/pull/4360 from @NGA-TRAN

**Comment by crepererum** [comment]
I've managed to build a regression test locally. Working on a fix now.
