### ISSUE TITLE
Pulling partition to local catalog corrupts metadata

### ISSUE THREAD

**Issue by domodwyer** [influxdata/influxdb_iox#4728]
After running something similar to:

```console
$ cargo run -- remote partition pull --catalog-dsn="$INFLUXDB_IOX_CATALOG_DSN" --object-store=file --data-dir=./dump "namespace" "table" "partition-key"
```

The compactor panics with a `parquet metadata broken` message (full message / stack below).

<details><summary>
Stack trace
</summary>

```
thread 'tokio-runtime-worker' panicked at 'parquet metadata broken: ZstdDecodeFailure { source: Custom { kind: UnexpectedEof, error: "incomplete frame" } }', parquet_file/src/chunk.rs:199:58
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/result.rs:1785:5
   3: core::result::Result<T,E>::expect
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/result.rs:1035:23
   4: parquet_file::chunk::DecodedParquetFile::new
             at ./parquet_file/src/chunk.rs:199:32
   5: compactor::utils::ParquetFileWithTombstone::iox_metadata
             at ./compactor/src/utils.rs:130:36
   6: compactor::compact::Compactor::compact::{{closure}}
             at ./compactor/src/compact.rs:693:32
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
   8: compactor::compact::Compactor::compact_partition::{{closure}}
             at ./compactor/src/compact.rs:485:58
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  10: compactor::handler::run_compactor::{{closure}}::{{closure}}
             at ./compactor/src/handler.rs:207:88
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  12: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/future.rs:124:9
  13: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/core.rs:165:17
  14: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/loom/std/unsafe_cell.rs:14:9
  15: tokio::runtime::task::core::CoreStage<T>::poll
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/core.rs:155:13
  16: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:470:19
  17: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panic/unwind_safe.rs:271:9
  18: std::panicking::try::do_call
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
  19: ___rust_try
  20: std::panicking::try
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
  21: std::panic::catch_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
  22: tokio::runtime::task::harness::poll_future
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:458:18
  23: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:104:27
  24: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:57:15
  25: tokio::runtime::task::raw::poll
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/raw.rs:144:5
  26: tokio::runtime::task::raw::RawTask::poll
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/raw.rs:84:18
  27: tokio::runtime::task::LocalNotified<S>::run
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/mod.rs:376:9
  28: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:431:13
  29: tokio::coop::with_budget::{{closure}}
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:102:9
  30: std::thread::local::LocalKey<T>::try_with
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/local.rs:442:16
  31: std::thread::local::LocalKey<T>::with
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/local.rs:418:9
  32: tokio::coop::with_budget
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:95:5
  33: tokio::coop::budget
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:72:5
  34: tokio::runtime::thread_pool::worker::Context::run_task
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:430:9
  35: tokio::runtime::thread_pool::worker::Context::run
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:397:24
  36: tokio::runtime::thread_pool::worker::run::{{closure}}
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:382:17
  37: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/macros/scoped_tls.rs:61:9
  38: tokio::runtime::thread_pool::worker::run
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:379:5
  39: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:358:45
  40: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/blocking/task.rs:42:21
  41: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/core.rs:165:17
  42: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/loom/std/unsafe_cell.rs:14:9
  43: tokio::runtime::task::core::CoreStage<T>::poll
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/core.rs:155:13
  44: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:470:19
  45: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panic/unwind_safe.rs:271:9
  46: std::panicking::try::do_call
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
  47: ___rust_try
  48: std::panicking::try
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
  49: std::panic::catch_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
  50: tokio::runtime::task::harness::poll_future
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:458:18
  51: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:104:27
  52: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:57:15
  53: tokio::runtime::task::raw::poll
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/raw.rs:144:5
  54: tokio::runtime::task::raw::RawTask::poll
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/raw.rs:84:18
  55: tokio::runtime::task::UnownedTask<S>::run
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/mod.rs:413:9
  56: tokio::runtime::blocking::pool::Task::run
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/blocking/pool.rs:91:9
  57: tokio::runtime::blocking::pool::Inner::run
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/blocking/pool.rs:325:17
  58: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /Users/dom/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/blocking/pool.rs:300:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
</details>

**Comment by alamb** [comment]
Proposed PR to "fix": https://github.com/influxdata/influxdb_iox/pull/7688
