### ISSUE TITLE
Panic: "Primary key column(s) found that don't appear in the catalog sort key" found in iox-shared-compactor-3-0

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#4762]
Only happen in `iox-shared-compactor-3-0`

```
level=error msg="Thread panic" panic_info="panicked at 'Primary key column(s) found that don't appear in the catalog sort key: [[\"tatraffic_vnstat_live_30s_rx,host\", \"taupgradesavail_apt,host\"]]', schema/src/sort.rs:217:13" target="panic_logging" location="panic_logging/src/lib.rs:107" time=1654095960183115430
thread 'tokio-runtime-worker' panicked at 'Primary key column(s) found that don't appear in the catalog sort key: [["tatraffic_vnstat_live_30s_rx,host", "taupgradesavail_apt,host"]]', schema/src/sort.rs:217:13

level=error msg="Thread panic" panic_info="panicked at 'Primary key column(s) found that don't appear in the catalog sort key: [[\"tatraffic_vnstat_live_30s_rx,host\", \"taupgradesavail_apt,host\"]]', schema/src/sort.rs:217:13" target="panic_logging" location="panic_logging/src/lib.rs:107" time=1654095960185830698
thread 'tokio-runtime-worker' panicked at 'Primary key column(s) found that don't appear in the catalog sort key: [["tatraffic_vnstat_live_30s_rx,host", "taupgradesavail_apt,host"]]', schema/src/sort.rs:217:13

level=error msg="Thread panic" panic_info="panicked at 'Primary key column(s) found that don't appear in the catalog sort key: [[\"tartraffic_vnstat_live_30s_rx,host\", \"tarupgradesavail_apt,host\", \"tatraffic_vnstat_live_30s_rx,host\", \"taupgradesavail_apt,host\"]]', schema/src/sort.rs:217:13" target="panic_logging" location="panic_logging/src/lib.rs:107" time=1654095960525857724
thread 'tokio-runtime-worker' panicked at 'Primary key column(s) found that don't appear in the catalog sort key: [["tartraffic_vnstat_live_30s_rx,host", "tarupgradesavail_apt,host", "tatraffic_vnstat_live_30s_rx,host", "taupgradesavail_apt,host"]]', schema/src/sort.rs:217:13

level=error msg="Thread panic" panic_info="panicked at 'Primary key column(s) found that don't appear in the catalog sort key: [[\"tatraffic_vnstat_live_30s_rx,host\", \"taupgradesavail_apt,host\", \"tawan_rx_bytes,host\", \"tawan_tx_bytes,host\"]]', schema/src/sort.rs:217:13" target="panic_logging" location="panic_logging/src/lib.rs:107" time=1654095960531400333
thread 'tokio-runtime-worker' panicked at 'Primary key column(s) found that don't appear in the catalog sort key: [["tatraffic_vnstat_live_30s_rx,host", "taupgradesavail_apt,host", "tawan_rx_bytes,host", "tawan_tx_bytes,host"]]', schema/src/sort.rs:217:13

level=error msg="Thread panic" panic_info="panicked at 'Primary key column(s) found that don't appear in the catalog sort key: [[\"tartraffic_vnstat_live_30s_rx,host\", \"tarupgradesavail_apt,host\"]]', schema/src/sort.rs:217:13" target="panic_logging" location="panic_logging/src/lib.rs:107" time=1654095960535641050
thread 'tokio-runtime-worker' panicked at 'Primary key column(s) found that don't appear in the catalog sort key: [["tartraffic_vnstat_live_30s_rx,host", "tarupgradesavail_apt,host"]]', schema/src/sort.rs:217:13

level=error msg="Thread panic" panic_info="panicked at 'Primary key column(s) found that don't appear in the catalog sort key: [[\"tardocker_netstat_combined,target\", \"tartraffic_vnstat_live_30s_rx,host\", \"tarupgradesavail_apt,host\"]]', schema/src/sort.rs:217:13" target="panic_logging" location="panic_logging/src/lib.rs:107" time=1654095960560062547
thread 'tokio-runtime-worker' panicked at 'Primary key column(s) found that don't appear in the catalog sort key: [["tardocker_netstat_combined,target", "tartraffic_vnstat_live_30s_rx,host", "tarupgradesavail_apt,host"]]', schema/src/sort.rs:217:13



```

**Comment by NGA-TRAN** [comment]
After reviewing the code, I am confident #4729 does not fix this. This is still a bug

**Comment by NGA-TRAN** [comment]
I think the problem is comma (,) in the name. 

The one of the column name in the panics include comma such as `tatraffic_vnstat_live_30s_rx,host`

Let us find its table_id
```text 
select * from column_name where name like '%tatraffic_vnstat_live_30s_rx,host%';
   id   | table_id |               name                | column_type 
--------+----------+-----------------------------------+-------------
 632251 |    47338 | tatraffic_vnstat_live_30s_rx,host |           7
```
Now let use table ID to find its partition's sort key

```text
select partition_key, sort_key from partition where table_id = 47338 and sort_key like '%tatraffic_vnstat_live_30s_rx,host%'
iox_catalog-# ;
 partition_key |                                                                          sort_key                                                                          
---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------
 2022-05-11    | taupgradesavail_apt,host,host,tatraffic_vnstat_live_30s_rx,host,target,time
 2022-05-12    | taupgradesavail_apt,host,tatraffic_vnstat_live_30s_rx,target,tatraffic_vnstat_live_30s_rx,host,taupgradesavail_apt,host,time
 2022-05-13    | tatraffic_vnstat_live_30s_rx,host,taupgradesavail_apt,tawan_rx_bytes,tawan_tx_bytes,target,tatraffic_vnstat_live_30s_rx,host,taupgradesavail_apt,host,time
 2022-05-14    | taupgradesavail_apt,host,tatraffic_vnstat_live_30s_rx,target,tatraffic_vnstat_live_30s_rx,host,taupgradesavail_apt,host,time
 2022-05-15    | tatraffic_vnstat_live_30s_rx,host,taupgradesavail_apt,target,tatraffic_vnstat_live_30s_rx,host,taupgradesavail_apt,host,time
(5 rows)
```

The sort key of that corresponding column is `tatraffic_vnstat_live_30s_rx,host,taupgradesavail_apt,tawan_rx_bytes,tawan_tx_bytes,target,tatraffic_vnstat_live_30s_rx,host,taupgradesavail_apt,host,time` 
When we parse that sort key, we split their column name by comma ([see here](https://github.com/influxdata/influxdb_iox/blob/1472ec272ffad796e20bd9d890a73d561f3c8160/data_types/src/lib.rs#L682)) and lead to panic of no longer match column [here](https://github.com/influxdata/influxdb_iox/blob/1472ec272ffad796e20bd9d890a73d561f3c8160/schema/src/sort.rs#L216).

**Comment by domodwyer** [comment]
I would second 2 (and not 1) - storing an array of column names as an [explicit array of columns](https://www.postgresql.org/docs/current/arrays.html) sounds like a sensible solution to me, our PG/sqlx/catalog abstraction fully supports it and it avoids any potentially ambiguous encoding / decoding steps to effectively do the same thing. It also becomes easier to query against, should we ever need to look up values of `sort_key`.

We can modify the `partition` table to be something like:

```sql
CREATE TABLE IF NOT EXISTS partition (
    sort_key TEXT[],

    # ...other columns...
);
```
