### ISSUE TITLE
influxrpc: fluxtest error `Schema error: Schema contains duplicate unqualified field name 'IsNull-Column-swap.host'`

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#4800]
This failure comes from the fluxtest suite:

#  Input:
```

input = "
#datatype,string,long,dateTime:RFC3339,string,string,string,double
#group,false,false,false,true,true,true,false
#default,_result,,,,,,
,result,table,_time,_measurement,host,_field,_value
,,0,2018-05-22T19:53:26Z,system,host.local,load1,1.83
,,0,2018-05-22T19:53:36Z,system,host.local,load1,1.72
,,0,2018-05-22T19:53:46Z,system,host.local,load1,1.74
,,0,2018-05-22T19:53:56Z,system,host.local,load1,1.63
,,0,2018-05-22T19:54:06Z,system,host.local,load1,1.91
,,0,2018-05-22T19:54:16Z,system,host.local,load1,1.84

,,1,2018-05-22T19:53:26Z,sys,host.local,load3,1.98
,,1,2018-05-22T19:53:36Z,sys,host.local,load3,1.97
,,1,2018-05-22T19:53:46Z,sys,host.local,load3,1.97
,,1,2018-05-22T19:53:56Z,sys,host.local,load3,1.96
,,1,2018-05-22T19:54:06Z,sys,host.local,load3,1.98
,,1,2018-05-22T19:54:16Z,sys,host.local,load3,1.97

,,2,2018-05-22T19:53:26Z,system,host.local,load5,1.95
,,2,2018-05-22T19:53:36Z,system,host.local,load5,1.92
,,2,2018-05-22T19:53:46Z,system,host.local,load5,1.92
,,2,2018-05-22T19:53:56Z,system,host.local,load5,1.89
,,2,2018-05-22T19:54:06Z,system,host.local,load5,1.94
,,2,2018-05-22T19:54:16Z,system,host.local,load5,1.93

,,3,2018-05-22T19:53:26Z,var,host.local,load3,91.98
,,3,2018-05-22T19:53:36Z,var,host.local,load3,91.97
,,3,2018-05-22T19:53:46Z,var,host.local,load3,91.97
,,3,2018-05-22T19:53:56Z,var,host.local,load3,91.96
,,3,2018-05-22T19:54:06Z,var,host.local,load3,91.98
,,3,2018-05-22T19:54:16Z,var,host.local,load3,91.97

,,4,2018-05-22T19:53:26Z,swap,host.global,used_percent,82.98
,,4,2018-05-22T19:53:36Z,swap,host.global,used_percent,82.59
,,4,2018-05-22T19:53:46Z,swap,host.global,used_percent,82.59
,,4,2018-05-22T19:53:56Z,swap,host.global,used_percent,82.59
,,4,2018-05-22T19:54:06Z,swap,host.global,used_percent,82.59
,,4,2018-05-22T19:54:16Z,swap,host.global,used_percent,82.64

#datatype,string,long,dateTime:RFC3339,string,string,string,double
#group,false,false,false,true,true,true,false
#default,_result,,,,,,
,result,table,_time,_measurement,loc,_field,_value
,,0,2018-05-22T19:53:26Z,locale,en,lat,37.09
,,0,2018-05-22T19:53:36Z,locale,en,lat,37.10
,,0,2018-05-22T19:53:46Z,locale,en,lat,37.08
"
```

# Query:
```
2022-06-07T17:45:42.398679Z  INFO service_grpc_influxrpc::service: read filter db_name=54425547585a6420_dfc574f9716be050 req.range=Some(TimestampRange { start: 1514764800000000000, end: 1546300800000000000 }) predicate=((TagRef:_m[0x00] != "system") AND ((TagRef:host == "host.local") Or (TagRef:host == "")))
```

# Expected output:
```
    want = csv.from(csv: "#datatype,string,long,dateTime:RFC3339,string,string,string,double
#group,false,false,false,true,true,true,false
#default,_result,,,,,,
,result,table,_time,_measurement,host,_field,_value
,,1,2018-05-22T19:53:26Z,sys,host.local,load3,1.98
,,1,2018-05-22T19:53:36Z,sys,host.local,load3,1.97
,,1,2018-05-22T19:53:46Z,sys,host.local,load3,1.97
,,1,2018-05-22T19:53:56Z,sys,host.local,load3,1.96
,,1,2018-05-22T19:54:06Z,sys,host.local,load3,1.98
,,1,2018-05-22T19:54:16Z,sys,host.local,load3,1.97
,,3,2018-05-22T19:53:26Z,var,host.local,load3,91.98
,,3,2018-05-22T19:53:36Z,var,host.local,load3,91.97
,,3,2018-05-22T19:53:46Z,var,host.local,load3,91.97
,,3,2018-05-22T19:53:56Z,var,host.local,load3,91.96
,,3,2018-05-22T19:54:06Z,var,host.local,load3,91.98
,,3,2018-05-22T19:54:16Z,var,host.local,load3,91.97

#datatype,string,long,dateTime:RFC3339,string,string,string,double
#group,false,false,false,true,true,true,false
#default,_result,,,,,,
,result,table,_time,_measurement,loc,_field,_value
,,0,2018-05-22T19:53:26Z,locale,en,lat,37.09
,,0,2018-05-22T19:53:36Z,locale,en,lat,37.10
,,0,2018-05-22T19:53:46Z,locale,en,lat,37.08
")

```

# Actual output 
An error:

```
	multi_measure_negation...fail: query error: rpc error: code = InvalidArgument desc = Error running series plans for database '54425547585a6420_dfc574f9716be050': Schema error: Schema contains duplicate unqualified field name 'IsNull-Column-swap.host'
```

Logs:
```
2022-06-07T17:45:42.543927Z ERROR service_grpc_influxrpc::service: Error Running series set plan: FilteringSeries { db_name: "54425547585a6420_dfc574f9716be050", source: SchemaError(DuplicateUnqualifiedField { name: "IsNull-Column-swap.host" }) }
2022-06-07T17:45:42.543979Z ERROR service_grpc_influxrpc::service: Error handling gRPC request: Error running series plans for database '54425547585a6420_dfc574f9716be050': Schema error: Schema contains duplicate unqualified field name 'IsNull-Column-swap.host'
2022-06-07T17:45:42.545382Z  WARN executor: Spawned task output ignored: receiver dropped
```

**Comment by alamb** [comment]
Here is a reproducer:

```diff
diff --git a/query_tests/src/influxrpc/read_filter.rs b/query_tests/src/influxrpc/read_filter.rs
index c760da675..0ec4d9e73 100644
--- a/query_tests/src/influxrpc/read_filter.rs
+++ b/query_tests/src/influxrpc/read_filter.rs
@@ -3,8 +3,8 @@ use std::sync::Arc;
 
 #[cfg(test)]
 use crate::scenarios::{
-    DbScenario, DbSetup, TwoMeasurements, TwoMeasurementsManyFields, TwoMeasurementsWithDelete,
-    TwoMeasurementsWithDeleteAll,
+    DbScenario, DbSetup, TwoMeasurements, TwoMeasurementsDifferentTags, TwoMeasurementsManyFields,
+    TwoMeasurementsWithDelete, TwoMeasurementsWithDeleteAll,
 };
 use crate::{
     db::AbstractDb,
@@ -15,7 +15,7 @@ use crate::{
         TwoMeasurementsMultiSeriesWithDelete, TwoMeasurementsMultiSeriesWithDeleteAll,
     },
 };
-use datafusion::logical_plan::{col, lit, when};
+use datafusion::logical_plan::{col, lit, when, Expr};
 use iox_query::frontend::influxrpc::InfluxRpcPlanner;
 use predicate::rpc_predicate::InfluxRpcPredicate;
 use predicate::PredicateBuilder;
@@ -192,12 +192,7 @@ async fn test_read_filter_invalid_predicate_case() {
         // https://github.com/influxdata/influxdb_iox/issues/3635
         // model what happens when a field is treated like a tag
         // CASE WHEN system" IS NULL THEN '' ELSE system END = 5;
-        .add_expr(
-            when(col("system").is_null(), lit(""))
-                .otherwise(col("system"))
-                .unwrap()
-                .eq(lit(5i32)),
-        )
+        .add_expr(make_empty_tag_ref_expr("system").eq(lit(5i32)))
         .build();
     let predicate = InfluxRpcPredicate::new(None, predicate);
 
@@ -783,6 +778,23 @@ async fn test_read_filter_on_field_single_measurement() {
     run_read_filter_test_case(TwoMeasurementsManyFields {}, predicate, expected_results).await;
 }
 
+#[tokio::test]
+async fn test_read_filter_multi_negation() {
+    // reproducer for https://github.com/influxdata/influxdb_iox/issues/4800
+    test_helpers::maybe_start_logging();
+
+    let host = make_empty_tag_ref_expr("host");
+    let p1 = col("_measurement")
+        .not_eq(lit("system"))
+        .and(host.clone().eq(lit("host.local")).or(host.eq(lit(""))));
+    let predicate = PredicateBuilder::default().add_expr(p1).build();
+    let predicate = InfluxRpcPredicate::new(None, predicate);
+
+    let expected_results = vec!["FOO"];
+
+    run_read_filter_test_case(TwoMeasurementsDifferentTags {}, predicate, expected_results).await;
+}
+
 #[tokio::test]
 async fn test_read_filter_on_field_multi_measurement() {
     test_helpers::maybe_start_logging();
@@ -812,3 +824,13 @@ async fn test_read_filter_on_field_multi_measurement() {
 
     run_read_filter_test_case(TwoMeasurementsManyFields {}, predicate, expected_results).await;
 }
+
+/// https://github.com/influxdata/influxdb_iox/issues/3635
+/// model what happens when a field is treated like a tag compared to ''
+///
+/// CASE WHEN system" IS NULL THEN '' ELSE system END
+fn make_empty_tag_ref_expr(tag_name: &str) -> Expr {
+    when(col(tag_name).is_null(), lit(""))
+        .otherwise(col(tag_name))
+        .unwrap()
+}
diff --git a/query_tests/src/scenarios/library.rs b/query_tests/src/scenarios/library.rs
index a2ce957d7..7af5c6e97 100644
--- a/query_tests/src/scenarios/library.rs
+++ b/query_tests/src/scenarios/library.rs
@@ -1348,3 +1348,52 @@ impl DbSetup for TwoChunksMissingColumns {
         .await
     }
 }
+
+#[derive(Debug)]
+pub struct TwoMeasurementsDifferentTags {}
+#[async_trait]
+impl DbSetup for TwoMeasurementsDifferentTags {
+    async fn make(&self) -> Vec<DbScenario> {
+        let partition_key = "2021-01-01T00";
+
+        let lp = r#"
+system,host=host.local load1=1.83,load5=1.95 1609459201000000001
+system,host=host.local load1=1.72,load5=1.92 1609459201000000002
+system,host=host.local load1=1.74,load5=1.92 1609459201000000003
+system,host=host.local load1=1.63,load5=1.89 1609459201000000004
+system,host=host.local load1=1.91,load5=1.94 1609459201000000005
+system,host=host.local load1=1.84,load5=1.93 1609459201000000006
+
+sys,host=host.local load3=1.98 1609459201000000001
+sys,host=host.local load3=1.97 1609459201000000002
+sys,host=host.local load3=1.97 1609459201000000003
+sys,host=host.local load3=1.96 1609459201000000004
+sys,host=host.local load3=1.98 1609459201000000005
+sys,host=host.local load3=1.97 1609459201000000006
+
+var,host=host.local load3=91.98 1609459201000000001
+var,host=host.local load3=91.97 1609459201000000002
+var,host=host.local load3=91.97 1609459201000000003
+var,host=host.local load3=91.96 1609459201000000004
+var,host=host.local load3=91.98 1609459201000000005
+var,host=host.local load3=91.97 1609459201000000006
+
+swap,host=host.global used_percent=82.98 1609459201000000001
+swap,host=host.global used_percent=82.59 1609459201000000002
+swap,host=host.global used_percent=82.59 1609459201000000003
+swap,host=host.global used_percent=82.59 1609459201000000004
+swap,host=host.global used_percent=82.59 1609459201000000005
+swap,host=host.global used_percent=82.64 1609459201000000006
+
+locale,loc=en lat=37.09 1609459201000000001
+locale,loc=en lat=37.10 1609459201000000001
+locale,loc=en lat=37.08 1609459201000000001
+"#
+        .trim()
+        .split("\n")
+        .collect();
+
+        // no delete predicates
+        all_scenarios_for_one_chunk(vec![], vec![], lp, "na", partition_key).await
+    }
+}

```

It fails like this:

```
failures:

---- influxrpc::read_filter::test_read_filter_multi_negation stdout ----
Running scenario 'Chunk stage=Parquet partition=2021-01-01T00'
Predicate: 'InfluxRpcPredicate {
    table_names: None,
    inner: Predicate {
        field_columns: None,
        partition_key: None,
        range: None,
        exprs: [
            #_measurement != Utf8("system") AND CASE WHEN #host IS NULL THEN Utf8("") ELSE #host END = Utf8("host.local") OR CASE WHEN #host IS NULL THEN Utf8("") ELSE #host END = Utf8(""),
        ],
        value_expr: [],
    },
}'
thread 'influxrpc::read_filter::test_read_filter_multi_negation' panicked at 'Unexpected error running read filter: "Schema error: Schema contains duplicate unqualified field name 'IsNull-Column-sys.host'"', query_tests/src/influxrpc/read_filter.rs:44:14

```

I am working to cut the reproducer down now

**Comment by alamb** [comment]
Here is a much smaller reproducer with the same symptom:
```rust

#[tokio::test]
async fn test_read_filter_multi_negation() {
    // reproducer for https://github.com/influxdata/influxdb_iox/issues/4800
    test_helpers::maybe_start_logging();

    let host = make_empty_tag_ref_expr("host");
    let p1 = host.clone().eq(lit("server01")).or(host.eq(lit("")));
    let predicate = PredicateBuilder::default().add_expr(p1).build();
    let predicate = InfluxRpcPredicate::new(None, predicate);

    let expected_results = vec!["FOO"];

    run_read_filter_test_case(EndToEndTest {}, predicate, expected_results).await;
}
```

**Comment by alamb** [comment]
The core error appears to be in the `common_subexpr_eliminate.rs` pass in datafusion. Switching there to see if I can get a self contained reproducer in DataFusion

```
thread 'IOx Query Executor Thread' panicked at 'Where is the erorr??', /Users/alamb/Software/arrow-datafusion/datafusion/common/src/dfschema.rs:78:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: datafusion_common::dfschema::DFSchema::new_with_metadata
             at /Users/alamb/Software/arrow-datafusion/datafusion/common/src/dfschema.rs:78:17
   3: datafusion_optimizer::common_subexpr_eliminate::build_project_plan
             at /Users/alamb/Software/arrow-datafusion/datafusion/optimizer/src/common_subexpr_eliminate.rs:289:22
   4: datafusion_optimizer::common_subexpr_eliminate::rewrite_expr
             at /Users/alamb/Software/arrow-datafusion/datafusion/optimizer/src/common_subexpr_eliminate.rs:334:21
   5: datafusion_optimizer::common_subexpr_eliminate::optimize
             at /Users/alamb/Software/arrow-datafusion/datafusion/optimizer/src/common_subexpr_eliminate.rs:100:45
   6: datafusion_optimizer::common_subexpr_eliminate::rewrite_expr
             at /Users/alamb/Software/arrow-datafusion/datafusion/optimizer/src/common_subexpr_eliminate.rs:332:25
   7: datafusion_optimizer::common_subexpr_eliminate::optimize
             at /Users/alamb/Software/arrow-datafusion/datafusion/optimizer/src/common_subexpr_eliminate.rs:201:45
   8: datafusion_optimizer::common_subexpr_eliminate::rewrite_expr
             at /Users/alamb/Software/arrow-datafusion/datafusion/optimizer/src/common_subexpr_eliminate.rs:332:25
   9: datafusion_optimizer::common_subexpr_eliminate::optimize
             at /Users/alamb/Software/arrow-datafusion/datafusion/optimizer/src/common_subexpr_eliminate.rs:100:45
  10: <datafusion_optimizer::common_subexpr_eliminate::CommonSubexprEliminate as datafusion_optimizer::optimizer::OptimizerRule>::optimize
             at /Users/alamb/Software/arrow-datafusion/datafusion/optimizer/src/common_subexpr_eliminate.rs:64:9
  11: datafusion_optimizer::optimizer::Optimizer::optimize
             at /Users/alamb/Software/arrow-datafusion/datafusion/optimizer/src/optimizer.rs:93:24
  12: datafusion::execution::context::SessionState::optimize
             at /Users/alamb/Software/arrow-datafusion/datafusion/core/src/execution/context.rs:1337:13
  13: datafusion::execution::context::SessionState::create_physical_plan::{{closure}}
             at /Users/alamb/Software/arrow-datafusion/datafusion/core/src/execution/context.rs:1347:28
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  15: datafusion::execution::context::SessionContext::create_physical_plan::{{closure}}
             at /Users/alamb/Software/arrow-datafusion/datafusion/core/src/execution/context.rs:886:56
  16: goop
  17: iox_query::exec::context::IOxSessionContext::prepare_plan::{{closure}}
             at /Users/alamb/Software/influxdb_iox/iox_query/src/exec/context.rs:295:66
  18: goop
  19: iox_query::exec::context::IOxSessionContext::to_series_and_groups::{{closure}}::{{closure}}::{{closure}}
             at /Users/alamb/Software/influxdb_iox/iox_query/src/exec/context.rs:403:64
  20: goop
  21: executor::DedicatedExecutor::spawn::{{closure}}
             at /Users/alamb/Software/influxdb_iox/executor/src/lib.rs:232:35
  22: goop
  23: goop
  24: goop
  25: goop
...
```

**Comment by alamb** [comment]
Well, I have an update:

The underlying issues appears to be that one of the datafusion optimizer passes (`datafusion_optimizer::common_subexpr_eliminate`), when run a second time, messes up the plan somehow.

I have found a workaround is to avoid the double optimization in IOx

I will also try and find a reproducer and fix the root cause in DataFusion
