### ISSUE TITLE
Maybe another catalog data corruption: Primary key column(s) found that don't appear in the catalog sort key

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#4869]
Log of Compactor-1 shows:

```
level=error msg="Thread panic" panic_info="panicked at 'Primary key column(s) found that don't appear in the catalog sort key: [[\"tag_description\"]]', schema/src/sort.rs:218:13" target="panic_logging" location="panic_logging/src/lib.rs:107" time=1655312827436438082
thread 'tokio-runtime-worker' panicked at 'Primary key column(s) found that don't appear in the catalog sort key: [["tag_description"]]', schema/src/sort.rs:218:13
```

Log of Compactor-2

```
level=error msg="Thread panic" panic_info="panicked at 'Primary key column(s) found that don't appear in the catalog sort key: [[\"WS_tag_mapping\", \"WS_tag_name\"]]', schema/src/sort.rs:218:13" target="panic_logging" location="panic_logging/src/lib.rs:107" time=1655319124843032746
thread 'tokio-runtime-worker' panicked at 'Primary key column(s) found that don't appear in the catalog sort key: [["WS_tag_mapping", "WS_tag_name"]]', schema/src/sort.rs:218:13

level=error msg="Thread panic" panic_info="panicked at 'Primary key column(s) found that don't appear in the catalog sort key: [[\"deviceName\"]]', schema/src/sort.rs:218:13" target="panic_logging" location="panic_logging/src/lib.rs:107" time=1655319590902592339
thread 'tokio-runtime-worker' panicked at 'Primary key column(s) found that don't appear in the catalog sort key: [["deviceName"]]', schema/src/sort.rs:218:13

level=error msg="Thread panic" panic_info="panicked at 'Primary key column(s) found that don't appear in the catalog sort key: [[\"tag_description\"]]', schema/src/sort.rs:218:13" target="panic_logging" location="panic_logging/src/lib.rs:107" time=1655319593011906233
thread 'tokio-runtime-worker' panicked at 'Primary key column(s) found that don't appear in the catalog sort key: [["tag_description"]]', schema/src/sort.rs:218:13

level=error msg="Thread panic" panic_info="panicked at 'Primary key column(s) found that don't appear in the catalog sort key: [[\"cm_stack_name\"]]', schema/src/sort.rs:218:13" target="panic_logging" location="panic_logging/src/lib.rs:107" time=1655319595284456286
thread 'tokio-runtime-worker' panicked at 'Primary key column(s) found that don't appear in the catalog sort key: [["cm_stack_name"]]', schema/src/sort.rs:218:13
```

Log of Compactor-3

```
level=debug msg="Number of columns in the merged schema to build query plan" num_cols=9 target="compactor::compact" location="compactor/src/compact.rs:710" time=1655318052018565411
thread 'tokio-runtime-worker' panicked at 'Primary key column(s) found that don't appear in the catalog sort key: [["web"]]', schema/src/sort.rs:218:13


```

**Comment by NGA-TRAN** [comment]
Confirm this is a catalog data corruption caused by catalog manual migration while Ingesters still loading data in. 

Detail of why it happens that way: 

1. Step 1 (catalog migration): a new column `sort_key_arr` was added in `partition` table.2.
2. Step 2 (catalog migration): data of `sort_key` was copied to `sort_key_arr`
3. Step 3: Ingesters load new data and update new tag columns into `sort_key`. 
4. Step 4 (catalog migration): `sort_key` was renamed to `sort_key_old`
5. Step 5: (catalog migration): `sort_key_arr` was renamed to `sort_key`
So new tag columns at step 3 were never got updated into `sort_key_arr` which is after step 5 becomes `sort_key`. I have verified this by comparing `sort_key_old` and `sort_key` for columns in the panic message as follows

These are  tags column in the panic message that could not be found in their partition sort_key:
'web'
'cm_stack_name'
'deviceName'
'WS_tag_mapping', 'WS_tag_name'
'tag_description'

Here are SQL confirm the explanation above. All of the partition was of the day of the migration

```SQL
select * from partition where table_id = 96384 and sort_key_old like '%web%' and NOT('web' = ANY(sort_key)) and sort_key != '{}' order by id;
    id    | sequencer_id | table_id | partition_key |                       sort_key_old                        |                        sort_key                         
----------+--------------+----------+---------------+-----------------------------------------------------------+---------------------------------------------------------
 24466850 |           17 |    96384 | 2022-06-10    | cli,component,device,flyAppName,flyRegion,metric,web,time | {cli,component,device,flyAppName,flyRegion,metric,time}
(1 row)


select * from partition where sort_key_old like '%cm_stack_name%' and NOT('cm_stack_name' = ANY(sort_key)) and sort_key != '{}' order by id;
    id    | sequencer_id | table_id | partition_key |                  sort_key_old                  |           sort_key            
----------+--------------+----------+---------------+------------------------------------------------+-------------------------------
 24770640 |           62 |   388295 | 2022-06-10    | host,cm_stack_name,time                        | {host,time}
 24770641 |           52 |   388298 | 2022-06-10    | host,cm_stack_name,time                        | {host,time}
 24770642 |           63 |   388296 | 2022-06-10    | host,pid_finder,result,cm_stack_name,user,time | {host,pid_finder,result,time}
 24770643 |           93 |   388294 | 2022-06-10    | host,cm_stack_name,time                        | {host,time}
 24770644 |           60 |   388293 | 2022-06-10    | host,cm_stack_name,time                        | {host,time}
 24770645 |           88 |   388292 | 2022-06-10    | host,name,cm_stack_name,time                   | {host,name,time}
 24770646 |           88 |   388297 | 2022-06-10    | host,cm_stack_name,time                        | {host,time}
 24770647 |           91 |   388300 | 2022-06-10    | event_type,cm_stack_name,time                  | {event_type,time}
 24770648 |           85 |   388301 | 2022-06-10    | host,cpu,cm_stack_name,time                    | {host,cpu,time}
(9 rows)

select * from partition where sort_key_old like '%deviceName%' and NOT('deviceName' = ANY(sort_key)) and sort_key != '{}' order by id;
    id    | sequencer_id | table_id | partition_key |      sort_key_old      |   sort_key    
----------+--------------+----------+---------------+------------------------+---------------
 24363991 |           77 |    63632 | 2022-06-10    | sensor,deviceName,time | {sensor,time}
(1 row)


select * from partition where sort_key_old like '%WS_tag_mapping%WS_tag_name%' and NOT('WS_tag_mapping' = ANY(sort_key)) and NOT('WS_tag_name' = ANY(sort_key))and sort_key != '{}' order by id;
    id    | sequencer_id | table_id | partition_key |                                                                                                                                                              sort_key_old                 
                                                                                                                                              |                                                                                                 
                                                   sort_key                                                                                                                                                    
----------+--------------+----------+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 24386285 |           96 |     9440 | 2022-06-10    | area_type,enterprise,equipment_manufacturer,equipment_name,equipment_type,equipment_uuid,line_name,line_uuid,machine_name,machine_type,machine_uuid,site_name,site_uuid,tag_address,tag_de
scription,tag_name,tag_sub_type,tag_type,tag_unit,tag_uuid,work_center_name,work_center_type,work_center_uuid,WS_tag_mapping,WS_tag_name,time | {area_type,enterprise,equipment_manufacturer,equipment_name,equipment_type,equipment_uuid,line_n
ame,line_uuid,machine_name,machine_type,machine_uuid,site_name,site_uuid,tag_address,tag_description,tag_name,tag_sub_type,tag_type,tag_unit,tag_uuid,work_center_name,work_center_type,work_center_uuid,time}
(1 row)

select * from partition where sort_key_old like '%tag_description%' and NOT('tag_description' = ANY(sort_key)) and sort_key != '{}' order by id;
    id    | sequencer_id | table_id | partition_key |                                                                                                                                                 sort_key_old                              
                                                                                                                   |                                                                                                                            
                sort_key                                                                                                                                            
----------+--------------+----------+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
 24347932 |           59 |   323760 | 2022-06-10    | area_type,enterprise,equipment_manufacturer,equipment_name,equipment_type,equipment_uuid,line_name,line_uuid,machine_name,machine_type,machine_uuid,site_name,site_uuid,tag_address,tag_na
me,tag_sub_type,tag_type,tag_unit,tag_uuid,work_center_name,work_center_type,work_center_uuid,tag_description,time | {area_type,enterprise,equipment_manufacturer,equipment_name,equipment_type,equipment_uuid,line_name,line_uuid,machine_name,
machine_type,machine_uuid,site_name,site_uuid,tag_address,tag_name,tag_sub_type,tag_type,tag_unit,tag_uuid,work_center_name,work_center_type,work_center_uuid,time}
 24375561 |           97 |   101681 | 2022-06-10    | area_type,enterprise,equipment_manufacturer,equipment_name,equipment_type,equipment_uuid,line_name,line_uuid,machine_name,machine_type,machine_uuid,site_name,site_uuid,tag_address,tag_na
me,tag_sub_type,tag_type,tag_unit,tag_uuid,work_center_name,work_center_type,work_center_uuid,tag_description,time | {area_type,enterprise,equipment_manufacturer,equipment_name,equipment_type,equipment_uuid,line_name,line_uuid,machine_name,
machine_type,machine_uuid,site_name,site_uuid,tag_address,tag_name,tag_sub_type,tag_type,tag_unit,tag_uuid,work_center_name,work_center_type,work_center_uuid,time}
(2 rows)
```

**Comment by NGA-TRAN** [comment]
Here are the scrip to update `sort_key` for the above cases to match with their sort_key_old. The last line is to also update **empty** `sort_key` their corresponding `sort_key_old` is not null which is the same problem.

```SQL
update partition set sort_key=string_to_array(sort_key_old, ',') where id in (select id from partition where table_id = 96384 and sort_key_old like '%web%' and NOT('web' = ANY(sort_key)));

update partition set sort_key=string_to_array(sort_key_old, ',') where id in (select id from partition where sort_key_old like '%cm_stack_name%' and NOT('cm_stack_name' = ANY(sort_key)));

update partition set sort_key=string_to_array(sort_key_old, ',') where id in (select id from partition where sort_key_old like '%deviceName%' and NOT('deviceName' = ANY(sort_key)));

update partition set sort_key=string_to_array(sort_key_old, ',') where id in (select id from partition where sort_key_old like '%WS_tag_mapping%WS_tag_name%' and NOT('WS_tag_mapping' = ANY(sort_key)) and NOT('WS_tag_name' = ANY(sort_key)));

update partition set sort_key=string_to_array(sort_key_old, ',') where id in (select id from partition where sort_key_old like '%tag_description%' and NOT('tag_description' = ANY(sort_key)));

update partition set sort_key=string_to_array(sort_key_old, ',') where id in (select id from partition where sort_key_old is not null and sort_key = '{}');
```

**Comment by NGA-TRAN** [comment]
After overnight runs, the Compactors no longer hit panics due to this problem. Close this ticket
