### ISSUE TITLE
End to end test flaky: Thread panic panic_info=panicked at 'partition sort key should be set when a parquet file exists', querier/src/chunk/mod.rs:408:14

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#5090]
Sometimes this end to end test is failing:
```
failures:
    end_to_end_cases::querier::multi_ingester::basic_multi_ingesters
```

```
2022-07-11T13:07:48.117800Z DEBUG querier::table: Fetching all chunks predicate=Predicate { field_columns: None, range: None, exprs: [], value_expr: [] } namespace=3291820968610966_6288833622983336 table_name=table_6
2022-07-11T13:07:48.118030Z DEBUG querier::ingester::flight_client: Reusing connection to ingester ingester_address=http://127.0.0.1:8147
2022-07-11T13:07:48.118080Z DEBUG querier::ingester::flight_client: Sending request to ingester ingester_addr=http://127.0.0.1:8147 request=IngesterQueryRequest { namespace: "3291820968610966_6288833622983336", table: "table_6", columns: ["tag1", "tag2", "time", "val"], predicate: Some(Predicate { field_columns: None, range: None, exprs: [], value_expr: [] }) }
2022-07-11T13:07:48.118393Z DEBUG tower::buffer::worker: service.ready=true processing request
2022-07-11T13:07:48.118884Z DEBUG Connection{peer=Client}: h2::codec::framed_write: send frame=Headers { stream_id: StreamId(13), flags: (0x4: END_HEADERS) }
2022-07-11T13:07:48.119091Z DEBUG Connection{peer=Client}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(13) }
2022-07-11T13:07:48.119211Z DEBUG Connection{peer=Client}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(13), flags: (0x1: END_STREAM) }
2022-07-11T13:07:48.125013Z DEBUG Connection{peer=Client}: h2::codec::framed_read: received frame=Headers { stream_id: StreamId(13), flags: (0x4: END_HEADERS) }
2022-07-11T13:07:48.126187Z DEBUG Connection{peer=Client}: h2::codec::framed_read: received frame=Data { stream_id: StreamId(13) }
2022-07-11T13:07:48.126307Z DEBUG Connection{peer=Client}: h2::codec::framed_read: received frame=Data { stream_id: StreamId(13) }
2022-07-11T13:07:48.127628Z DEBUG Connection{peer=Client}: h2::codec::framed_read: received frame=Data { stream_id: StreamId(13) }
2022-07-11T13:07:48.127783Z DEBUG Connection{peer=Client}: h2::codec::framed_read: received frame=Headers { stream_id: StreamId(13), flags: (0x5: END_HEADERS | END_STREAM) }
2022-07-11T13:07:48.130469Z  INFO querier::ingester: Time spent in ingester predicate=Predicate { field_columns: None, range: None, exprs: [], value_expr: [] } namespace=3291820968610966_6288833622983336 table_name=table_6 ingester_duration=12.518677ms status="success"
2022-07-11T13:07:48.130614Z DEBUG querier::table: Ingester partitions fetched namespace=3291820968610966_6288833622983336 table_name=table_6 parquet_cache_outdated=false tombstone_cache_outdated=false max_parquet_sequence_number=None max_tombstone_sequence_number=None
2022-07-11T13:07:48.130653Z DEBUG querier::table: Ingester partitions fetched namespace=3291820968610966_6288833622983336 table_name=table_6 num_ingester_partitions=1
2022-07-11T13:07:48.132841Z ERROR panic_logging: Thread panic panic_info=panicked at 'partition sort key should be set when a parquet file exists', querier/src/chunk/mod.rs:408:14
thread 'IOx Query Executor Thread' panicked at 'partition sort key should be set when a parquet file exists', querier/src/chunk/mod.rs:408:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/option.rs:1854:5
   5: core::option::Option<T>::expect
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/option.rs:718:21
   6: querier::chunk::ChunkAdapter::chunk_parts::{{closure}}
             at /home/rust/project/querier/src/chunk/mod.rs:405:38
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
   8: querier::chunk::ChunkAdapter::new_parquet_chunk::{{closure}}
             at /home/rust/project/querier/src/chunk/mod.rs:315:68
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
  10: querier::table::QuerierTable::chunks::{{closure}}::{{closure}}::{{closure}}
             at /home/rust/project/querier/src/table/mod.rs:177:26
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
  12: <futures_util::stream::stream::filter_map::FilterMap<St,Fut,F> as futures_core::stream::Stream>::poll_next
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/stream/stream/filter_map.rs:74:35
  13: <futures_util::stream::stream::filter_map::FilterMap<St,Fut,F> as futures_core::stream::Stream>::poll_next
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/stream/stream/filter_map.rs:79:47
  14: <S as futures_core::stream::TryStream>::try_poll_next
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.21/src/stream.rs:196:9
  15: <futures_util::stream::try_stream::try_collect::TryCollect<St,C> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/stream/try_stream/try_collect.rs:46:26
  16: querier::table::QuerierTable::chunks::{{closure}}
             at /home/rust/project/querier/src/table/mod.rs:191:27
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
  18: querier::table::query_access::<impl datafusion::datasource::datasource::TableProvider for querier::table::QuerierTable>::scan::{{closure}}
             at /home/rust/project/querier/src/table/query_access.rs:54:32
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
  20: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/future.rs:124:9
  21: datafusion::physical_plan::planner::DefaultPhysicalPlanner::create_initial_plan::{{closure}}
             at /usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/5e26b13/datafusion/core/src/physical_plan/planner.rs:393:79
  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
  23: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/future.rs:124:9
  24: datafusion::physical_plan::planner::DefaultPhysicalPlanner::create_initial_plan::{{closure}}
             at /usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/5e26b13/datafusion/core/src/physical_plan/planner.rs:633:84
  25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
  26: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/future.rs:124:9
  27: <datafusion::physical_plan::planner::DefaultPhysicalPlanner as datafusion::physical_plan::planner::PhysicalPlanner>::create_physical_plan::{{closure}}
             at /usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/5e26b13/datafusion/core/src/physical_plan/planner.rs:330:70
  28: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
  29: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/future.rs:124:9
  30: <iox_query::exec::context::IOxQueryPlanner as datafusion::execution::context::QueryPlanner>::create_physical_plan::{{closure}}
             at /home/rust/project/iox_query/src/exec/context.rs:84:63
  31: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
  32: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/future.rs:124:9
  33: datafusion::execution::context::SessionState::create_physical_plan::{{closure}}
             at /usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/5e26b13/datafusion/core/src/execution/context.rs:1399:58
  34: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
  35: datafusion::execution::context::SessionContext::create_physical_plan::{{closure}}
             at /usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/5e26b13/datafusion/core/src/execution/context.rs:893:56
  36: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
  37: iox_query::exec::context::IOxSessionContext::create_physical_plan::{{closure}}
             at /home/rust/project/iox_query/src/exec/context.rs:303:65
  38: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
  39: iox_query::exec::context::IOxSessionContext::prepare_sql::{{closure}}
             at /home/rust/project/iox_query/src/exec/context.rs:296:48
  40: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
  41: iox_query::frontend::sql::SqlQueryPlanner::query::{{closure}}
             at /home/rust/project/iox_query/src/frontend/sql.rs:22:31
  42: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
  43: service_common::planner::Planner::sql::{{closure}}::{{closure}}
             at /home/rust/project/service_common/src/planner.rs:42:58
  44: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
  45: executor::DedicatedExecutor::spawn::{{closure}}
             at /home/rust/project/executor/src/lib.rs:232:35
  46: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
  47: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/future.rs:124:9
  48: executor::Task::run::{{closure}}::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/macros/select.rs:507:49
  49: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/future/poll_fn.rs:38:9
  50: executor::Task::run::{{closure}}
             at /home/rust/project/executor/src/lib.rs:43:9
  51: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
  52: executor::DedicatedExecutor::new::{{closure}}::{{closure}}::{{closure}}
             at /home/rust/project/executor/src/lib.rs:194:35
  53: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
  54: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/core.rs:165:17
  55: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/loom/std/unsafe_cell.rs:14:9
  56: tokio::runtime::task::core::CoreStage<T>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/core.rs:155:13
  57: tokio::runtime::task::harness::poll_future::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:470:19
  58: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panic/unwind_safe.rs:271:9
  59: std::panicking::try::do_call
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:492:40
  60: __rust_try
  61: std::panicking::try
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:456:19
  62: std::panic::catch_unwind
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panic.rs:137:14
  63: tokio::runtime::task::harness::poll_future
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:458:18
  64: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:104:27
  65: tokio::runtime::task::harness::Harness<T,S>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:57:15
  66: tokio::runtime::task::raw::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/raw.rs:144:5
  67: tokio::runtime::task::raw::RawTask::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/raw.rs:84:18
  68: tokio::runtime::task::LocalNotified<S>::run
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/mod.rs:376:9
  69: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:458:21
  70: tokio::coop::with_budget::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:102:9
  71: std::thread::local::LocalKey<T>::try_with
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/thread/local.rs:445:16
  72: std::thread::local::LocalKey<T>::with
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/thread/local.rs:421:9
  73: tokio::coop::with_budget
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:95:5
  74: tokio::coop::budget
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:72:5
  75: tokio::runtime::thread_pool::worker::Context::run_task
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:434:9
  76: tokio::runtime::thread_pool::worker::Context::run
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:401:24
  77: tokio::runtime::thread_pool::worker::run::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:386:17
  78: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/macros/scoped_tls.rs:61:9
  79: tokio::runtime::thread_pool::worker::run
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:383:5
  80: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:362:45
  81: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/blocking/task.rs:42:21
  82: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/core.rs:165:17
  83: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/loom/std/unsafe_cell.rs:14:9
  84: tokio::runtime::task::core::CoreStage<T>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/core.rs:155:13
  85: tokio::runtime::task::harness::poll_future::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:470:19
  86: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panic/unwind_safe.rs:271:9
  87: std::panicking::try::do_call
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:492:40
  88: __rust_try
  89: std::panicking::try
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:456:19
  90: std::panic::catch_unwind
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panic.rs:137:14
  91: tokio::runtime::task::harness::poll_future
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:458:18
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

__Steps to reproduce:__
https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/21237/workflows/1598d4b2-34ec-4d6d-bd3f-2a9b28e8b223/jobs/182432 (has no code changes, just doc)

__Expected behaviour:__
The test should always pass

__Actual behaviour:__
Describe What actually happened.

__Environment info:__

* Please provide the command you used to build the project, including any `RUSTFLAGS`.
* System info: Run `uname -srm` or similar and copy the output here (we want to know your OS, architecture etc).
* If you're running IOx in a containerised environment then details about that would be helpful.
* Other relevant environment details: disk info, hardware setup etc.

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in logs or stack traces here.
Sometimes you can get useful information by running the program with the `RUST_BACKTRACE=full` environment variable.
Finally, the IOx server has a `-vv` for verbose logging.

**Comment by alamb** [comment]
Here is another example of the failure: https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/21756/workflows/2d9695c0-85e3-4aa3-99ba-0dce927d9b42/jobs/187696
Complete log: 
[fail.zip](https://github.com/influxdata/influxdb_iox/files/9189690/fail.zip)

**Comment by crepererum** [comment]
This is strange. We even invalidate the sort key if the does not cover the primary key (which should always be non-empty because there's at least the timestamp column):

https://github.com/influxdata/influxdb_iox/blob/bbcf4ec64ed2ec6ef11e5709849fb2be6cb72fe9/querier/src/chunk/mod.rs#L454-L472

Indicating that this is flaky, I'm wondering if the ingester somehow commits the parquet file before (or during) committing the partition sort key to the catalog.

**Comment by alamb** [comment]
I wonder if this could be related somehow to https://github.com/influxdata/conductor/issues/1068 that we are seeing on production 🤔

**Comment by crepererum** [comment]
Another data point, this time a totally different test (`end_to_end_cases::cli::remote_partition_and_get_from_store_and_pull`):

https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/21780/workflows/5301498b-3f0d-4016-93e8-92675cca8e2b/jobs/187940

```text
thread 'tokio-runtime-worker' panicked at 'no partition sort key in catalog', compactor/src/parquet_file_combining.rs:169:10
```

To me, this seems quite related.

**Comment by alamb** [comment]
cc @NGA-TRAN

**Comment by NGA-TRAN** [comment]
Regarding `remote_partition_and_get_from_store_and_pull`, @carols10cents or I will look into it. We talked about it last week but at that time it was always failed without our update.  We may need to change a bit to make the compaction always happens

**Comment by alamb** [comment]
Here is another failure: https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/22100/workflows/4742f080-6ddc-416a-8fe9-88ddf4b09c5f/jobs/191160

```
2022-08-03T21:29:49.874254Z  INFO querier::ingester: Time spent in ingester predicate=Predicate { field_columns: None, range: None, exprs: [], value_expr: [] } namespace=9721638853810284_9178687882469052 table_name=table_11 ingester_duration=12.814668ms status="success"
2022-08-03T21:29:49.874412Z DEBUG querier::table: Ingester partitions fetched namespace=9721638853810284_9178687882469052 table_name=table_11 parquet_cache_outdated=false tombstone_cache_outdated=false max_parquet_sequence_number=None max_tombstone_sequence_number=None
2022-08-03T21:29:49.874452Z DEBUG querier::table: Ingester partitions fetched namespace=9721638853810284_9178687882469052 table_name=table_11 num_ingester_partitions=1
2022-08-03T21:29:49.876846Z ERROR panic_logging: Thread panic panic_info=panicked at 'partition sort key should be set when a parquet file exists', querier/src/chunk/mod.rs:485:14
thread 'IOx Query Executor Thread' panicked at 'partition sort key should be set when a parquet file exists', querier/src/chunk/mod.rs:485:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/option.rs:1854:5
   5: core::option::Option<T>::expect
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/option.rs:718:21
   6: querier::chunk::ChunkAdapter::chunk_parts::{{closure}}
             at /home/rust/project/querier/src/chunk/mod.rs:482:38
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
   8: querier::chunk::ChunkAdapter::new_chunk::{{closure}}
             at /home/rust/project/querier/src/chunk/mod.rs:391:14
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  10: querier::table::QuerierTable::chunks_inner::{{closure}}::{{closure}}::{{closure}}
             at /home/rust/project/querier/src/table/mod.rs:224:26
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  12: <futures_util::stream::stream::filter_map::FilterMap<St,Fut,F> as futures_core::stream::Stream>::poll_next
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/stream/stream/filter_map.rs:74:35
  13: <futures_util::stream::stream::filter_map::FilterMap<St,Fut,F> as futures_core::stream::Stream>::poll_next
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/stream/stream/filter_map.rs:79:47
  14: <S as futures_core::stream::TryStream>::try_poll_next
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.21/src/stream.rs:196:9
  15: <futures_util::stream::try_stream::try_collect::TryCollect<St,C> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/stream/try_stream/try_collect.rs:46:26
  16: querier::table::QuerierTable::chunks_inner::{{closure}}
             at /home/rust/project/querier/src/table/mod.rs:238:27
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  18: querier::table::QuerierTable::chunks::{{closure}}
             at /home/rust/project/querier/src/table/mod.rs:147:59
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  20: querier::table::query_access::<impl datafusion::datasource::datasource::TableProvider for querier::table::QuerierTable>::scan::{{closure}}
             at /home/rust/project/querier/src/table/query_access.rs:60:72
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  22: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/future.rs:124:9
  23: datafusion::physical_plan::planner::DefaultPhysicalPlanner::create_initial_plan::{{closure}}
             at /usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/9a5f17e/datafusion/core/src/physical_plan/planner.rs:394:79
  24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  25: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/future.rs:124:9
  26: datafusion::physical_plan::planner::DefaultPhysicalPlanner::create_initial_plan::{{closure}}
             at /usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/9a5f17e/datafusion/core/src/physical_plan/planner.rs:634:84
  27: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
 ```

**Comment by alamb** [comment]
It certainly looks like the issue is related to the fact that the querier has a stale cache entry for the sort key.

However, there is already logic about expiring the sort key if it doesn't cover all columns in the schema pk:https://github.com/influxdata/influxdb_iox/blob/main/querier/src/cache/partition.rs#L118-L135

Good news is I can reproduce this error locally when I run it enough locally with:

```shell
# run the basic_multi_ingesters test in a loop
set -x
set -e

cd /Users/alamb/Software/influxdb_iox
export RUST_BACKTRACE=1
export CARGO_TARGET_DIR=/Users/alamb/Software/target-iox
export TEST_INTEGRATION=1
export TEST_INFLUXDB_IOX_CATALOG_DSN=postgresql://localhost:5432/alamb

for i in `seq 1 1000` ; do
    echo "****** AAL iteration $i"
    cargo test --test end_to_end  -- basic_multi_ingesters
    #/Users/alamb/Software/target-iox/debug/deps/end_to_end-af1a566230d46569 basic_multi_ingesters
done

echo "COMPLETE"
```

So I am now adding more logging to sort it out.

**Comment by alamb** [comment]
Well, good news is I have a fix for this intermittent failure: https://github.com/influxdata/influxdb_iox/pull/5333 

Bad news is that several other tests now fail 🤦  -- I am investigating

**Comment by alamb** [comment]
PR fix is ready: https://github.com/influxdata/influxdb_iox/pull/5333
