### ISSUE TITLE
Intermittent failures in `data::tests::persist` (flaky test)

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#5434]
# Description
This test fails intermittently and then passes on retry

Here is an example failure: https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/22674/workflows/a61e1ffd-5ae4-4050-9f92-b2e8e190cc5a/jobs/196938

```
thread 'data::tests::persist' panicked at 'assertion failed: `(left == right)`
  left: `1248`,
 right: `1252`', ingester/src/data.rs:2053:9
```

Passed on rerun: https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/22674/workflows/16a46f40-6e06-41ec-ad60-fef92d777688/jobs/196957

# Logs

```
failures:

---- data::tests::persist stdout ----
2022-08-19T10:01:54.984234Z DEBUG datafusion::execution::memory_manager: Creating memory manager with initial size 11744051.2 TB    
2022-08-19T10:01:54.993019Z DEBUG ingester::data: Persisting partition_id=PartitionId(1) partition_info=PartitionInfo { partition: Partition { id: PartitionId(1), sequencer_id: SequencerId(1), table_id: TableId(1), partition_key: PartitionKey("1970-01-01"), sort_key: [] }, namespace_name: "foo", table_name: "mem" }
2022-08-19T10:01:54.994656Z DEBUG schema::sort: Computed sort key primary_key=["time"] sort_key=SortKey { columns: {"time": SortOptions { descending: false, nulls_first: true }} }
2022-08-19T10:01:54.995425Z DEBUG iox_query::frontend::reorg: created compact plan for table table_name="mem" plan=TableScan: mem [foo:Float64;N, time:Timestamp(Nanosecond, None)]
2022-08-19T10:01:54.995532Z DEBUG iox_query::exec::context: create_physical_plan: initial plan text=TableScan: mem [foo:Float64;N, time:Timestamp(Nanosecond, None)]
2022-08-19T10:01:54.995650Z DEBUG datafusion_optimizer::optimizer: Input logical plan:
TableScan: mem
    
2022-08-19T10:01:54.995830Z DEBUG datafusion_optimizer::optimizer: After apply simplify_expressions rule:
    
2022-08-19T10:01:54.995850Z DEBUG datafusion_optimizer::optimizer: Optimized logical plan:
TableScan: mem
    
2022-08-19T10:01:54.995998Z DEBUG datafusion_optimizer::optimizer: After apply decorrelate_where_exists rule:
    
2022-08-19T10:01:54.996020Z DEBUG datafusion_optimizer::optimizer: Optimized logical plan:
TableScan: mem
    
2022-08-19T10:01:54.996058Z DEBUG datafusion_optimizer::optimizer: After apply decorrelate_where_in rule:
    
2022-08-19T10:01:54.996074Z DEBUG datafusion_optimizer::optimizer: Optimized logical plan:
TableScan: mem
    
2022-08-19T10:01:54.996377Z DEBUG datafusion_optimizer::optimizer: After apply decorrelate_scalar_subquery rule:
    
2022-08-19T10:01:54.996420Z DEBUG datafusion_optimizer::optimizer: Optimized logical plan:
TableScan: mem
    
2022-08-19T10:01:54.996461Z DEBUG datafusion_optimizer::optimizer: After apply subquery_filter_to_join rule:
    
2022-08-19T10:01:54.996488Z DEBUG datafusion_optimizer::optimizer: Optimized logical plan:
TableScan: mem
    
2022-08-19T10:01:54.996528Z DEBUG datafusion_optimizer::optimizer: After apply eliminate_filter rule:
    
2022-08-19T10:01:54.996553Z DEBUG datafusion_optimizer::optimizer: Optimized logical plan:
TableScan: mem
    
2022-08-19T10:01:54.996667Z DEBUG datafusion_optimizer::optimizer: After apply common_sub_expression_eliminate rule:
    
2022-08-19T10:01:54.996689Z DEBUG datafusion_optimizer::optimizer: Optimized logical plan:
TableScan: mem
    
2022-08-19T10:01:54.996726Z DEBUG datafusion_optimizer::optimizer: After apply eliminate_limit rule:
    
2022-08-19T10:01:54.996746Z DEBUG datafusion_optimizer::optimizer: Optimized logical plan:
TableScan: mem
    
2022-08-19T10:01:54.996936Z DEBUG datafusion_optimizer::optimizer: After apply projection_push_down rule:
    
2022-08-19T10:01:54.996956Z DEBUG datafusion_optimizer::optimizer: Optimized logical plan:
TableScan: mem projection=[foo, time]
    
2022-08-19T10:01:54.997001Z DEBUG datafusion_optimizer::optimizer: After apply rewrite_disjunctive_predicate rule:
    
2022-08-19T10:01:54.997015Z DEBUG datafusion_optimizer::optimizer: Optimized logical plan:
TableScan: mem projection=[foo, time]
    
2022-08-19T10:01:54.997063Z DEBUG datafusion_optimizer::optimizer: After apply reduce_outer_join rule:
    
2022-08-19T10:01:54.997149Z DEBUG datafusion_optimizer::optimizer: Optimized logical plan:
TableScan: mem projection=[foo, time]
    
2022-08-19T10:01:54.997227Z DEBUG datafusion_optimizer::optimizer: After apply filter_push_down rule:
    
2022-08-19T10:01:54.997257Z DEBUG datafusion_optimizer::optimizer: Optimized logical plan:
TableScan: mem projection=[foo, time]
    
2022-08-19T10:01:54.997313Z DEBUG datafusion_optimizer::optimizer: After apply limit_push_down rule:
    
2022-08-19T10:01:54.997339Z DEBUG datafusion_optimizer::optimizer: Optimized logical plan:
TableScan: mem projection=[foo, time]
    
2022-08-19T10:01:54.997391Z DEBUG datafusion_optimizer::optimizer: After apply SingleDistinctAggregationToGroupBy rule:
    
2022-08-19T10:01:54.997416Z DEBUG datafusion_optimizer::optimizer: Optimized logical plan:
TableScan: mem projection=[foo, time]
    
2022-08-19T10:01:54.997461Z DEBUG datafusion_optimizer::optimizer: Optimized logical plan:
TableScan: mem projection=[foo, time]
    
2022-08-19T10:01:54.998053Z DEBUG iox_query::provider: pruned with pushed down predicates predicate=Predicate num_initial_chunks=1 num_final_chunks=1
2022-08-19T10:01:54.998107Z DEBUG iox_query::provider: All chunks schema schema=Schema { fields: [Field { name: "foo", data_type: Float64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: Some({"iox::column::type": "iox::column_type::field::float"}) }, Field { name: "time", data_type: Timestamp(Nanosecond, None), nullable: false, dict_id: 0, dict_is_ordered: false, metadata: Some({"iox::column::type": "iox::column_type::timestamp"}) }], metadata: {} }
2022-08-19T10:01:54.998781Z DEBUG iox_query::provider: Chunks after classifying overlapped_chunks=1 in_chunk_duplicates=0 no_duplicates_chunks=0
2022-08-19T10:01:54.998820Z DEBUG iox_query::provider: output_sort_key is provided for building deduplicate plan sort_key=time,
2022-08-19T10:01:54.998889Z DEBUG iox_query::provider: Sort keys while building build_deduplicate_plan_for_overlapped_chunks chunks_dedup_sort_key=SortKey { columns: {"time": SortOptions { descending: false, nulls_first: true }} } output_sort_key=Some(SortKey { columns: {"time": SortOptions { descending: false, nulls_first: true }} }) pk_schema=Schema { inner: Schema { fields: [Field { name: "time", data_type: Timestamp(Nanosecond, None), nullable: false, dict_id: 0, dict_is_ordered: false, metadata: Some({"iox::column::type": "iox::column_type::timestamp"}) }], metadata: {} } }
2022-08-19T10:01:54.999454Z DEBUG iox_query::provider: creating deduplicate plan for overlapped chunks output_schema=Schema { inner: Schema { fields: [Field { name: "foo", data_type: Float64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: Some({"iox::column::type": "iox::column_type::field::float"}) }, Field { name: "time", data_type: Timestamp(Nanosecond, None), nullable: false, dict_id: 0, dict_is_ordered: false, metadata: Some({"iox::column::type": "iox::column_type::timestamp"}) }], metadata: {} } } pk_schema=Schema { inner: Schema { fields: [Field { name: "time", data_type: Timestamp(Nanosecond, None), nullable: false, dict_id: 0, dict_is_ordered: false, metadata: Some({"iox::column::type": "iox::column_type::timestamp"}) }], metadata: {} } } input_schema=Schema { inner: Schema { fields: [Field { name: "foo", data_type: Float64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: Some({"iox::column::type": "iox::column_type::field::float"}) }, Field { name: "time", data_type: Timestamp(Nanosecond, None), nullable: false, dict_id: 0, dict_is_ordered: false, metadata: Some({"iox::column::type": "iox::column_type::timestamp"}) }], metadata: {} } }
2022-08-19T10:01:55.000300Z DEBUG iox_query::provider: input to build_sort_plan chunk_id=ChunkId(718dfdbe-e6c7-4f2f-b6ff-f7e65acc2a1e) output_sort_key=SortKey { columns: {"time": SortOptions { descending: false, nulls_first: true }} }
2022-08-19T10:01:55.000340Z DEBUG iox_query::provider: Chunk is not yet sorted and will get sorted in build_sort_plan chunk_type="PersistingBatch" chunk_id=ChunkId(72333b5a-bc68-4657-a175-524714b74013)
2022-08-19T10:01:55.000398Z DEBUG iox_query::provider: Sort Expression for the sort operator of chunk sort_exprs=[PhysicalSortExpr { expr: Column { name: "time", index: 1 }, options: SortOptions { descending: false, nulls_first: true } }] chunk_id=ChunkId(c7001af6-c7c2-4f4e-936a-0a20d3bf5bc0)
2022-08-19T10:01:55.000549Z DEBUG datafusion::physical_plan::planner: Input physical plan:
SortPreservingMergeExec: [time@1 ASC]
  DeduplicateExec: [time@1 ASC]
    SortPreservingMergeExec: [time@1 ASC]
      UnionExec
        SortExec: [time@1 ASC]
          IOxReadFilterNode: table_name=mem, chunks=1 predicate=Predicate

    
2022-08-19T10:01:55.000807Z DEBUG datafusion::physical_plan::planner: Optimized physical plan:
SortPreservingMergeExec: [time@1 ASC]
  DeduplicateExec: [time@1 ASC]
    SortPreservingMergeExec: [time@1 ASC]
      UnionExec
        SortExec: [time@1 ASC]
          IOxReadFilterNode: table_name=mem, chunks=1 predicate=Predicate

    
2022-08-19T10:01:55.000961Z DEBUG iox_query::exec::context: create_physical_plan: plan to run text=SortPreservingMergeExec: [time@1 ASC]
  DeduplicateExec: [time@1 ASC]
    SortPreservingMergeExec: [time@1 ASC]
      UnionExec
        SortExec: [time@1 ASC]
          IOxReadFilterNode: table_name=mem, chunks=1 predicate=Predicate

2022-08-19T10:01:55.031792Z DEBUG datafusion::physical_plan::sorts::sort_preserving_merge: Start SortPreservingMergeExec::execute for partition: 0    
2022-08-19T10:01:55.031946Z DEBUG datafusion::physical_plan::sorts::sort_preserving_merge: Number of input partitions of  SortPreservingMergeExec::execute: 1    
2022-08-19T10:01:55.032178Z DEBUG datafusion::physical_plan::sorts::sort_preserving_merge: Start SortPreservingMergeExec::execute for partition: 0    
2022-08-19T10:01:55.032274Z DEBUG datafusion::physical_plan::sorts::sort_preserving_merge: Number of input partitions of  SortPreservingMergeExec::execute: 1    
2022-08-19T10:01:55.032299Z DEBUG datafusion::physical_plan::union: Start UnionExec::execute for partition 0 of context session_id 8feaadc9-28bd-4f63-b5d5-6c2e5c9d844b and task_id None    
2022-08-19T10:01:55.032411Z DEBUG datafusion::physical_plan::sorts::sort: Start SortExec::execute for partition 0 of context session_id 8feaadc9-28bd-4f63-b5d5-6c2e5c9d844b and task_id None    
2022-08-19T10:01:55.032443Z DEBUG datafusion::physical_plan::sorts::sort: Start invoking SortExec's input.execute for partition: 0    
2022-08-19T10:01:55.032850Z DEBUG datafusion::physical_plan::sorts::sort: End SortExec's input.execute for partition: 0    
2022-08-19T10:01:55.032951Z DEBUG datafusion::physical_plan::union: Found a Union partition to execute    
2022-08-19T10:01:55.032973Z DEBUG datafusion::physical_plan::sorts::sort_preserving_merge: Done getting stream for SortPreservingMergeExec::execute with 1 input    
2022-08-19T10:01:55.033023Z DEBUG iox_query::provider::deduplicate: End building stream for DeduplicationExec::execute partition=0
2022-08-19T10:01:55.033063Z DEBUG datafusion::physical_plan::sorts::sort_preserving_merge: Done getting stream for SortPreservingMergeExec::execute with 1 input    
2022-08-19T10:01:55.033149Z DEBUG datafusion::physical_plan::sorts::sort: Start do_sort for partition 0 of context session_id 8feaadc9-28bd-4f63-b5d5-6c2e5c9d844b and task_id None    
2022-08-19T10:01:55.033209Z DEBUG ingester::data: Adjusted sort key during compacting the persting batch partition_id=PartitionId(1) sort_key_update=Some(SortKey { columns: {"time": SortOptions { descending: false, nulls_first: true }} })
2022-08-19T10:01:55.033280Z DEBUG datafusion::execution::memory_manager: trying to acquire 464.0 B whiling holding 0.0 B from consumer 0:129    
2022-08-19T10:01:55.033254Z DEBUG parquet_file::serialize: IOxMetaData provided for serializing the data into the in-memory buffer partition_id=PartitionId(1) meta=IoxMetadata { object_store_id: 9b028346-53b9-4420-b74a-059eafd5db6b, creation_timestamp: 2022-08-19T10:01:55.033168851+00:00, namespace_id: NamespaceId(1), namespace_name: "foo", sequencer_id: SequencerId(1), table_id: TableId(1), table_name: "mem", partition_id: PartitionId(1), partition_key: PartitionKey("1970-01-01"), max_sequence_number: SequenceNumber(2), compaction_level: Initial, sort_key: Some(SortKey { columns: {"time": SortOptions { descending: false, nulls_first: true }} }) }
2022-08-19T10:01:55.033622Z DEBUG datafusion::execution::memory_manager: free: total 464.0 B, freed 464.0 B    
2022-08-19T10:01:55.033658Z DEBUG datafusion::physical_plan::sorts::sort: End do_sort for partition 0 of context session_id 8feaadc9-28bd-4f63-b5d5-6c2e5c9d844b and task_id None    
2022-08-19T10:01:55.033923Z DEBUG iox_query::provider::deduplicate: before sending the left over batch
2022-08-19T10:01:55.034060Z DEBUG iox_query::provider::deduplicate: done sending the left over batch
2022-08-19T10:01:55.035716Z DEBUG parquet_file::serialize: Parquet Metadata partition_id=PartitionId(1) meta=FileMetaData { version: 1, schema: [SchemaElement { type_: None, type_length: None, repetition_type: None, name: "arrow_schema", num_children: Some(2), converted_type: None, scale: None, precision: None, field_id: None, logical_type: None }, SchemaElement { type_: Some(Double), type_length: None, repetition_type: Some(Optional), name: "foo", num_children: None, converted_type: None, scale: None, precision: None, field_id: None, logical_type: None }, SchemaElement { type_: Some(Int64), type_length: None, repetition_type: Some(Required), name: "time", num_children: None, converted_type: None, scale: None, precision: None, field_id: None, logical_type: Some(TIMESTAMP(TimestampType { is_adjusted_to_u_t_c: false, unit: NANOS(NanoSeconds) })) }], num_rows: 2, row_groups: [RowGroup { columns: [ColumnChunk { file_path: None, file_offset: 91, meta_data: Some(ColumnMetaData { type_: Double, encodings: [Plain, Rle, RleDictionary], path_in_schema: ["foo"], codec: Zstd, num_values: 2, total_uncompressed_size: 69, total_compressed_size: 87, key_value_metadata: None, data_page_offset: 35, index_page_offset: None, dictionary_page_offset: Some(4), statistics: Some(Statistics { max: None, min: None, null_count: None, distinct_count: None, max_value: Some([0, 0, 0, 0, 0, 0, 240, 63]), min_value: Some([0, 0, 0, 0, 0, 0, 240, 63]) }), encoding_stats: None, bloom_filter_offset: None }), offset_index_offset: Some(346), offset_index_length: Some(10), column_index_offset: Some(284), column_index_length: Some(31), crypto_metadata: None, encrypted_column_metadata: None }, ColumnChunk { file_path: None, file_offset: 231, meta_data: Some(ColumnMetaData { type_: Int64, encodings: [Plain, Rle, RleDictionary], path_in_schema: ["time"], codec: Zstd, num_values: 2, total_uncompressed_size: 72, total_compressed_size: 90, key_value_metadata: None, data_page_offset: 180, index_page_offset: None, dictionary_page_offset: Some(141), statistics: Some(Statistics { max: None, min: None, null_count: None, distinct_count: None, max_value: Some([30, 0, 0, 0, 0, 0, 0, 0]), min_value: Some([10, 0, 0, 0, 0, 0, 0, 0]) }), encoding_stats: None, bloom_filter_offset: None }), offset_index_offset: Some(356), offset_index_length: Some(11), column_index_offset: Some(315), column_index_length: Some(31), crypto_metadata: None, encrypted_column_metadata: None }], total_byte_size: 177, num_rows: 2, sorting_columns: None, file_offset: None, total_compressed_size: None, ordinal: None }], key_value_metadata: Some([KeyValue { key: "IOX:metadata", value: Some("ChCbAoNGU7lEILdKBZ6v1dtrEgsIk7/9lwYQ07voDxgBIgNmb28oATABOgNtZW1AAUoKMTk3MC0wMS0wMWgCegoKCAoEdGltZRgB") }, KeyValue { key: "ARROW:schema", value: Some("/////3gBAAAQAAAAAAAKAA4ADAALAAQACgAAABQAAAAAAAABBAAKAAwAAAAIAAQACgAAAAgAAAAIAAAAAAAAAAIAAACwAAAAGAAAAAAAEgAYABQAAAATAAgAAAAMAAQAEgAAADQAAAAUAAAADAAAAAAAAAoYAAAAAAAAAG7///8AAAMAAAAAAAAAAAAEAAAAdGltZQAAAAABAAAABAAAAHD///8oAAAABAAAABsAAABpb3g6OmNvbHVtbl90eXBlOjp0aW1lc3RhbXAAEQAAAGlveDo6Y29sdW1uOjp0eXBlABIAGgAUABIAEwAIAAAADAAEABIAAAAwAAAAGAAAABwAAAAAAAEDGAAAAAAABgAIAAYABgAAAAAAAgAAAAAAAwAAAGZvbwABAAAADAAAAAgADAAEAAgACAAAACwAAAAEAAAAHgAAAGlveDo6Y29sdW1uX3R5cGU6OmZpZWxkOjpmbG9hdAAAEQAAAGlveDo6Y29sdW1uOjp0eXBlAAAA") }]), created_by: Some("parquet-rs version 20.0.0"), column_orders: None, encryption_algorithm: None, footer_signing_key_metadata: None }
2022-08-19T10:01:55.035863Z DEBUG parquet_file::serialize: Done shrink to fit partition_id=PartitionId(1)
2022-08-19T10:01:55.036721Z DEBUG parquet_file::storage: IoxParquetMetaData coverted from Row Group Metadata (aka FileMetaData) meta.partition_id=PartitionId(1) parquet_meta=IoxParquetMetaData { data: "<601 bytes>" }
2022-08-19T10:01:55.036919Z DEBUG ingester::data: Updated sort key in catalog partition_id=PartitionId(1) table_id=TableId(1) sort_key=["time"]
2022-08-19T10:01:55.037695Z DEBUG ingester::data: parquet file written to catalog partition_id=PartitionId(1) table_id=TableId(1) parquet_file_id=ParquetFileId(1) table_name=mem
2022-08-19T10:01:55.037761Z DEBUG ingester::data: mark_persisted partition_id=PartitionId(1) table_name=mem partition_key=1970-01-01 max_sequence_number=2
thread 'data::tests::persist' panicked at 'assertion failed: `(left == right)`
  left: `1248`,
 right: `1252`', ingester/src/data.rs:2053:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:181:5
   4: ingester::data::tests::persist::{{closure}}
             at ./src/data.rs:2053:9
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
   6: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/future.rs:124:9
   7: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/basic_scheduler.rs:543:48
   8: tokio::coop::with_budget::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/coop.rs:102:9
   9: std::thread::local::LocalKey<T>::try_with
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/thread/local.rs:445:16
  10: std::thread::local::LocalKey<T>::with
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/thread/local.rs:421:9
  11: tokio::coop::with_budget
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/coop.rs:95:5
  12: tokio::coop::budget
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/coop.rs:72:5
  13: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/basic_scheduler.rs:543:25
  14: tokio::runtime::basic_scheduler::Context::enter
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/basic_scheduler.rs:367:19
  15: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/basic_scheduler.rs:542:36
  16: tokio::runtime::basic_scheduler::CoreGuard::enter::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/basic_scheduler.rs:613:57
  17: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/macros/scoped_tls.rs:61:9
  18: tokio::runtime::basic_scheduler::CoreGuard::enter
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/basic_scheduler.rs:613:27
  19: tokio::runtime::basic_scheduler::CoreGuard::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/basic_scheduler.rs:533:19
  20: tokio::runtime::basic_scheduler::BasicScheduler::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/basic_scheduler.rs:179:24
  21: tokio::runtime::Runtime::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/mod.rs:482:46
  22: ingester::data::tests::persist
             at ./src/data.rs:2098:9
  23: ingester::data::tests::persist::{{closure}}
             at ./src/data.rs:1884:11
  24: core::ops::function::FnOnce::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5
  25: core::ops::function::FnOnce::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2022-08-19T10:01:55.108653Z  WARN executor: DedicatedExecutor dropped without calling shutdown()
2022-08-19T10:01:55.108902Z  WARN executor: DedicatedExecutor dropped without calling shutdown()


failures:
    data::tests::persist

test result: FAILED. 75 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.30s

error: test failed, to rerun pass '-p ingester --lib'
```

**Comment by alamb** [comment]
I think the issue here is that parquet files contain metadata with timestamps, and since our parquet files are compressed with block level compression there can be small variations in file size.
