### ISSUE TITLE
thread 'tokio-runtime-worker' panicked at 'attempt to add with overflow',  while running flux query

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#590]
__Steps to reproduce:__
Run this flux query against the default telegraph system schema:
```
from(bucket: "devbucket")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "cpu")
  |> filter(fn: (r) => r["_field"] == "usage_user")
  |> group(columns: ["cpu"])
  |> sum()
```

__Expected behaviour:__
results are produced

__Actual behaviour:__
An error is logged:
```
Dec 21 09:23:34.867  INFO influxdb_iox::server::rpc::service: read_group for database 26f7e5a4b7be365b_917b97a92e883afc, range: Some(TimestampRange { start: 1608559714855817000, end: 1608560614855817000 }), group_keys: ["cpu"], group: 2, aggregate: Some(Aggregate { r#type: Sum }), predicate: ((TagRef:_m[0x00] == "cpu") AND (TagRef:_f[0xff] == "usage_user"))
Dec 21 09:23:34.895 ERROR influxdb_iox::panic: thread 'tokio-runtime-worker' panicked at 'attempt to add with overflow', /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/arith.rs:107:1
thread 'tokio-runtime-worker' panicked at 'attempt to add with overflow', /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/arith.rs:107:1
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8256379832b5ecb7f71e8c5e2018446482223c12/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/8256379832b5ecb7f71e8c5e2018446482223c12/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/8256379832b5ecb7f71e8c5e2018446482223c12/library/core/src/panicking.rs:50:5
   3: <i64 as core::ops::arith::Add>::add
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/arith.rs:100:45
   4: <arrow::compute::kernels::aggregate::simd::SumAggregate<T> as arrow::compute::kernels::aggregate::simd::SimdAggregate<T>>::accumulate_scalar
             at /Users/alamb/.cargo/git/checkouts/arrow-3a9cfebb6b7b2bdc/edff65d/rust/arrow/src/compute/kernels/aggregate.rs:271:28
   5: arrow::compute::kernels::aggregate::simd::simd_aggregation::{{closure}}
             at /Users/alamb/.cargo/git/checkouts/arrow-3a9cfebb6b7b2bdc/edff65d/rust/arrow/src/compute/kernels/aggregate.rs:499:21
   6: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::for_each
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/iter/macros.rs:203:21
   7: arrow::compute::kernels::aggregate::simd::simd_aggregation
             at /Users/alamb/.cargo/git/checkouts/arrow-3a9cfebb6b7b2bdc/edff65d/rust/arrow/src/compute/kernels/aggregate.rs:498:17
   8: arrow::compute::kernels::aggregate::sum
             at /Users/alamb/.cargo/git/checkouts/arrow-3a9cfebb6b7b2bdc/edff65d/rust/arrow/src/compute/kernels/aggregate.rs:547:5
   9: datafusion::physical_plan::expressions::sum_batch
             at /Users/alamb/.cargo/git/checkouts/arrow-3a9cfebb6b7b2bdc/edff65d/rust/datafusion/src/physical_plan/expressions.rs:205:28
  10: <datafusion::physical_plan::expressions::SumAccumulator as datafusion::physical_plan::Accumulator>::update_batch
             at /Users/alamb/.cargo/git/checkouts/arrow-3a9cfebb6b7b2bdc/edff65d/rust/datafusion/src/physical_plan/expressions.rs:309:36
  11: datafusion::physical_plan::hash_aggregate::group_aggregate_batch::{{closure}}::{{closure}}
             at /Users/alamb/.cargo/git/checkouts/arrow-3a9cfebb6b7b2bdc/edff65d/rust/datafusion/src/physical_plan/hash_aggregate.rs:318:47
  12: core::iter::adapters::map_try_fold::{{closure}}
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:912:28
  13: core::iter::adapters::map_try_fold::{{closure}}
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:912:21
  14: core::iter::traits::iterator::Iterator::try_fold
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:1888:21
  15: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:938:9
  16: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:938:9
  17: <core::iter::adapters::ResultShunt<I,E> as core::iter::traits::iterator::Iterator>::try_fold
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:2945:9
  18: <core::iter::adapters::ResultShunt<I,E> as core::iter::traits::iterator::Iterator>::fold
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:2966:9
  19: core::iter::traits::iterator::Iterator::for_each
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:678:9
  20: core::unit::<impl core::iter::traits::collect::FromIterator<()> for ()>::from_iter
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/unit.rs:19:9
  21: core::iter::traits::iterator::Iterator::collect
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:1670:9
  22: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter::{{closure}}
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:1490:53
  23: core::iter::adapters::process_results
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:2916:17
  24: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:1490:9
  25: core::iter::traits::iterator::Iterator::collect
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:1670:9
  26: datafusion::physical_plan::hash_aggregate::group_aggregate_batch::{{closure}}
             at /Users/alamb/.cargo/git/checkouts/arrow-3a9cfebb6b7b2bdc/edff65d/rust/datafusion/src/physical_plan/hash_aggregate.rs:296:13
  27: core::iter::adapters::map_try_fold::{{closure}}
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:912:28
  28: core::iter::traits::iterator::Iterator::try_fold
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:1888:21
  29: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:938:9
  30: <core::iter::adapters::ResultShunt<I,E> as core::iter::traits::iterator::Iterator>::try_fold
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:2945:9
  31: <core::iter::adapters::ResultShunt<I,E> as core::iter::traits::iterator::Iterator>::fold
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:2966:9
  32: core::iter::traits::iterator::Iterator::for_each
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:678:9
  33: core::unit::<impl core::iter::traits::collect::FromIterator<()> for ()>::from_iter
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/unit.rs:19:9
  34: core::iter::traits::iterator::Iterator::collect
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:1670:9
  35: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter::{{closure}}
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:1490:53
  36: core::iter::adapters::process_results
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:2916:17
  37: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:1490:9
  38: core::iter::traits::iterator::Iterator::collect
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:1670:9
  39: datafusion::physical_plan::hash_aggregate::group_aggregate_batch
             at /Users/alamb/.cargo/git/checkouts/arrow-3a9cfebb6b7b2bdc/edff65d/rust/datafusion/src/physical_plan/hash_aggregate.rs:291:5
  40: datafusion::physical_plan::hash_aggregate::compute_grouped_hash_aggregate::{{closure}}
             at /Users/alamb/.cargo/git/checkouts/arrow-3a9cfebb6b7b2bdc/edff65d/rust/datafusion/src/physical_plan/hash_aggregate.rs:353:24
  41: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  42: datafusion::physical_plan::hash_aggregate::GroupedHashAggregateStream::new::{{closure}}
             at /Users/alamb/.cargo/git/checkouts/arrow-3a9cfebb6b7b2bdc/edff65d/rust/datafusion/src/physical_plan/hash_aggregate.rs:380:26
  43: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  44: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/core.rs:173:17
  45: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/loom/std/unsafe_cell.rs:14:9
  46: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/core.rs:158:13
  47: tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
             at /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/harness.rs:107:27
  48: core::ops::function::FnOnce::call_once
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  49: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:322:9
  50: std::panicking::try::do_call
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  51: ___rust_try
  52: std::panicking::try
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  53: std::panic::catch_unwind
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:396:14
  54: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/harness.rs:89:19
  55: tokio::runtime::task::raw::poll
             at /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/raw.rs:104:5
  56: tokio::runtime::task::raw::RawTask::poll
             at /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/raw.rs:66:18
  57: tokio::runtime::task::Notified<S>::run
             at /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/mod.rs:169:9
  58: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/thread_pool/worker.rs:349:13
  59: tokio::coop::with_budget::{{closure}}
             at /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/coop.rs:127:9
  60: std::thread::local::LocalKey<T>::try_with
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  61: std::thread::local::LocalKey<T>::with
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  62: tokio::coop::with_budget
             at /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/coop.rs:120:5
  63: tokio::coop::budget
             at /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/coop.rs:96:5
  64: tokio::runtime::thread_pool::worker::Context::run_task
             at /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/thread_pool/worker.rs:348:9
  65: tokio::runtime::thread_pool::worker::Context::run
             at /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/thread_pool/worker.rs:320:24
  66: tokio::runtime::thread_pool::worker::run::{{closure}}
             at /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/thread_pool/worker.rs:305:17
  67: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/macros/scoped_tls.rs:63:9
  68: tokio::runtime::thread_pool::worker::run
             at /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/thread_pool/worker.rs:302:5
  69: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/thread_pool/worker.rs:281:45
  70: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/blocking/task.rs:41:21
  71: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/core.rs:173:17
  72: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/loom/std/unsafe_cell.rs:14:9
  73: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/core.rs:158:13
  74: tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
             at /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/harness.rs:107:27
  75: core::ops::function::FnOnce::call_once
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  76: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:322:9
  77: std::panicking::try::do_call
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  78: ___rust_try
  79: std::panicking::try
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  80: std::panic::catch_unwind
             at /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:396:14
  81: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/harness.rs:89:19
  82: tokio::runtime::task::raw::poll
             at /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/raw.rs:104:5
  83: tokio::runtime::task::raw::RawTask::poll
             at /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/raw.rs:66:18
  84: tokio::runtime::task::Notified<S>::run
             at /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/mod.rs:169:9
  85: tokio::runtime::blocking::pool::Inner::run
             at /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/blocking/pool.rs:250:17
  86: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::{{closure}}
             at /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/blocking/pool.rs:230:21
  87: tokio::runtime::context::enter
             at /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/context.rs:72:5
  88: tokio::runtime::handle::Handle::enter
             at /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/handle.rs:76:9
  89: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/blocking/pool.rs:229:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

__Environment info:__

* Please provide the command you used to build the project, including any `RUSTFLAGS`.
* System info: Run `uname -srm` or similar and copy the output here (we want to know your OS, architecture etc).
* If you're running IOx in a containerised environment then details about that would be helpful.
* Other relevant environment details: disk info, hardware setup etc.

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in logs or stack traces here.
Sometimes you can get useful information by running the program with the `RUST_BACKTRACE=full` environment variable.
Finally, the IOx server has a `-vv` for verbose logging.

**Comment by alamb** [comment]
We haven't seen this for a long time, closing as not actionable
