### ISSUE TITLE
Flaky test: `postgres::tests::test_catalog` (`iox_catalog`)

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#6085]
```
---- postgres::tests::test_catalog stdout ----
thread 'postgres::tests::test_catalog' panicked at 'assertion failed: `(left == right)`
  left: `[ParquetFile { id: ParquetFileId(55), shard_id: ShardId(18), namespace_id: NamespaceId(20), table_id: TableId(25), partition_id: PartitionId(24), object_store_id: c0ec0792-18f8-4151-bd90-3fa87d7cfa9a, max_sequence_number: SequenceNumber(140), min_time: Timestamp(1), max_time: Timestamp(10), to_delete: None, file_size_bytes: 1337, row_count: 0, compaction_level: FileNonOverlapped, created_at: Timestamp(1), column_set: ColumnSet([ColumnId(1), ColumnId(2)]) }, ParquetFile { id: ParquetFileId(53), shard_id: ShardId(18), namespace_id: NamespaceId(20), table_id: TableId(25), partition_id: PartitionId(24), object_store_id: 199f5d07-9c80-4ab2-b3de-5f31cc98dbcb, max_sequence_number: SequenceNumber(140), min_time: Timestamp(1), max_time: Timestamp(10), to_delete: None, file_size_bytes: 1337, row_count: 0, compaction_level: Initial, created_at: Timestamp(1), column_set: ColumnSet([ColumnId(1), ColumnId(2)]) }]`,
 right: `[ParquetFile { id: ParquetFileId(53), shard_id: ShardId(18), namespace_id: NamespaceId(20), table_id: TableId(25), partition_id: PartitionId(24), object_store_id: 199f5d07-9c80-4ab2-b3de-5f31cc98dbcb, max_sequence_number: SequenceNumber(140), min_time: Timestamp(1), max_time: Timestamp(10), to_delete: None, file_size_bytes: 1337, row_count: 0, compaction_level: Initial, created_at: Timestamp(1), column_set: ColumnSet([ColumnId(1), ColumnId(2)]) }, ParquetFile { id: ParquetFileId(55), shard_id: ShardId(18), namespace_id: NamespaceId(20), table_id: TableId(25), partition_id: PartitionId(24), object_store_id: c0ec0792-18f8-4151-bd90-3fa87d7cfa9a, max_sequence_number: SequenceNumber(140), min_time: Timestamp(1), max_time: Timestamp(10), to_delete: None, file_size_bytes: 1337, row_count: 0, compaction_level: FileNonOverlapped, created_at: Timestamp(1), column_set: ColumnSet([ColumnId(1), ColumnId(2)]) }]`', iox_catalog/src/interface.rs:3764:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:181:5
   4: iox_catalog::interface::test_helpers::test_list_by_partiton_not_to_delete::{{closure}}
             at ./src/interface.rs:3764:9
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
   6: iox_catalog::interface::test_helpers::test_catalog::{{closure}}
             at ./src/interface.rs:924:66
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
   8: iox_catalog::postgres::tests::test_catalog::{{closure}}
             at ./src/postgres.rs:2334:63
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  10: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/future.rs:124:9
  11: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/current_thread.rs:525:48
  12: tokio::coop::with_budget::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:102:9
  13: std::thread::local::LocalKey<T>::try_with
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/local.rs:445:16
  14: std::thread::local::LocalKey<T>::with
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/local.rs:421:9
  15: tokio::coop::with_budget
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:95:5
  16: tokio::coop::budget
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:72:5
  17: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/current_thread.rs:525:25
  18: tokio::runtime::scheduler::current_thread::Context::enter
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/current_thread.rs:349:19
  19: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/current_thread.rs:524:36
  20: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/current_thread.rs:595:57
  21: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/macros/scoped_tls.rs:61:9
  22: tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/current_thread.rs:595:27
  23: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/current_thread.rs:515:19
  24: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/current_thread.rs:161:24
  25: tokio::runtime::Runtime::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/mod.rs:490:46
  26: iox_catalog::postgres::tests::test_catalog
             at ./src/postgres.rs:2334:9
  27: iox_catalog::postgres::tests::test_catalog::{{closure}}
             at ./src/postgres.rs:2325:11
  28: core::ops::function::FnOnce::call_once
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:248:5
  29: core::ops::function::FnOnce::call_once
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    postgres::tests::test_catalog

test result: FAILED. 18 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.97s

error: test failed, to rerun pass '-p iox_catalog --lib'
```

**Comment by crepererum** [comment]
This was fixed by @lukebond in #6073, specifically https://github.com/influxdata/influxdb_iox/pull/6073/commits/079a9d42af7ca975cb218181484073ac083a403e. Thank you!
