### ISSUE TITLE
Intermittent failures on `end_to_end_cases::compactor::running_compactor_generate_twice_overwrites_existing_files`

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#6191]
https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/26035/workflows/72988fdb-6686-4f53-a83a-22d01588d81d/jobs/230805

The actual failure is 

```
end_to_end_cases::compactor::running_compactor_generate_twice_overwrites_existing_files stdout ----
2022-11-21T14:32:48.578094Z DEBUG datafusion::physical_plan::file_format::parquet: Creating ParquetExec, files: [[PartitionedFile { object_meta: ObjectMeta { location: Path { raw: "tmp/.tmpY3TY1d/compactor_data/parquet/data_0_measure.parquet" }, last_modified: 2022-11-21T14:32:48.566560584Z, size: 2933 }, partition_values: [], range: None, extensions: None }]], projection None, predicate: None, limit: None    
2022-11-21T14:32:48.578516Z DEBUG datafusion::execution::memory_manager: Creating memory manager with initial size 11744051.2 TB    
thread 'end_to_end_cases::compactor::running_compactor_generate_twice_overwrites_existing_files' panicked at 'called `Result::unwrap()` on an `Err` value: InferringSchema { source: Execution("file size of 2933 is less than footer + metadata 827474264") }', influxdb_iox/tests/end_to_end_cases/compactor.rs:150:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/result.rs:1785:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/result.rs:1107:23
   4: end_to_end::end_to_end_cases::compactor::read_record_batches::{{closure}}
             at ./tests/end_to_end_cases/compactor.rs:148:18
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
   6: end_to_end::end_to_end_cases::compactor::running_compactor_generate_twice_overwrites_existing_files::{{closure}}
             at ./tests/end_to_end_cases/compactor.rs:129:79
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
   8: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/future.rs:124:9
   9: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/current_thread.rs:531:57
  10: tokio::runtime::coop::with_budget
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/coop.rs:102:5
  11: tokio::runtime::coop::budget
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/coop.rs:68:5
  12: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/current_thread.rs:531:25
  13: tokio::runtime::scheduler::current_thread::Context::enter
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/current_thread.rs:340:19
  14: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/current_thread.rs:530:36
  15: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/current_thread.rs:601:57
  16: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/macros/scoped_tls.rs:61:9
  17: tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/current_thread.rs:601:27
  18: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/current_thread.rs:520:19
  19: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/current_thread.rs:154:24
  20: tokio::runtime::runtime::Runtime::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/runtime.rs:279:47
  21: end_to_end::end_to_end_cases::compactor::running_compactor_generate_twice_overwrites_existing_files
             at ./tests/end_to_end_cases/compactor.rs:139:5
  22: end_to_end::end_to_end_cases::compactor::running_compactor_generate_twice_overwrites_existing_files::{{closure}}
             at ./tests/end_to_end_cases/compactor.rs:87:7
  23: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
  24: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    end_to_end_cases::compactor::running_compactor_generate_twice_overwrites_existing_files
```

I have seen this same failure on my own PRs so wanted to start tracking it

**Comment by alamb** [comment]
FYI @carols10cents  and @NGA-TRAN who I think worked on this feature

**Comment by alamb** [comment]
Dupe of https://github.com/influxdata/influxdb_iox/issues/6190 @domodwyer  beat me to it
