### ISSUE TITLE
In the router gRPC write path, tolerate not being able to contact some ingesters

### ISSUE THREAD

**Issue by carols10cents** [influxdata/influxdb_iox#6321]
See [this comment:](https://github.com/influxdata/influxdb_iox/pull/6320#discussion_r1038280194)

> I think we need to support some ingesters being down when a router starts up (otherwise availability is tied to a single ingester being offline) - I guess this is why there was a deferred connect thing? Perhaps we can error only if all are unreachable or something.

**Comment by carols10cents** [comment]
Yup!

**Comment by domodwyer** [comment]
I'm unsure if we've resolved this - I just saw a router in a crash loop because it couldn't talk to the ingester:

```
<startup messages but before grpc bind>

thread 'main' panicked at 'failed to connect to server iox-shared-ingester-0.iox-shared-ingester:8082: Connection error: transport error (error trying to connect: tcp connect error: Connection refused (os error 111))', /influxdb_iox/router/src/dml_handlers/rpc_write.rs:26:29
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: router::dml_handlers::rpc_write::write_service_client::{{closure}}::{{closure}}
             at ./influxdb_iox/router/src/dml_handlers/rpc_write.rs:26:29
   3: core::result::Result<T,E>::unwrap_or_else
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/result.rs:1498:23
   4: router::dml_handlers::rpc_write::write_service_client::{{closure}}
             at ./influxdb_iox/router/src/dml_handlers/rpc_write.rs:23:22
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
   6: ioxd_router::create_router2_server_type::{{closure}}
             at ./influxdb_iox/ioxd_router/src/lib.rs:265:66
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
   8: influxdb_iox::commands::run::router2::command::{{closure}}
             at ./influxdb_iox/influxdb_iox/src/commands/run/router2.rs:99:5
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  10: influxdb_iox::commands::run::command::{{closure}}
             at ./influxdb_iox/influxdb_iox/src/commands/run/mod.rs:129:67
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  12: influxdb_iox::main::{{closure}}
             at ./influxdb_iox/influxdb_iox/src/main.rs:277:64
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  14: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  15: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/park.rs:272:63
  16: tokio::runtime::coop::with_budget
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/coop.rs:102:5
  17: tokio::runtime::coop::budget
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/coop.rs:68:5
  18: tokio::runtime::park::CachedParkThread::block_on
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/park.rs:272:31
  19: tokio::runtime::context::BlockingRegionGuard::block_on
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/context.rs:255:13
  20: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/multi_thread/mod.rs:66:9
  21: tokio::runtime::runtime::Runtime::block_on
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/runtime.rs:281:45
  22: influxdb_iox::main
             at ./influxdb_iox/influxdb_iox/src/main.rs:203:5
  23: core::ops::function::FnOnce::call_once
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
level=error msg="sender-side of async exporter dropped without waiting for shut down" target="trace_exporters::export" location="trace_exporters/src/export.rs:114" time=1671540772072393620
```
