### ISSUE TITLE
flaky test: `query_tests2::cases::duplicates_ingester`

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#6780]
`query_tests2::cases::duplicates_ingester` for example [here](https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/28624/workflows/473a9691-5977-47c3-8ec8-4d1e43081185/jobs/257450).

<details>

```text
Expected output does not match actual output
  expected output in "/home/rust/project/influxdb_iox/tests/query_tests2/cases/in/duplicates_ingester.expected"
  actual output in "/home/rust/project/influxdb_iox/tests/query_tests2/cases/out/duplicates_ingester.out"
Possibly helpful commands:
  # See diff
  diff -du "/home/rust/project/influxdb_iox/tests/query_tests2/cases/in/duplicates_ingester.expected" "/home/rust/project/influxdb_iox/tests/query_tests2/cases/out/duplicates_ingester.out"
  # Update expected
  cp -f "/home/rust/project/influxdb_iox/tests/query_tests2/cases/out/duplicates_ingester.out" "/home/rust/project/influxdb_iox/tests/query_tests2/cases/in/duplicates_ingester.expected"
thread 'query_tests2::cases::duplicates_ingester' panicked at 'called `Result::unwrap()` on an `Err` value: OutputMismatch { output_path: "/home/rust/project/influxdb_iox/tests/query_tests2/cases/out/duplicates_ingester.out", expected_path: "/home/rust/project/influxdb_iox/tests/query_tests2/cases/in/duplicates_ingester.expected" }', /home/rust/project/test_helpers_end_to_end/src/steps.rs:386:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
   2: core::result::unwrap_failed
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/result.rs:1791:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/result.rs:1113:23
   4: test_helpers_end_to_end::steps::StepTest<S>::run::{{closure}}
             at /home/rust/project/test_helpers_end_to_end/src/steps.rs:379:21
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/future/mod.rs:91:19
   6: end_to_end::query_tests2::framework::TestCase::run::{{closure}}
             at ./tests/query_tests2/framework.rs:132:21
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/future/mod.rs:91:19
   8: end_to_end::query_tests2::cases::duplicates_ingester::{{closure}}
             at ./tests/query_tests2/cases.rs:85:5
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/future/mod.rs:91:19
  10: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/future/future.rs:124:9
  11: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/future/future.rs:124:9
  12: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/current_thread.rs:541:57
  13: tokio::runtime::coop::with_budget
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/coop.rs:102:5
  14: tokio::runtime::coop::budget
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/coop.rs:68:5
  15: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/current_thread.rs:541:25
  16: tokio::runtime::scheduler::current_thread::Context::enter
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/current_thread.rs:350:19
  17: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/current_thread.rs:540:36
  18: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/current_thread.rs:615:57
  19: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/macros/scoped_tls.rs:61:9
  20: tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/current_thread.rs:615:27
  21: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/current_thread.rs:530:19
  22: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/current_thread.rs:154:24
  23: tokio::runtime::runtime::Runtime::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/runtime.rs:282:47
  24: end_to_end::query_tests2::cases::duplicates_ingester
             at ./tests/query_tests2/cases.rs:80:5
  25: end_to_end::query_tests2::cases::duplicates_ingester::{{closure}}
             at ./tests/query_tests2/cases.rs:77:7
  26: core::ops::function::FnOnce::call_once
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/ops/function.rs:251:5
  27: core::ops::function::FnOnce::call_once
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

**Comment by alamb** [comment]
Thank you for the report -- I will look into this -- it is unhelpful that the actual diff is not present in the test output. I will see if I can fix that

**Comment by alamb** [comment]
This is a dupe of  https://github.com/influxdata/influxdb_iox/issues/6819 I believe

**Comment by crepererum** [comment]
Might be, closing (we can always re-open it).
