### ISSUE TITLE
`panic`s in ingester when CTRL-C'ing "all in one mode"

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#7290]
FWIW when I am running "all in one mode" via:

```shell
cargo run -- -v
```

When I hit CTRL-C to kill the process, there are a bunch of `panic`s -- All the data still seems to be there and I think the panics are cosmetic, I just figured I would point it out:
 
```
2023-03-21T15:33:49.914514Z  INFO ioxd_common: backend shutdown completed server_type=Compactor2
2023-03-21T15:33:49.914540Z  INFO influxdb_iox::commands::run::main: done serving, draining futures grpc_bind_address=SocketAddr(127.0.0.1:8084) http_bind_address=None server_type=Compactor2
2023-03-21T15:33:49.926000Z  WARN executor: tried to schedule task on an executor that was shutdown
2023-03-21T15:33:49.926125Z ERROR panic_logging: Thread panic panic_info=panicked at 'called `Result::unwrap()` on an `Err` value: Context("Join Error", External("Worker thread gone, executor was likely shut down"))', /Users/alamb/Software/influxdb_iox/ingester2/src/persist/compact.rs:97:65
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Context("Join Error", External("Worker thread gone, executor was likely shut down"))', /Users/alamb/Software/influxdb_iox/ingester2/src/persist/compact.rs:97:65
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-03-21T15:33:49.927270Z  WARN executor: tried to schedule task on an executor that was shutdown
2023-03-21T15:33:49.927356Z ERROR panic_logging: Thread panic panic_info=panicked at 'called `Result::unwrap()` on an `Err` value: Context("Join Error", External("Worker thread gone, executor was likely shut down"))', /Users/alamb/Software/influxdb_iox/ingester2/src/persist/compact.rs:97:65
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Context("Join Error", External("Worker thread gone, executor was likely shut down"))', /Users/alamb/Software/influxdb_iox/ingester2/src/persist/compact.rs:97:65
2023-03-21T15:33:49.937474Z  WARN executor: tried to schedule task on an executor that was shutdown
2023-03-21T15:33:49.937646Z ERROR panic_logging: Thread panic panic_info=panicked at 'called `Result::unwrap()` on an `Err` value: Context("Join Error", External("Worker thread gone, executor was likely shut down"))', /Users/alamb/Software/influxdb_iox/ingester2/src/persist/compact.rs:97:65
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Context("Join Error", External("Worker thread gone, executor was likely shut down"))', /Users/alamb/Software/influxdb_iox/ingester2/src/persist/compact.rs:97:65
2023-03-21T15:33:49.938042Z ERROR panic_logging: Thread panic panic_info=panicked at 'persist worker task panic: RecvError(())', /Users/alamb/Software/influxdb_iox/ingester2/src/persist/drain_buffer.rs:75:17
thread 'tokio-runtime-worker' panicked at 'persist worker task panic: RecvError(())', /Users/alamb/Software/influxdb_iox/ingester2/src/persist/drain_buffer.rs:75:17
2023-03-21T15:33:49.938247Z ERROR panic_logging: Thread panic panic_info=panicked at 'graceful shutdown task panicked: RecvError(())', /Users/alamb/Software/influxdb_iox/ingester2/src/init.rs:119:14
thread 'tokio-runtime-worker' panicked at 'graceful shutdown task panicked: RecvError(())', /Users/alamb/Software/influxdb_iox/ingester2/src/init.rs:119:14
Server command failed: Run: Error joining server task: task 149 panicked
```

_Originally posted by @alamb in https://github.com/influxdata/influxdb_iox/issues/7284#issuecomment-1478061250_

**Comment by domodwyer** [comment]
I think an important point to make, is that this only happens in all-in-one - stopping a solo ingester performs the proper shutdown process.

There's probably a missing join() in the all-in-one stopper.
