### ISSUE TITLE
Ingester2 crashes when namespace is deleted

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#7438]
From one of our staging environments:

```text
OK
level=info msg="Creating jaeger tracing exporter" agent_endpoint=10.146.86.77:6831 service_name=iox-ingester2 target="trace_exporters::jaeger" location="trace_exporters/src/jaeger.rs:93" time=1680596802299490297
level=info msg="connected to config store" application_name=ingester target="iox_catalog::postgres" location="iox_catalog/src/postgres.rs:436" time=1680596802402030320
level=info msg="Object Store" bucket="Some(\"stag101-us-east-1-iox\")" endpoint=None object_store_type=S3 target="clap_blocks::object_store" location="clap_blocks/src/object_store.rs:290" time=1680596802402397115
level=info msg="Using WebIdentity credential provider" target="object_store::aws" location="/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/object_store-0.5.5/src/aws/mod.rs:894" time=1680596802402424709
level=info msg="initialised persist task" n_workers=20 persist_queue_depth=120000 target="ingester2::persist::handle" location="ingester2/src/persist/handle.rs:192" time=1680596802506593282
level=info msg="Initalizing Write Ahead Log (WAL)" wal_dir="/data" target="wal" location="wal/src/lib.rs:216" time=1680596802506738206
level=info msg="found wal files for replay" n_files=150 target="ingester2::init::wal_replay" location="ingester2/src/init/wal_replay.rs:86" time=1680596802511688339
level=info msg="replaying wal file" file_number=1 n_files=150 file_id=20014 size=285249 target="ingester2::init::wal_replay" location="ingester2/src/init/wal_replay.rs:106" time=1680596802511711632
level=warn msg="request encountered non-fatal error - backing off" error="foreign key violation: error returned from database: insert or update on table \"partition\" violates foreign key constraint \"partition_table_id_fkey\"" task_name="resolve partition" backoff_secs=0 target="backoff" location="backoff/src/lib.rs:179" time=1680596802515291525
level=warn msg="request encountered non-fatal error - backing off" error="foreign key violation: error returned from database: insert or update on table \"partition\" violates foreign key constraint \"partition_table_id_fkey\"" task_name="resolve partition" backoff_secs=0 target="backoff" location="backoff/src/lib.rs:179" time=1680596802619440742
level=warn msg="request encountered non-fatal error - backing off" error="foreign key violation: error returned from database: insert or update on table \"partition\" violates foreign key constraint \"partition_table_id_fkey\"" task_name="resolve partition" backoff_secs=0 target="backoff" location="backoff/src/lib.rs:179" time=1680596802812182201
level=warn msg="request encountered non-fatal error - backing off" error="foreign key violation: error returned from database: insert or update on table \"partition\" violates foreign key constraint \"partition_table_id_fkey\"" task_name="resolve partition" backoff_secs=0 target="backoff" location="backoff/src/lib.rs:179" time=1680596803164300064
level=warn msg="request encountered non-fatal error - backing off" error="foreign key violation: error returned from database: insert or update on table \"partition\" violates foreign key constraint \"partition_table_id_fkey\"" task_name="resolve partition" backoff_secs=0 target="backoff" location="backoff/src/lib.rs:179" time=1680596803363173266
level=warn msg="request encountered non-fatal error - backing off" error="foreign key violation: error returned from database: insert or update on table \"partition\" violates foreign key constraint \"partition_table_id_fkey\"" task_name="resolve partition" backoff_secs=0 target="backoff" location="backoff/src/lib.rs:179" time=1680596803789745137
level=warn msg="request encountered non-fatal error - backing off" error="foreign key violation: error returned from database: insert or update on table \"partition\" violates foreign key constraint \"partition_table_id_fkey\"" task_name="resolve partition" backoff_secs=0 target="backoff" location="backoff/src/lib.rs:179" time=1680596804631205819
level=warn msg="request encountered non-fatal error - backing off" error="foreign key violation: error returned from database: insert or update on table \"partition\" violates foreign key constraint \"partition_table_id_fkey\"" task_name="resolve partition" backoff_secs=0 target="backoff" location="backoff/src/lib.rs:179" time=1680596805074089617
level=warn msg="request encountered non-fatal error - backing off" error="foreign key violation: error returned from database: insert or update on table \"partition\" violates foreign key constraint \"partition_table_id_fkey\"" task_name="resolve partition" backoff_secs=0 target="backoff" location="backoff/src/lib.rs:179" time=1680596805475365581
level=warn msg="request encountered non-fatal error - backing off" error="foreign key violation: error returned from database: insert or update on table \"partition\" violates foreign key constraint \"partition_table_id_fkey\"" task_name="resolve partition" backoff_secs=2 target="backoff" location="backoff/src/lib.rs:179" time=1680596806379366793
level=warn msg="request encountered non-fatal error - backing off" error="foreign key violation: error returned from database: insert or update on table \"partition\" violates foreign key constraint \"partition_table_id_fkey\"" task_name="resolve partition" backoff_secs=0 target="backoff" location="backoff/src/lib.rs:179" time=1680596808481859961
level=warn msg="request encountered non-fatal error - backing off" error="foreign key violation: error returned from database: insert or update on table \"partition\" violates foreign key constraint \"partition_table_id_fkey\"" task_name="resolve partition" backoff_secs=1 target="backoff" location="backoff/src/lib.rs:179" time=1680596809078983181
level=warn msg="request encountered non-fatal error - backing off" error="foreign key violation: error returned from database: insert or update on table \"partition\" violates foreign key constraint \"partition_table_id_fkey\"" task_name="resolve partition" backoff_secs=1 target="backoff" location="backoff/src/lib.rs:179" time=1680596810692972448
level=warn msg="request encountered non-fatal error - backing off" error="foreign key violation: error returned from database: insert or update on table \"partition\" violates foreign key constraint \"partition_table_id_fkey\"" task_name="resolve partition" backoff_secs=0 target="backoff" location="backoff/src/lib.rs:179" time=1680596812200491781
level=warn msg="request encountered non-fatal error - backing off" error="foreign key violation: error returned from database: insert or update on table \"partition\" violates foreign key constraint \"partition_table_id_fkey\"" task_name="resolve partition" backoff_secs=1 target="backoff" location="backoff/src/lib.rs:179" time=1680596812963102829
level=warn msg="request encountered non-fatal error - backing off" error="foreign key violation: error returned from database: insert or update on table \"partition\" violates foreign key constraint \"partition_table_id_fkey\"" task_name="resolve partition" backoff_secs=3 target="backoff" location="backoff/src/lib.rs:179" time=1680596814126240926
level=warn msg="request encountered non-fatal error - backing off" error="foreign key violation: error returned from database: insert or update on table \"partition\" violates foreign key constraint \"partition_table_id_fkey\"" task_name="resolve partition" backoff_secs=7 target="backoff" location="backoff/src/lib.rs:179" time=1680596817323675145
thread 'tokio-runtime-worker' panicked at 'resolving namespace name for non-existent namespace id 154', ingester2/src/buffer_tree/namespace/name_resolver.rs:55:25
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
   2: ingester2::buffer_tree::namespace::name_resolver::NamespaceNameResolver::fetch::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at ./influxdb_iox/ingester2/src/buffer_tree/namespace/name_resolver.rs:55:25
   3: core::option::Option<T>::unwrap_or_else
             at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/option.rs:873:21
   4: ingester2::buffer_tree::namespace::name_resolver::NamespaceNameResolver::fetch::{{closure}}::{{closure}}::{{closure}}
             at ./influxdb_iox/ingester2/src/buffer_tree/namespace/name_resolver.rs:45:25
   5: backoff::Backoff::retry_all_errors::{{closure}}::{{closure}}::{{closure}}
             at ./influxdb_iox/backoff/src/lib.rs:205:31
   6: backoff::Backoff::retry_with_backoff::{{closure}}
             at ./influxdb_iox/backoff/src/lib.rs:164:35
   7: backoff::Backoff::retry_all_errors::{{closure}}
             at ./influxdb_iox/backoff/src/lib.rs:211:9
   8: ingester2::buffer_tree::namespace::name_resolver::NamespaceNameResolver::fetch::{{closure}}
             at ./influxdb_iox/ingester2/src/buffer_tree/namespace/name_resolver.rs:64:13
   9: ingester2::deferred_load::DeferredLoad<T>::new::{{closure}}
             at ./influxdb_iox/ingester2/src/deferred_load.rs:197:31
  10: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  11: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/core.rs:223:17
  12: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/loom/std/unsafe_cell.rs:14:9
  13: tokio::runtime::task::core::Core<T,S>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/core.rs:212:13
  14: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/harness.rs:476:19
  15: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panic/unwind_safe.rs:271:9
  16: std::panicking::try::do_call
             at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:483:40
  17: std::panicking::try
             at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:447:19
  18: std::panic::catch_unwind
             at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panic.rs:140:14
  19: tokio::runtime::task::harness::poll_future
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/harness.rs:464:18
  20: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/harness.rs:198:27
  21: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/harness.rs:152:15
  22: tokio::runtime::task::raw::RawTask::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/raw.rs:200:18
  23: tokio::runtime::task::LocalNotified<S>::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/mod.rs:394:9
  24: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:464:13
  25: tokio::runtime::coop::with_budget
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:107:5
  26: tokio::runtime::coop::budget
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:73:5
  27: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:463:9
  28: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:426:24
  29: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:406:17
  30: tokio::macros::scoped_tls::ScopedKey<T>::set
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/macros/scoped_tls.rs:61:9
  31: tokio::runtime::scheduler::multi_thread::worker::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:403:5
  32: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:365:45
  33: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/blocking/task.rs:42:21
  34: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  35: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/core.rs:223:17
  36: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/loom/std/unsafe_cell.rs:14:9
  37: tokio::runtime::task::core::Core<T,S>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/core.rs:212:13
  38: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/harness.rs:476:19
  39: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panic/unwind_safe.rs:271:9
  40: std::panicking::try::do_call
             at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:483:40
  41: std::panicking::try
             at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:447:19
  42: std::panic::catch_unwind
             at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panic.rs:140:14
  43: tokio::runtime::task::harness::poll_future
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/harness.rs:464:18
  44: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/harness.rs:198:27
  45: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/harness.rs:152:15
  46: tokio::runtime::task::raw::RawTask::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/raw.rs:200:18
  47: tokio::runtime::task::UnownedTask<S>::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/mod.rs:431:9
  48: tokio::runtime::blocking::pool::Task::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/blocking/pool.rs:159:9
  49: tokio::runtime::blocking::pool::Inner::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/blocking/pool.rs:513:17
  50: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/blocking/pool.rs:471:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The pod is now crash-looping.

**Comment by domodwyer** [comment]
Can you elaborate? Why/how was the namespace deleted? Namespaces cannot be hard deleted (i.e. `DELETE FROM namespace`) least they blow everything up when each service goes looking for the catalog entries.

**Comment by domodwyer** [comment]
It is unclear how this happened - it might have been a bug, but it seems more likely the staging database has been tweaked.

I'll close this as it's expected behaviour to crash in the presence of hard catalog entry deletes for all of IOx (https://github.com/influxdata/idpe/issues/17043).
