### ISSUE TITLE
Error while planning query: projection_pushdown\ncaused by\nInternal error: The data type inlist should be same

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#7644]
__Steps to reproduce:__
Write the following data into IOx:
```
                        r#"checks,id=1,method=POST,name=Writes,url="https://example.com",user_id=1 elapsed=66909i,status=204i 1678578528255989730"#,
                        r#"checks,id=1,method=POST,name=Writes,url="https://example.com",user_id=1 elapsed=112928i,status=204i 1678578532192972168"#,
                        r#"checks,id=1,method=POST,name=Writes,url="https://example.com",user_id=1 elapsed=147683i,status=204i 1678578588416052133"#,
                        r#"checks,id=1,method=POST,name=Writes,url="https://example.com",user_id=1 elapsed=78000i,status=204i 1678578592147893402"#,

```
Wait for the data to be persisted to parquet

The run this query:

```sql
SELECT id FROM checks WHERE id in ('2','3','4','5');
```

__Expected behaviour:__
Query should return 4 rows successfully

__Actual behaviour:__
Error while planning query: projection_pushdown\ncaused by\nInternal error: The data type inlist should be same, the value type is Int64, one of list expr type is Dictionary(Int32, Utf8). This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker

__Environment info:__

* Please provide the command you used to build the project, including any `RUSTFLAGS`.
* System info: Run `uname -srm` or similar and copy the output here (we want to know your OS, architecture etc).
* If you're running IOx in a containerised environment then details about that would be helpful.
* Other relevant environment details: disk info, hardware setup etc.

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in logs or stack traces here.
Sometimes you can get useful information by running the program with the `RUST_BACKTRACE=full` environment variable.
Finally, the IOx server has a `-vv` for verbose logging.

**Comment by alamb** [comment]
BTW here is a stack trace of the error:

```
2023-04-24T18:43:00.090858Z ERROR panic_logging: Thread panic panic_info=panicked at 'in the disco', /Users/alamb/Software/arrow-datafusion/datafusion/physical-expr/src/expressions/in_list.rs:361:13
thread 'IOx Query 1' panicked at 'in the disco', /Users/alamb/Software/arrow-datafusion/datafusion/physical-expr/src/expressions/in_list.rs:361:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
   2: datafusion_physical_expr::expressions::in_list::in_list
             at /Users/alamb/Software/arrow-datafusion/datafusion/physical-expr/src/expressions/in_list.rs:361:13
   3: <datafusion_physical_expr::expressions::in_list::InListExpr as datafusion_physical_expr::physical_expr::PhysicalExpr>::with_new_children
             at /Users/alamb/Software/arrow-datafusion/datafusion/physical-expr/src/expressions/in_list.rs:327:9
   4: datafusion_physical_expr::physical_expr::with_new_children_if_necessary
             at /Users/alamb/Software/arrow-datafusion/datafusion/physical-expr/src/physical_expr.rs:256:9
   5: datafusion_physical_expr::tree_node::<impl datafusion_common::tree_node::DynTreeNode for dyn datafusion_physical_expr::physical_expr::PhysicalExpr>::with_new_arc_children
             at /Users/alamb/Software/arrow-datafusion/datafusion/physical-expr/src/tree_node.rs:35:9
   6: <alloc::sync::Arc<T> as datafusion_common::tree_node::TreeNode>::map_children
             at /Users/alamb/Software/arrow-datafusion/datafusion/common/src/tree_node.rs:332:13
   7: datafusion_common::tree_node::TreeNode::transform_up
             at /Users/alamb/Software/arrow-datafusion/datafusion/common/src/tree_node.rs:123:33
   8: datafusion_common::tree_node::TreeNode::transform
             at /Users/alamb/Software/arrow-datafusion/datafusion/common/src/tree_node.rs:102:9
   9: datafusion_physical_expr::utils::reassign_predicate_columns
             at /Users/alamb/Software/arrow-datafusion/datafusion/physical-expr/src/utils.rs:583:5
  10: iox_query::physical_optimizer::projection_pushdown::ProjectionPushdown::optimize_impl::{{closure}}::{{closure}}
             at ./iox_query/src/physical_optimizer/projection_pushdown.rs:168:33
  11: iox_query::physical_optimizer::projection_pushdown::wrap_user_into_projections
             at ./iox_query/src/physical_optimizer/projection_pushdown.rs:385:12
  12: iox_query::physical_optimizer::projection_pushdown::ProjectionPushdown::optimize_impl::{{closure}}
             at ./iox_query/src/physical_optimizer/projection_pushdown.rs:162:32
  13: datafusion_common::tree_node::TreeNode::transform_down
             at /Users/alamb/Software/arrow-datafusion/datafusion/common/src/tree_node.rs:112:24
  14: datafusion_common::tree_node::TreeNode::transform_down::{{closure}}
             at /Users/alamb/Software/arrow-datafusion/datafusion/common/src/tree_node.rs:113:38
  15: core::iter::adapters::map::map_try_fold::{{closure}}
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/iter/adapters/map.rs:91:28
  16: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/iter/traits/iterator.rs:2262:21
  17: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/iter/adapters/map.rs:117:9
  18: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/iter/adapters/mod.rs:195:9
  19: <I as alloc::vec::in_place_collect::SpecInPlaceCollect<T,I>>::collect_in_place
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/vec/in_place_collect.rs:257:13
  20: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/vec/in_place_collect.rs:181:19
  21: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/vec/mod.rs:2753:9
  22: core::iter::traits::iterator::Iterator::collect
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/iter/traits/iterator.rs:1860:9
  23: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter::{{closure}}
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/result.rs:2074:51
  24: core::iter::adapters::try_process
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/iter/adapters/mod.rs:164:17
  25: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/result.rs:2074:9
  26: core::iter::traits::iterator::Iterator::collect
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/iter/traits/iterator.rs:1860:9
  27: <alloc::sync::Arc<T> as datafusion_common::tree_node::TreeNode>::map_children
             at /Users/alamb/Software/arrow-datafusion/datafusion/common/src/tree_node.rs:330:17
  28: datafusion_common::tree_node::TreeNode::transform_down
             at /Users/alamb/Software/arrow-datafusion/datafusion/common/src/tree_node.rs:113:9
  29: iox_query::physical_optimizer::projection_pushdown::ProjectionPushdown::optimize_impl
             at ./iox_query/src/physical_optimizer/projection_pushdown.rs:65:9
  30: <iox_query::physical_optimizer::projection_pushdown::ProjectionPushdown as datafusion::physical_optimizer::optimizer::PhysicalOptimizerRule>::optimize
             at ./iox_query/src/physical_optimizer/projection_pushdown.rs:44:19
  31: datafusion::physical_plan::planner::DefaultPhysicalPlanner::optimize_internal
             at /Users/alamb/Software/arrow-datafusion/datafusion/core/src/physical_plan/planner.rs:1827:24
  32: <datafusion::physical_plan::planner::DefaultPhysicalPlanner as datafusion::physical_plan::planner::PhysicalPlanner>::create_physical_plan::{{closure}}
             at /Users/alamb/Software/arrow-datafusion/datafusion/core/src/physical_plan/planner.rs:427:17
  33: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/future/future.rs:125:9
  34: <iox_query::exec::context::IOxQueryPlanner as datafusion::execution::context::QueryPlanner>::create_physical_plan::{{closure}}
             at ./iox_query/src/exec/context.rs:87:13
  35: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/future/future.rs:125:9
  36: datafusion::execution::context::SessionState::create_physical_plan::{{closure}}
             at /Users/alamb/Software/arrow-datafusion/datafusion/core/src/execution/context.rs:1724:13
  37: iox_query::exec::context::IOxSessionContext::create_physical_plan::{{closure}}
             at ./iox_query/src/exec/context.rs:400:81
  38: iox_query::exec::context::IOxSessionContext::sql_to_physical_plan::{{closure}}
             at ./iox_query/src/exec/context.rs:366:48
  39: iox_query::frontend::sql::SqlQueryPlanner::query::{{closure}}
             at ./iox_query/src/frontend/sql.rs:22:40
  40: service_common::planner::Planner::sql::{{closure}}::{{closure}}
             at ./service_common/src/planner.rs:46:58
  41: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panic/unwind_safe.rs:296:9
  42: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll::{{closure}}
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/future/catch_unwind.rs:36:42
  43: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panic/unwind_safe.rs:271:9
  44: std::panicking::try::do_call
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:483:40
  45: ___rust_try
  46: std::panicking::try
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:447:19
  47: std::panic::catch_unwind
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panic.rs:140:14
  48: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/future/catch_unwind.rs:36:9
  49: executor::DedicatedExecutor::spawn::{{closure}}
             at ./executor/src/lib.rs:288:68
  50: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/future/future.rs:125:9
  51: executor::Task::run::{{closure}}::{{closure}}
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/macros/select.rs:524:49
  52: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/future/poll_fn.rs:58:9
  53: executor::Task::run::{{closure}}
             at ./executor/src/lib.rs:54:9
  54: executor::DedicatedExecutor::new_inner::{{closure}}::{{closure}}::{{closure}}
             at ./executor/src/lib.rs:235:39
  55: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/task/core.rs:223:17
  56: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/loom/std/unsafe_cell.rs:14:9
  57: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/task/core.rs:212:13
  58: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/task/harness.rs:476:19
  59: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panic/unwind_safe.rs:271:9
  60: std::panicking::try::do_call
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:483:40
  61: ___rust_try
  62: std::panicking::try
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:447:19
  63: std::panic::catch_unwind
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panic.rs:140:14
  64: tokio::runtime::task::harness::poll_future
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/task/harness.rs:464:18
  65: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/task/harness.rs:198:27
  66: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/task/harness.rs:152:15
  67: tokio::runtime::task::raw::poll
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/task/raw.rs:255:5
  68: tokio::runtime::task::raw::RawTask::poll
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/task/raw.rs:200:18
  69: tokio::runtime::task::LocalNotified<S>::run
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/task/mod.rs:394:9
  70: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:464:13
  71: tokio::runtime::coop::with_budget
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/coop.rs:107:5
  72: tokio::runtime::coop::budget
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/coop.rs:73:5
  73: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:463:9
  74: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:426:24
  75: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:406:17
  76: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/macros/scoped_tls.rs:61:9
  77: tokio::runtime::scheduler::multi_thread::worker::run
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:403:5
  78: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:365:45
  79: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/blocking/task.rs:42:21
  80: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/task/core.rs:223:17
  81: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/loom/std/unsafe_cell.rs:14:9
  82: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/task/core.rs:212:13
  83: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/task/harness.rs:476:19
  84: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panic/unwind_safe.rs:271:9
  85: std::panicking::try::do_call
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:483:40
  86: ___rust_try
  87: std::panicking::try
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:447:19
  88: std::panic::catch_unwind
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panic.rs:140:14
  89: tokio::runtime::task::harness::poll_future
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/task/harness.rs:464:18
  90: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/task/harness.rs:198:27
  91: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/alamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/task/harness.rs:152:15
```

It appears to be happening via `iox_query::physical_optimizer::projection_pushdown::ProjectionPushdown::optimize_impl` (though that is calling some function in DataFusion)

**Comment by alamb** [comment]
Here is the input plan:

```
  UnionExec
    FilterExec: Use id@1 IN (SET) ([Literal { value: Dictionary(Int32, Utf8("2")) }, Literal { value: Dictionary(Int32, Utf8("3")) }, Literal { value: Dictionary(Int32, Utf8("4")) }, Literal { value: Dictionary(Int32, Utf8("5")) }])
      ParquetExec: limit=None, partitions={1 group: [[8/29/1/243/62f8376d-1108-4118-9412-67a535f09288.parquet]]}, predicate=Use id@1 IN (SET) ([Literal { value: Dictionary(Int32, Utf8("2")) }, Literal { value: Dictionary(Int32, Utf8("3")) }, Literal { value: Dictionary(Int32, Utf8("4")) }, Literal { value: Dictionary(Int32, Utf8("5")) }]), pruning_predicate=id_min@0 <= 2 AND 2 <= id_max@1 OR id_min@0 <= 3 AND 3 <= id_max@1 OR id_min@0 <= 4 AND 4 <= id_max@1 OR id_min@0 <= 5 AND 5 <= id_max@1, output_ordering=[id@1 ASC, method@2 ASC, name@3 ASC, url@6 ASC, user_id@7 ASC, time@5 ASC, __chunk_order@8 ASC], projection=[elapsed, id, method, name, status, time, url, user_id, __chunk_order]

```

**Comment by alamb** [comment]
I confirm that https://github.com/apache/arrow-datafusion/pull/6114 fixes the problem -- there is a regression test in https://github.com/influxdata/influxdb_iox/pull/7645
