### ISSUE TITLE
jdb_client fails when querying server on https

### ISSUE THREAD

**Issue by mkmik** [influxdata/influxdb_iox#7854]
__Steps to reproduce:__

```console
$ ./jdbc_client "jdbc:arrow-flight-sql://redacted.a.influxdb.io:443?useEncryption=true&database=foo" query 'show tables'
```

__Expected behaviour:__

The query to work or at least an error coming from IOx (e.g. permission denied in this example since I intentionally omitted the token)

__Actual behaviour:__

```
make: `flight-sql-jdbc-driver-10.0.0.jar' is up to date.
total 68808
-rw-r--r--  1 mkm  staff        76 Jan 26 16:44 flight-sql-jdbc-driver-10.0.0.jar.sha
-rw-r--r--  1 mkm  staff       599 Apr 17 13:00 README.md
-rw-r--r--  1 mkm  staff     19716 May 18 17:51 Main.java
-rw-r--r--  1 mkm  staff       385 May 18 17:51 Makefile
-rwxr-xr-x  1 mkm  staff       803 May 18 17:51 jdbc_client
-rw-r--r--  1 mkm  staff     19592 May 23 15:30 Main.class
-rw-r--r--  1 mkm  staff  35168799 May 23 15:31 flight-sql-jdbc-driver-10.0.0.jar
make: `Main.class' is up to date.
InfluxDB IOx JDCB Test Driver
----- Running SQL Query -------
query: show tables
----- Connecting -------
URL: jdbc:arrow-flight-sql://redacted.a.influxdb.io:443?useEncryption=true&database=foo
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.sql.SQLException: java.lang.IllegalArgumentException: Input stream does not contain valid certificates.
	at org.apache.arrow.driver.jdbc.client.ArrowFlightSqlClientHandler$Builder.build(ArrowFlightSqlClientHandler.java:584)
	at org.apache.arrow.driver.jdbc.ArrowFlightConnection.createNewClientHandler(ArrowFlightConnection.java:109)
	at org.apache.arrow.driver.jdbc.ArrowFlightConnection.createNewConnection(ArrowFlightConnection.java:88)
	at org.apache.arrow.driver.jdbc.ArrowFlightJdbcDriver.connect(ArrowFlightJdbcDriver.java:80)
	at org.apache.arrow.driver.jdbc.ArrowFlightJdbcDriver.connect(ArrowFlightJdbcDriver.java:48)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:191)
	at Main.connect(Main.java:93)
	at Main.run_query(Main.java:100)
	at Main.main(Main.java:50)
Caused by: java.lang.IllegalArgumentException: Input stream does not contain valid certificates.
	at cfjd.io.netty.handler.ssl.SslContextBuilder.trustManager(SslContextBuilder.java:276)
	at cfjd.org.apache.arrow.flight.FlightClient$Builder.build(FlightClient.java:701)
	at org.apache.arrow.driver.jdbc.client.ArrowFlightSqlClientHandler$Builder.build(ArrowFlightSqlClientHandler.java:572)
	... 9 more
Caused by: java.security.cert.CertificateException: found no certificates in input stream
	at cfjd.io.netty.handler.ssl.PemReader.readCertificates(PemReader.java:107)
	at cfjd.io.netty.handler.ssl.SslContext.toX509Certificates(SslContext.java:1226)
	at cfjd.io.netty.handler.ssl.SslContextBuilder.trustManager(SslContextBuilder.java:274)
	... 11 more
```

__Environment info:__

* System info: `Darwin 21.6.0 arm64`

**Comment by alamb** [comment]
FWIW the `jdbc_client` is a program we wrote for unit testing. I wonder if you could try something like https://github.com/julianhyde/sqlline to see if it is related to `jdbc_client` or something abotu the JDBC driver itself

**Comment by mkmik** [comment]
as discovered by @appletreeisyellow, we can work around it by adding `useSystemTrustStore=false`; I'm not sure exactly what does that do though

**Comment by mhilton** [comment]
I have delved deeper and this is a JDBC driver problem (https://github.com/apache/arrow/issues/35741). The good news is that it is only a problem on MacOS. Linux works fine (what's that, windows? no never heard of it).

I think there is a less insecure, but much more fiddly work around possible though.

**Comment by mhilton** [comment]
The workaround for MacOS users is to create a trust store containing the let's encrypt root key and use that. To do this run the following:

```
$ curl -o isrgrootx1.pem https://letsencrypt.org/certs/isrgrootx1.pem
$ openssl pkcs12 -export -in isrgrootx1.pem	-out isrgrootx1.pkcs12 -nokeys -passout pass:
```

Then add the parameters `&useSystemTrustStore=false&trustStorePath=isrgrootx1.pkcs12&trustStorePassword=` to the DSN URL.

To save everyone some time I've attached a pkcds12 file that can be used.

[isrgrootx1.pkcs12.gz](https://github.com/influxdata/influxdb_iox/files/11556639/isrgrootx1.pkcs12.gz)

**Comment by mhilton** [comment]
Further reading of the JDBC driver code, however, suggest that it is sufficient to just set the `&userSystemTrustStore=false` parameter. That doesn't disable server certificate validation, It just doesn't attempt to load any CA certificates. This probably results in the system using the default CA certificates without needing to load them specially.

**Comment by mkmik** [comment]
Is that the same as https://github.com/influxdata/influxdb_iox/issues/7854#issuecomment-1560085585

or is it "user" with an r instead of "use" ?

**Comment by mhilton** [comment]
> Is that the same as https://github.com/influxdata/influxdb_iox/issues/7854#issuecomment-1560085585
> 
> or is it "user" with an r instead of "use" ?

It was supposed to be "use". I've fixed the comment to avoid confusion.
