### ISSUE TITLE
Flaky test: end_to_end_cases::debug::build_catalog

### ISSUE THREAD

**Issue by carols10cents** [influxdata/influxdb_iox#8203]
Test added in https://github.com/influxdata/influxdb_iox/pull/8067

Here are some examples of this test failing then passing in CI without any code changes:

- On https://github.com/influxdata/influxdb_iox/pull/8083:
  - [Test failed](https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/35377/workflows/1a6249e4-cb1f-4f8f-97cb-ac54ff594488/jobs/332424) at commit [e958993](https://github.com/influxdata/influxdb_iox/commit/e958993dae92b15678a34c45036e8e1e410ff1a9)
  - I reran from failed and then the [test passed](https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/35377/workflows/afd343cd-96ba-4d2b-bbf9-8c7101a0d99c/jobs/332448), also at[e958993](https://github.com/influxdata/influxdb_iox/commit/e958993dae92b15678a34c45036e8e1e410ff1a9)
- On https://github.com/influxdata/influxdb_iox/pull/8187: 
	- [Test failed](https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/35379/workflows/d16ae7dd-0022-41d5-a799-102d6b1008ff/jobs/332440) at commit [395efe5](https://github.com/influxdata/influxdb_iox/commit/395efe579838556c7b28942969e5f52e2013e787)
	- [Test passed](https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/35379/workflows/38f23d3c-0607-4e88-95a4-b0c91e2aa98e/jobs/332460), also at [395efe5](https://github.com/influxdata/influxdb_iox/commit/395efe579838556c7b28942969e5f52e2013e787)

<details>
<summary>Test failure message</summary>

```
---- end_to_end_cases::debug::build_catalog stdout ----
2023-07-10T15:48:20.646836Z DEBUG test_helpers_end_to_end::mini_cluster: creating standard cluster mutex_wait=30.573µs
2023-07-10T15:48:20.646890Z DEBUG test_helpers_end_to_end::mini_cluster: Reusing existing cluster
2023-07-10T15:48:20.646985Z  INFO test_helpers_end_to_end::server_fixture: Creating gRPC channel to http://127.0.0.1:8119
2023-07-10T15:48:20.647136Z DEBUG hyper::client::connect::http: connecting to 127.0.0.1:8119
2023-07-10T15:48:20.647288Z DEBUG hyper::client::connect::http: connected to 127.0.0.1:8119
2023-07-10T15:48:20.647810Z  INFO test_helpers_end_to_end::server_fixture: Creating gRPC channel to http://127.0.0.1:8102
2023-07-10T15:48:20.647876Z DEBUG hyper::client::connect::http: connecting to 127.0.0.1:8102
2023-07-10T15:48:20.648017Z DEBUG hyper::client::connect::http: connected to 127.0.0.1:8102
2023-07-10T15:48:20.648575Z  INFO test_helpers_end_to_end::server_fixture: Creating gRPC channel to http://127.0.0.1:8130
2023-07-10T15:48:20.648651Z DEBUG hyper::client::connect::http: connecting to 127.0.0.1:8130
2023-07-10T15:48:20.648865Z DEBUG hyper::client::connect::http: connected to 127.0.0.1:8130
2023-07-10T15:48:20.649415Z  INFO test_helpers_end_to_end::mini_cluster: created new mini cluster from existing cluster total_wait=2.514251ms
2023-07-10T15:48:20.649438Z  INFO test_helpers_end_to_end::steps: **** Begin step 0 *****
2023-07-10T15:48:20.649528Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:20.653200Z  INFO test_helpers_end_to_end::steps: Recorded count of Parquet files for namespace 1049693198425623_4438048291302141: 0
2023-07-10T15:48:20.653213Z  INFO test_helpers_end_to_end::steps: **** Begin step 1 *****
2023-07-10T15:48:20.653219Z  INFO test_helpers_end_to_end::steps: ====Begin writing line protocol to v2 HTTP API:
my_awesome_table,tag1=C,tag2=D val=43i 123456
2023-07-10T15:48:20.653304Z DEBUG hyper::client::connect::http: connecting to 127.0.0.1:8118
2023-07-10T15:48:20.653426Z DEBUG hyper::client::connect::http: connected to 127.0.0.1:8118
2023-07-10T15:48:20.668067Z DEBUG hyper::client::pool: pooling idle connection for ("http", 127.0.0.1:8118)
2023-07-10T15:48:20.668149Z  INFO test_helpers_end_to_end::steps: ====Done writing line protocol
2023-07-10T15:48:20.668160Z  INFO test_helpers_end_to_end::steps: **** Begin step 2 *****
2023-07-10T15:48:20.668166Z  INFO test_helpers_end_to_end::steps: ====Begin waiting for a change in the number of Parquet files
2023-07-10T15:48:20.668381Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:20.671935Z  INFO test_helpers_end_to_end::steps: Retrying; Parquet file count is still 0 which is less than 1
2023-07-10T15:48:20.672045Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:20.675140Z  INFO test_helpers_end_to_end::steps: Retrying; Parquet file count is still 0 which is less than 1
2023-07-10T15:48:21.669437Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:21.672587Z  INFO test_helpers_end_to_end::steps: Retrying; Parquet file count is still 0 which is less than 1
2023-07-10T15:48:22.669582Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:22.673762Z  INFO test_helpers_end_to_end::steps: Retrying; Parquet file count is still 0 which is less than 1
2023-07-10T15:48:23.669381Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:23.673464Z  INFO test_helpers_end_to_end::steps: Retrying; Parquet file count is still 0 which is less than 1
2023-07-10T15:48:24.669487Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:24.673273Z  INFO test_helpers_end_to_end::steps: Retrying; Parquet file count is still 0 which is less than 1
2023-07-10T15:48:25.669710Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:25.677357Z  INFO test_helpers_end_to_end::steps: Success; Parquet file count is now 1 which is at least 1
2023-07-10T15:48:25.677389Z  INFO test_helpers_end_to_end::steps: ====Done waiting for a change in the number of Parquet files
2023-07-10T15:48:25.677398Z  INFO test_helpers_end_to_end::steps: **** Begin step 3 *****
2023-07-10T15:48:25.677405Z  INFO test_helpers_end_to_end::steps: ====Begin running SQL query: select tag1, tag2, val from my_awesome_table
2023-07-10T15:48:25.677533Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:25.679783Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:25.745778Z  INFO test_helpers_end_to_end::steps: ====Done running
2023-07-10T15:48:25.745817Z  INFO test_helpers_end_to_end::steps: **** Begin step 4 *****
2023-07-10T15:48:25.745823Z  INFO test_helpers_end_to_end::steps: ====Begin custom step
Input directory: "/tmp/.tmpHbWLZY/my_awesome_table"
target_directory: TempDir { path: "/tmp/.tmpLFlvyi" }
Completed rebuild in TempDir { path: "/tmp/.tmpLFlvyi" }
2023-07-10T15:48:26.910885Z  INFO test_helpers_end_to_end::server_fixture: ****************
2023-07-10T15:48:26.910915Z  INFO test_helpers_end_to_end::server_fixture: Server AllInOne Logging to "/tmp/.tmpPERuGC"
2023-07-10T15:48:26.910924Z  INFO test_helpers_end_to_end::server_fixture: ****************
2023-07-10T15:48:26.911104Z  INFO test_helpers_end_to_end: Running command: `INFLUXDB_IOX_COMPACTOR_GRPC_BIND_ADDR=127.0.0.1:8241 INFLUXDB_IOX_DB_DIR=/tmp/.tmpLFlvyi INFLUXDB_IOX_INGESTER_GRPC_BIND_ADDR=127.0.0.1:8240 INFLUXDB_IOX_QUERIER_GRPC_BIND_ADDR=127.0.0.1:8239 INFLUXDB_IOX_ROUTER_GRPC_BIND_ADDR=127.0.0.1:8238 INFLUXDB_IOX_ROUTER_HTTP_BIND_ADDR=127.0.0.1:8237 LOG_FILTER=debug,,hyper::proto::h1=info,h2=info INFLUXDB_IOX_COMPACTOR_GRPC_BIND_ADDR="127.0.0.1:8241" INFLUXDB_IOX_DB_DIR="/tmp/.tmpLFlvyi" INFLUXDB_IOX_INGESTER_GRPC_BIND_ADDR="127.0.0.1:8240" INFLUXDB_IOX_QUERIER_GRPC_BIND_ADDR="127.0.0.1:8239" INFLUXDB_IOX_ROUTER_GRPC_BIND_ADDR="127.0.0.1:8238" INFLUXDB_IOX_ROUTER_HTTP_BIND_ADDR="127.0.0.1:8237" LOG_FILTER="debug,,hyper::proto::h1=info,h2=info" "/home/rust/project/target/debug/influxdb_iox" "run" "all-in-one"`
2023-07-10T15:48:26.911579Z  INFO test_helpers_end_to_end::server_fixture: Creating gRPC channel to http://127.0.0.1:8238
2023-07-10T15:48:26.911773Z DEBUG hyper::client::connect::http: connecting to 127.0.0.1:8238
2023-07-10T15:48:26.912086Z  INFO test_helpers_end_to_end::server_fixture: wait_until_ready: can not yet connect: Cannot connect to router at http://127.0.0.1:8238: Connection error: transport error (error trying to connect: tcp connect error: Connection refused (os error 111))
2023-07-10T15:48:26.912121Z  INFO test_helpers_end_to_end::server_fixture: Creating gRPC channel to http://127.0.0.1:8238
2023-07-10T15:48:26.912189Z DEBUG hyper::client::connect::http: connecting to 127.0.0.1:8238
2023-07-10T15:48:26.912341Z  INFO test_helpers_end_to_end::server_fixture: wait_until_ready: can not yet connect: Cannot connect to router at http://127.0.0.1:8238: Connection error: transport error (error trying to connect: tcp connect error: Connection refused (os error 111))
2023-07-10T15:48:27.012731Z  INFO test_helpers_end_to_end::server_fixture: Creating gRPC channel to http://127.0.0.1:8238
2023-07-10T15:48:27.012876Z DEBUG hyper::client::connect::http: connecting to 127.0.0.1:8238
2023-07-10T15:48:27.013117Z  INFO test_helpers_end_to_end::server_fixture: wait_until_ready: can not yet connect: Cannot connect to router at http://127.0.0.1:8238: Connection error: transport error (error trying to connect: tcp connect error: Connection refused (os error 111))
2023-07-10T15:48:27.112468Z  INFO test_helpers_end_to_end::server_fixture: Creating gRPC channel to http://127.0.0.1:8238
2023-07-10T15:48:27.112632Z DEBUG hyper::client::connect::http: connecting to 127.0.0.1:8238
2023-07-10T15:48:27.112843Z DEBUG hyper::client::connect::http: connected to 127.0.0.1:8238
2023-07-10T15:48:27.113463Z  INFO test_helpers_end_to_end::server_fixture: Creating gRPC channel to http://127.0.0.1:8240
2023-07-10T15:48:27.113555Z DEBUG hyper::client::connect::http: connecting to 127.0.0.1:8240
2023-07-10T15:48:27.113710Z DEBUG hyper::client::connect::http: connected to 127.0.0.1:8240
2023-07-10T15:48:27.114292Z  INFO test_helpers_end_to_end::server_fixture: Creating gRPC channel to http://127.0.0.1:8239
2023-07-10T15:48:27.114376Z DEBUG hyper::client::connect::http: connecting to 127.0.0.1:8239
2023-07-10T15:48:27.114618Z DEBUG hyper::client::connect::http: connected to 127.0.0.1:8239
2023-07-10T15:48:27.115514Z DEBUG reqwest::connect: starting new connection: http://127.0.0.1:8237/    
2023-07-10T15:48:27.115583Z DEBUG hyper::client::connect::http: connecting to 127.0.0.1:8237
2023-07-10T15:48:27.115913Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:27.116338Z DEBUG hyper::client::connect::http: connected to 127.0.0.1:8237
2023-07-10T15:48:27.118167Z  INFO test_helpers_end_to_end::server_fixture: CatalogService service AllInOne is running
2023-07-10T15:48:27.118427Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:27.118826Z DEBUG hyper::client::pool: pooling idle connection for ("http", 127.0.0.1:8237)
2023-07-10T15:48:27.118889Z  INFO test_helpers_end_to_end::server_fixture: Successfully got a response from AllInOne HTTP: Response { url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(127.0.0.1)), port: Some(8237), path: "/health", query: None, fragment: None }, status: 200, headers: {"content-length": "2", "date": "Mon, 10 Jul 2023 15:48:27 GMT"} }
2023-07-10T15:48:27.120248Z  INFO test_helpers_end_to_end::server_fixture: Flight service AllInOne is running
2023-07-10T15:48:27.120340Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:27.122099Z  INFO test_helpers_end_to_end::server_fixture: Flight service AllInOne is running
2023-07-10T15:48:27.122120Z  INFO test_helpers_end_to_end::server_fixture: Successfully started TestServer AllInOne (router_http: 127.0.0.1:8237 router_grpc: 127.0.0.1:8238 querier_grpc: 127.0.0.1:8239 ingester_grpc: 127.0.0.1:8240 compactor_grpc: 127.0.0.1:8241 )
2023-07-10T15:48:27.122250Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:27.123398Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:27.294126Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:27.295795Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:27.450054Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:27.451661Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:27.605968Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:27.607556Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:27.762012Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:27.763652Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:27.918098Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:27.919962Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:28.074146Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:28.075786Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:28.230107Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:28.232076Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:28.390107Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:28.391990Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:28.546029Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:28.547745Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:28.702089Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:28.703840Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:28.858020Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:28.859913Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:29.014030Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-10T15:48:29.016026Z DEBUG tower::buffer::worker: service.ready=true processing request
thread 'end_to_end_cases::debug::build_catalog' panicked at 'timed out waiting for non-empty batches in result: Elapsed(())', influxdb_iox/tests/end_to_end_cases/debug.rs:111:26
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:1687:5
   3: core::result::Result<T,E>::expect
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:1046:23
   4: end_to_end::end_to_end_cases::debug::build_catalog::{{closure}}::{{closure}}::{{closure}}
             at ./tests/end_to_end_cases/debug.rs:108:35
   5: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/future/future.rs:125:9
   6: test_helpers_end_to_end::steps::StepTest<S>::run::{{closure}}
             at /home/rust/project/test_helpers_end_to_end/src/steps.rs:618:34
   7: end_to_end::end_to_end_cases::debug::build_catalog::{{closure}}
             at ./tests/end_to_end_cases/debug.rs:129:5
   8: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/future/future.rs:125:9
   9: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  10: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/future/future.rs:125:9
  11: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:651:57
  12: tokio::runtime::coop::with_budget
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/coop.rs:107:5
  13: tokio::runtime::coop::budget
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/coop.rs:73:5
  14: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:651:25
  15: tokio::runtime::scheduler::current_thread::Context::enter
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:410:19
  16: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:650:36
  17: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:729:68
  18: tokio::runtime::context::scoped::Scoped<T>::set
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context/scoped.rs:40:9
  19: tokio::runtime::context::set_scheduler::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context.rs:176:26
  20: std::thread::local::LocalKey<T>::try_with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:252:16
  21: std::thread::local::LocalKey<T>::with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:228:9
  22: tokio::runtime::context::set_scheduler
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context.rs:176:9
  23: tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:729:27
  24: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:638:19
  25: tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:175:28
  26: tokio::runtime::context::runtime::enter_runtime
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context/runtime.rs:65:16
  27: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:167:9
  28: tokio::runtime::runtime::Runtime::block_on
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/runtime.rs:311:47
  29: end_to_end::end_to_end_cases::debug::build_catalog
             at ./tests/end_to_end_cases/debug.rs:66:5
  30: end_to_end::end_to_end_cases::debug::build_catalog::{{closure}}
             at ./tests/end_to_end_cases/debug.rs:50:26
  31: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
  32: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace
```

</details>

**Comment by alamb** [comment]
will fix -- thansks @carols10cents

**Comment by alamb** [comment]
Note this looks similar to https://github.com/influxdata/influxdb_iox/issues/8200 which @savage-engineer  made a fix yesterday. However, your reported message  seems like it also includes that fix

**Comment by alamb** [comment]
I ran this test 250 times in a loop locally and it passed every time. I suspect the CI machine is just a little slower and needs the timeout extended. However, to test this theory I am going to try and run the test in parallel (to slow it down) and see if I can trigger the same problem

**Comment by carols10cents** [comment]
I SWEAR I LOOKED FOR OPEN ISSUES BEFORE OPENING THIS ONE i don't know how I missed https://github.com/influxdata/influxdb_iox/issues/8200

**Comment by alamb** [comment]
Well, it is still a problem so a second ticket is definitely warranted

**Comment by alamb** [comment]
I have made a PR to add more debug logging: https://github.com/influxdata/influxdb_iox/pull/8224

**Comment by alamb** [comment]
My plan for debugging this is to get a circle CI job running under SSH mode and try and reproduce the error there to debug further

For example, this https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/35682/workflows/a1c914e8-85b9-4540-8aa7-36d11ad18a86/jobs/335882

I can reproduce it with this  shell script

```
cd project
export PATH="$PATH:/usr/local/cargo/bin"
cargo test --test end_to_end -- end_to_end_cases::debug::build_catalog --include-ignored 
```

**Comment by alamb** [comment]
I tried setting https://docs.rs/sqlx-sqlite/0.7.1/sqlx_sqlite/struct.SqliteConnectOptions.html#method.serialized and it did not help

I also tried https://docs.rs/sqlx-sqlite/0.7.1/sqlx_sqlite/enum.SqliteSynchronous.html#variant.Extra and the error still happens.

I may add a sleep at the end of catalog build

**Comment by carols10cents** [comment]
Reopening this-- @alamb I'm seeing `build_catalog` fail a bunch again, and I'm not sure what changed. It looks to me like the retry added in https://github.com/influxdata/influxdb_iox/pull/8271 isn't retrying? 

[Here's an example](https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/36696/workflows/35960c8c-b91f-4fea-a1b7-aa006e3808af/jobs/347040) - I only ever see [`** Retries remaining:  5`](https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/36696/workflows/35960c8c-b91f-4fea-a1b7-aa006e3808af/jobs/347040?invite=true#step-106-494) and then it fails; I don't see `** Retries remaining:  4` or fewer in the logs 😭

**Comment by alamb** [comment]
@carols10cents  When I looked at the history for that branch, it looks like the test started failing after this commit: https://github.com/influxdata/influxdb_iox/commit/149a4fbab805d03df966278c9fa7c05c8a5d5cce and I didn't see any examples of it passing on rerun, as I would expect for a flaky test:

https://app.circleci.com/pipelines/github/influxdata/influxdb_iox?branch=cn%2Fbackfill

![Screenshot 2023-08-16 at 8 15 14 AM](https://github.com/influxdata/influxdb_iox/assets/490673/e4f8ba3d-2289-4297-bf61-802e7ff8081a)

I wonder if the test failure could be due to a code change?

In terms of why the query is not being retried, I think the retries code only retries when the query returns zero rows. 

https://github.com/influxdata/influxdb_iox/blob/0d009e3467c7ca136df8deaad1fa4831b6650757/influxdb_iox/tests/end_to_end_cases/debug.rs#L129-L138

In the [example](https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/36696/workflows/35960c8c-b91f-4fea-a1b7-aa006e3808af/jobs/347040) failure, the query fails to run with an error about finding the parquet file:

> thread 'end_to_end_cases::debug::build_catalog' panicked at 'Error executing sql query: ArrowFlightError(Tonic(Status { code: InvalidArgument, message: "Parquet error: Parquet error: AsyncChunkReader::get_bytes error: Object at location 1/1/b862a7e9b329ee6a418cde191198eaeb1512753f19b87a81def2ae6c3d0ed237/b0fd6f9b-0013-460b-9772-8f18f46cae90.parquet not found: not found", source: None }))', /home/rust/project/test_helpers_end_to_end/src/client.rs:165:6

**Comment by carols10cents** [comment]
UGH yep, you're right, this is likely my fault. I got myself confused by some other log messages and other PRs I had going I think. Sorry for the bother!
