### ISSUE TITLE
Querier panics in DataFusion aggregation (`index out of bounds: the len is 0 but the index is 0`)

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#8264]
**Panic msg:**

`index out of bounds: the len is 0 but the index is 0`

**Panic location:**

`/usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/46182c8/datafusion/physical-expr/src/aggregate/first_last.rs:374:13`

**Backtrace:**

<details>

```text
   0: rust_begin_unwind


            at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5


   1: core::panicking::panic_fmt


             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14


   2: core::panicking::panic_bounds_check


             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:162:5


   3: <datafusion_physical_expr::aggregate::first_last::LastValueAccumulator as datafusion_expr::accumulator::Accumulator>::update_batch


             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/46182c8/datafusion/physical-expr/src/aggregate/first_last.rs:374:13


   4: <datafusion_physical_expr::aggregate::first_last::LastValueAccumulator as datafusion_expr::accumulator::Accumulator>::merge_batch


             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/46182c8/datafusion/physical-expr/src/aggregate/first_last.rs:393:9


   5: datafusion::physical_plan::aggregates::row_hash::GroupedHashAggregateStream::update_accumulators_using_batch::{{closure}}::{{closure}}


  6: core::iter::traits::iterator::Iterator::try_for_each::call::{{closure}}


             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/iter/traits/iterator.rs:2362:26


   7: core::iter::traits::iterator::Iterator::try_fold


             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/iter/traits/iterator.rs:2303:21


   8: core::iter::traits::iterator::Iterator::try_for_each


             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/iter/traits/iterator.rs:2365:9


   9: datafusion::physical_plan::aggregates::row_hash::GroupedHashAggregateStream::update_accumulators_using_batch::{{closure}}


             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/46182c8/datafusion/core/src/physical_plan/aggregates/row_hash.rs:456:22


 10: core::iter::traits::iterator::Iterator::try_for_each::call::{{closure}}


             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/iter/traits/iterator.rs:2362:26


  11: core::iter::traits::iterator::Iterator::try_fold


             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/iter/traits/iterator.rs:2303:21


  12: core::iter::traits::iterator::Iterator::try_for_each


             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/iter/traits/iterator.rs:2365:9


  13: datafusion::physical_plan::aggregates::row_hash::GroupedHashAggregateStream::update_accumulators_using_batch


             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/46182c8/datafusion/core/src/physical_plan/aggregates/row_hash.rs:422:14


  14: datafusion::physical_plan::aggregates::row_hash::GroupedHashAggregateStream::group_aggregate_batch


             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/46182c8/datafusion/core/src/physical_plan/aggregates/row_hash.rs:593:17


  15: <datafusion::physical_plan::aggregates::row_hash::GroupedHashAggregateStream as futures_core::stream::Stream>::poll_next


             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/46182c8/datafusion/core/src/physical_plan/aggregates/row_hash.rs:252:42


  16: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9


  17: futures_util::stream::stream::StreamExt::poll_next_unpin


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/mod.rs:1632:9


  18: <datafusion::physical_plan::projection::ProjectionStream as futures_core::stream::Stream>::poll_next


             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/46182c8/datafusion/core/src/physical_plan/projection.rs:384:31


  19: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9


  20: futures_util::stream::stream::StreamExt::poll_next_unpin


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/mod.rs:1632:9


  21: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/next.rs:32:21


  22: datafusion::physical_plan::stream::RecordBatchReceiverStreamBuilder::run_input::{{closure}}


             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/46182c8/datafusion/core/src/physical_plan/stream.rs:126:50


  23: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9


  24: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/core.rs:311:17


  25: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/loom/std/unsafe_cell.rs:14:9


  26: tokio::runtime::task::core::Core<T,S>::poll


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/core.rs:300:13


  27: tokio::runtime::task::harness::poll_future::{{closure}}


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/harness.rs:476:19


  28: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once


             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panic/unwind_safe.rs:271:9


  29: std::panicking::try::do_call


            at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:500:40


  30: std::panicking::try


             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:464:19


  31: std::panic::catch_unwind


             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panic.rs:142:14


  32: tokio::runtime::task::harness::poll_future


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/harness.rs:464:18


  33: tokio::runtime::task::harness::Harness<T,S>::poll_inner


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/harness.rs:198:27


  34: tokio::runtime::task::harness::Harness<T,S>::poll


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/harness.rs:152:15


  35: tokio::runtime::task::raw::RawTask::poll


          at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/raw.rs:200:18


  36: tokio::runtime::task::LocalNotified<S>::run


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/mod.rs:400:9


  37: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/multi_thread/worker.rs:639:22


  38: tokio::runtime::coop::with_budget


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/coop.rs:107:5


  39: tokio::runtime::coop::budget


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/coop.rs:73:5


  40: tokio::runtime::scheduler::multi_thread::worker::Context::run_task


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/multi_thread/worker.rs:575:9


  41: tokio::runtime::scheduler::multi_thread::worker::Context::run


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/multi_thread/worker.rs:526:24


  42: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::{{closure}}


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/multi_thread/worker.rs:491:21


  43: tokio::runtime::context::scoped::Scoped<T>::set


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context/scoped.rs:40:9


  44: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/multi_thread/worker.rs:486:9


  45: tokio::runtime::context::runtime::enter_runtime


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context/runtime.rs:65:16


  46: tokio::runtime::scheduler::multi_thread::worker::run


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/multi_thread/worker.rs:478:5


  47: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/multi_thread/worker.rs:447:45


  48: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/blocking/task.rs:42:21


  49: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9


  50: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}


            at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/core.rs:311:17


  51: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/loom/std/unsafe_cell.rs:14:9


  52: tokio::runtime::task::core::Core<T,S>::poll


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/core.rs:300:13


  53: tokio::runtime::task::harness::poll_future::{{closure}}


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/harness.rs:476:19


  54: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once


             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panic/unwind_safe.rs:271:9


 55: std::panicking::try::do_call


             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:500:40


  56: std::panicking::try


             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:464:19


  57: std::panic::catch_unwind


             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panic.rs:142:14


  58: tokio::runtime::task::harness::poll_future


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/harness.rs:464:18


  59: tokio::runtime::task::harness::Harness<T,S>::poll_inner


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/harness.rs:198:27


  60: tokio::runtime::task::harness::Harness<T,S>::poll


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/harness.rs:152:15


  61: tokio::runtime::task::raw::RawTask::poll


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/raw.rs:200:18


  62: tokio::runtime::task::UnownedTask<S>::run


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/mod.rs:437:9


  63: tokio::runtime::blocking::pool::Task::run


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/blocking/pool.rs:159:9


  64: tokio::runtime::blocking::pool::Inner::run


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/blocking/pool.rs:513:17


  65: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}


             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/blocking/pool.rs:471:13


note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

Sorry for the slightly messy formatting, had to extract it from the logging collector.

**Code location link:**

https://github.com/apache/arrow-datafusion/blob/46182c894e5106adba7fb53e9848ce666fb6129b/datafusion/physical-expr/src/aggregate/first_last.rs#L374

**Comment by alamb** [comment]
Well, that was easy to reproduce:

```shell
(arrow_dev) alamb@MacBook-Pro-8:~/Software/influxdb_iox2$ datafusion-cli
DataFusion CLI v28.0.0
❯ create table foo (x int) as values (1), (2);
0 rows in set. Query took 0.003 seconds.
❯ select last_value(x) from foo;
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /Users/alamb/Software/arrow-datafusion/datafusion/physical-expr/src/aggregate/first_last.rs:374:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Will file upstream ticket now

**Comment by alamb** [comment]
Filed https://github.com/apache/arrow-datafusion/issues/7118 upstream

**Comment by alamb** [comment]
This is fixed upstream and will be closed by https://github.com/influxdata/influxdb_iox/pull/8355
